- conf/chunkserver.conf.example
- conf/mds.conf
- conf/snapshot_clone_server.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/server.ini
fix: root username and password
> fix: root username and password

- curve-ansible/client.ini
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/etcd.conf.yml.j2
- curve-ansible/roles/install_package/defaults/main.yml
- curve-ansible/roles/install_package/tasks/include/determine_if_lib_installed.yml
- curve-ansible/roles/install_package/tasks/include/install_aws-sdk.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-chunkserver.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-mds.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-sdk.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-snapshotcloneserver.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-tools.yml
- curve-ansible/roles/install_package/tasks/include/install_daemon.yml
- curve-ansible/roles/install_package/tasks/include/install_etcd.yml
- curve-ansible/roles/install_package/tasks/include/install_lib_with_source_code.yml
- curve-ansible/roles/install_package/tasks/include/install_nebd.yml
- curve-ansible/roles/install_package/tasks/include/install_with_source_code.yml
- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/roles/install_package/templates/mds-daemon.sh.j2
- curve-ansible/roles/install_package/templates/nebd-daemon.j2
- curve-ansible/roles/install_package/vars/main.yml
- curve-ansible/server.ini
- tools/curvefsTool.cpp
Change-Id: I93ca609b4c192bf739e19061f1d5bc1fd989f0c5
> fix: curvefsTool and curve-ansible for centos

- src/mds/topology/topology_storge_etcd.cpp
- test/mds/topology/test_topology_storage_etcd.cpp
Change-Id: Idb3430d0379791ddeefa12a768263529c1d77d53
> set  chunkserver unstable when loaded

- README.md
- docs/README.md
**readme add Badge**
How it Works:
> 【doc】readme add Badge

- curve-ansible/deploy_curve.yml
- curve-ansible/roles/generate_config/templates/snapshot_tools.conf.j2
- curve-ansible/roles/install_package/tasks/include/install_curve-tools.yml
- curve-ansible/server.ini
- mk-deb.sh
- mk-tar.sh
- src/common/string_util.h
- src/snapshotcloneserver/clone/clone_service_manager.cpp
- src/snapshotcloneserver/clone/clone_service_manager.h
- src/snapshotcloneserver/common/define.cpp
- src/snapshotcloneserver/common/define.h
- src/snapshotcloneserver/snapshot/snapshot_service_manager.cpp
- src/snapshotcloneserver/snapshot/snapshot_service_manager.h
- src/snapshotcloneserver/snapshotclone_service.cpp
- src/snapshotcloneserver/snapshotclone_service.h
- test/snapshotcloneserver/mock_snapshot_server.h
- test/snapshotcloneserver/test_clone_service_manager.cpp
- test/snapshotcloneserver/test_snapshot_service_manager.cpp
- test/snapshotcloneserver/test_snapshotclone_service.cpp
- tools/snaptool/clone_or_recover.py
- tools/snaptool/common.py
- tools/snaptool/config.py
- tools/snaptool/curltool.py
- tools/snaptool/delete_or_cancel_snap.py
- tools/snaptool/parser.py
- tools/snaptool/queryclone.py
- tools/snaptool/querysnap.py
- tools/snaptool/snaptool
- tools/snaptool/snaptool.py
Problem Summary: add snaptool
What's Changed: add snaptool
How it Works: snaptool -h
- [ x] Relevant documentation/comments is changed or added
- [x ] I acknowledge that all my contributions will be made under the project's license
> add snaptool

- test/mds/nameserver2/namespace_service_test.cpp
> fix namespace_service_test

- src/snapshotcloneserver/clone/clone_core.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
fix a bug in snapshotcloneserver when we clone a file and delete it，then clone a file which has same filename will return a failure code -19。
change snapshotclone server code in clone.cpp to fix it。
How it Works:
When we clone a file which has same filename and notexist ，we try to search it on mds to find it notexist， then we continue to clone。
nothing
> fix clone has same dest bug

- CHANGELOG-1.1.md
Problem Summary: Add CHANGELOG-1.1
How it Works:
> Add CHANGELOG-1.1

- src/client/chunk_closure.cpp
- test/client/backoff_test.cpp
Problem Summary: Fix curve-client unittest failed
How it Works:
> test: fix client ut failed

- docs/cn/deploy.md
> Modify the download version in deploy doc

- robot/Resources/config/config.py
- robot/Resources/keywords/test_curve_stability_nbd.py
- robot/curve_failover_robot.txt
> add snapshotclone tests

- conf/chunkserver.conf.example
- deploy/local/chunkserver/conf/chunkserver.conf.0
- deploy/local/chunkserver/conf/chunkserver.conf.1
- deploy/local/chunkserver/conf/chunkserver.conf.2
- src/chunkserver/chunkserver.cpp
- src/chunkserver/trash.cpp
- src/chunkserver/trash.h
- test/chunkserver/metrics_test.cpp
- test/chunkserver/trash_test.cpp
- test/integration/common/config_generator.h
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_recover_test.cpp
> fix trash have not recycle wal bug

- curve-ansible/clean_curve.yml
- curve-ansible/deploy_walpool.yml
- curve-ansible/release_disk_5%_space.yml
- curve-ansible/roles/clean/files/recycle_chunks.sh
- curve-ansible/roles/clean/tasks/include/clean_chunkserver.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_retain_chunkfilepool.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_totally.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_with_disk_format.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_without_disk_format.yml
- curve-ansible/roles/clean/tasks/include/clean_curve_sdk.yml
- curve-ansible/roles/clean/tasks/include/clean_etcd.yml
- curve-ansible/roles/clean/tasks/include/clean_mds.yml
- curve-ansible/roles/clean/tasks/include/clean_snapshotcloneserver.yml
- curve-ansible/roles/clean/tasks/include/clean_snapshotcloneserver_nginx.yml
- curve-ansible/roles/format_chunkserver/tasks/include/prepare_chunkserver_with_disk_format.yml
- curve-ansible/roles/format_chunkserver/tasks/include/prepare_chunkserver_without_disk_format.yml
- curve-ansible/roles/format_chunkserver/tasks/main.yml
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/roles/install_package/templates/chunkserver_deploy.sh.j2
- curve-ansible/roles/start_service/tasks/include/start_by_daemon.yml
- curve-ansible/roles/stop_service/tasks/include/stop_by_daemon.yml
- curve-ansible/server.ini
- curve-ansible/stop_curve.yml
- curve-chunkserver/home/nbs/chunkserver_deploy.sh
- mk-deb.sh
- robot/Resources/keywords/deploy.py
Problem Summary: support retain chunkfilepool and walpool when clean
How it Works:
> support retain chunkfilepool when clean

- src/chunkserver/config_info.h
- test/integration/cluster_common/cluster_basic_test.cpp
- test/integration/raft/raft_snapshot_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_recover_test.cpp
> fix ci write file fail bug

- src/mds/common/mds_define.cpp
- src/mds/common/mds_define.h
> 【translate】mds/common

- CHANGELOG-1.1.md
Issue Number: No
What's Changed: Add release-1.1 performance test data
> Add release-1.1 performance test data

- test/chunkserver/copyset_node_test.cpp
- test/integration/raft/raft_config_change_test.cpp
- test/integration/raft/raft_log_replication_test.cpp
- test/integration/raft/raft_snapshot_test.cpp
- test/integration/raft/raft_vote_test.cpp
Separate raft integration test log to convenience to analysis.
How it Works:
> separate raft integration test log

- docs/cn/curve-client.md
- docs/en/client_en.md
> 【translate】doc/en/client_en.md

- README.md
- README_en.md
> 【translate】 README_en.md

- docs/cn/chunkserver_design.md
- docs/cn/quality.md
- docs/en/chunkserver_design_en.md
- docs/en/quality_en.md
> 【translate】doc/en/chunkserver_design_en.md & quality_en.md 

- monitor/grafana/dashboards/mds.json
> Add grafana mds config panel in mds-dashboard

- src/mds/nameserver2/allocstatistic/alloc_statistic.cpp
- src/mds/nameserver2/allocstatistic/alloc_statistic.h
- src/mds/nameserver2/allocstatistic/alloc_statistic_helper.cpp
- src/mds/nameserver2/allocstatistic/alloc_statistic_helper.h
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/file_lock.cpp
- src/mds/nameserver2/file_lock.h
- src/mds/nameserver2/file_record.cpp
- src/mds/nameserver2/file_record.h
- src/mds/nameserver2/idgenerator/chunk_id_generator.h
- src/mds/nameserver2/idgenerator/etcd_id_generator.cpp
- src/mds/nameserver2/idgenerator/etcd_id_generator.h
- src/mds/nameserver2/idgenerator/inode_id_generator.h
- src/mds/nameserver2/nameserverMetrics.h
- src/mds/nameserver2/namespace_service.cpp
- src/mds/nameserver2/namespace_service.h
- src/mds/nameserver2/namespace_storage.cpp
- src/mds/nameserver2/namespace_storage.h
- src/mds/nameserver2/namespace_storage_cache.cpp
- src/mds/nameserver2/namespace_storage_cache.h
> 【translate】mds/nameserver2

- curve-ansible/README.md
- curve-ansible/check_chunkserver.yml
- curve-ansible/clean_curve.yml
- curve-ansible/client.ini
- curve-ansible/deploy_curve.yml
- curve-ansible/deploy_curve_sdk.yml
- curve-ansible/deploy_monitor.yml
- curve-ansible/deploy_walpool.yml
- curve-ansible/release_disk_5%_space.yml
- curve-ansible/roles/generate_config/tasks/include/generate_config_with_template.yml
- curve-ansible/roles/generate_config/tasks/include/update_config_with_puppet.yml
- curve-ansible/roles/generate_config/tasks/main.yml
- curve-ansible/roles/install_package/templates/mds-daemon.sh.j2
- curve-ansible/roles/restart_service/tasks/include/restart_mds.yml
- curve-ansible/roles/restart_service/tasks/include/restart_nebd.yml
- curve-ansible/roles/restart_service/tasks/include/restart_one_chunkserver.yml
- curve-ansible/roles/restart_service/tasks/include/restart_snapshotclone.yml
- curve-ansible/rolling_update_curve.yml
- curve-ansible/server.ini
- curve-ansible/start_curve.yml
- curve-ansible/stop_curve.yml
- curve-mds/home/nbs/mds-daemon.sh
- docs/cn/deploy.md
Fix curve-ansible become method, and provide generate config with puppet
How it Works:
> fix curve-ansible: become, generate_config

- curve-ansible/roles/install_package/templates/chunkserver_deploy.sh.j2
- curve-chunkserver/home/nbs/chunkserver_deploy.sh
Issue Number: No
chunkserver deploy one may failed to mount SSD to data dir.
Remove existing mount record from fstab, and then add new record
How it Works:
> scripts: fix deploy one may mount data-dir to system-disk

- src/kvstorageclient/etcd_client.cpp
Problem Summary: fix mds mem leak in etcd client
What's Changed: fix mds mem leak in etcd client
How it Works: fix mds mem leak in etcd client
need urgent bug fix
> fix_mds_mem_leak

- curve-ansible/client.ini
- curve-ansible/common_tasks/start_service.yml
- curve-ansible/deploy_curve.yml
- curve-ansible/deploy_curve_sdk.yml
- curve-ansible/deploy_nbd.yml
- curve-ansible/deploy_nebd.yml
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/client.conf.j2
- curve-ansible/roles/restart_service/tasks/include/restart_one_chunkserver.yml
- curve-ansible/roles/start_service/tasks/include/start_chunkserver.yml
- curve-ansible/server.ini
- curve-chunkserver/home/nbs/chunkserver_deploy.sh
add tags at prepare software environment to skip.
How it Works:
> add tags at prepare software environment

- curve-ansible/common_tasks/auto_get_disk_list.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-chunkserver.yml
- curve-ansible/server.ini
support get disk list automatically when format disk
How it Works:
> ansible support get disk list automatically

- robot/Resources/keywords/deploy.py
- robot/ansible_deploy.sh
- robot/curve_failover_robot.txt
> use ansible deploy curve

- src/kvstorageclient/etcd_client.cpp
- test/integration/client/chunkserver_exception_test.cpp
- test/integration/client/config/topo_example_1.json
- test/integration/cluster_common/cluster_basic_test.cpp
- test/integration/raft/raft_snapshot_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_recover_test.cpp
Problem Summary: fix mds mem leak in etcd client
What's Changed:fix mds mem leak in etcd client
How it Works:fix mds mem leak in etcd client
> fix mds mem leak in etcd client

- src/mds/chunkserverclient/chunkserver_client.cpp
- src/mds/chunkserverclient/chunkserver_client.h
- src/mds/chunkserverclient/copyset_client.cpp
- src/mds/chunkserverclient/copyset_client.h
> 【translate】mds/chunkserverclient

- curve-ansible/clean_nebd.yml
- curve-ansible/roles/install_package/tasks/include/install_nebd.yml
- curve-ansible/roles/stop_service/tasks/include/stop_nebd.yml
- curve-ansible/server.ini
- curve-ansible/stop_nebd_server.yml
- nebd/nebd-package/usr/bin/nebd-daemon
1、clean nebd when clean nebd。2、modify get disk list cmd。3、let nebd-daemon installed in curve_bin_dir
How it Works:
> stop nebd-server when clean nebd

- nebd/nebd-package/usr/bin/nebd-daemon
> scripts: fix nebd-daemon may stop failed

- curve-ansible/roles/install_package/templates/nebd-daemon.j2
> ansible: fix nebd-daemon may stop failed

- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/DEBIAN/postrm
- nbd/nbd-package/etc/nbd/k8s_curve.conf
- nbd/nbd-package/usr/bin/mount_curve_clouddisk.sh
> Add mount curve  cloud disk script for k8s compute node

- curve-ansible/common_tasks/install_with_yum_apt.yml
- curve-ansible/roles/prepare_software_env/tasks/main.yml
Determine if package exists with dpkg or yum before installing.
How it Works:
> Determine if package exists before installing

- curve-ansible/roles/install_package/templates/nebd-daemon.j2
- nebd/nebd-package/DEBIAN/control
- nebd/nebd-package/usr/bin/nebd-daemon
fix jemalloc dependecy on Debian10
How it Works:
> nebd: fix jemalloc dependecy and shared library path

- src/mds/main/main.cpp
- src/mds/server/mds.cpp
- src/mds/server/mds.h
> 【translate】mds/server and mds/main

- src/mds/copyset/copyset_config.h
- src/mds/copyset/copyset_manager.cpp
- src/mds/copyset/copyset_manager.h
- src/mds/copyset/copyset_policy.cpp
- src/mds/copyset/copyset_validation.cpp
- src/mds/copyset/copyset_validation.h
> 【translate】mds/copyset

- src/mds/topology/topology.cpp
- src/mds/topology/topology.h
- src/mds/topology/topology_chunk_allocator.cpp
- src/mds/topology/topology_chunk_allocator.h
- src/mds/topology/topology_config.h
- src/mds/topology/topology_item.h
- src/mds/topology/topology_metric.cpp
- src/mds/topology/topology_metric.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- src/mds/topology/topology_stat.h
- src/mds/topology/topology_storage_codec.h
- src/mds/topology/topology_storge_etcd.h
- src/mds/topology/topology_token_generator.cpp
> 【translate】mds/topology

- src/mds/schedule/coordinator.cpp
- src/mds/schedule/coordinator.h
- src/mds/schedule/copySetScheduler.cpp
- src/mds/schedule/leaderScheduler.cpp
- src/mds/schedule/operator.h
- src/mds/schedule/operatorController.h
- src/mds/schedule/operatorFactory.h
- src/mds/schedule/operatorStep.cpp
- src/mds/schedule/operatorStep.h
- src/mds/schedule/rapidLeaderScheduler.cpp
- src/mds/schedule/recoverScheduler.cpp
- src/mds/schedule/replicaScheduler.cpp
- src/mds/schedule/scheduleMetrics.cpp
- src/mds/schedule/scheduleMetrics.h
- src/mds/schedule/schedule_define.h
- src/mds/schedule/scheduler.cpp
- src/mds/schedule/scheduler.h
- src/mds/schedule/scheduler_helper.cpp
- src/mds/schedule/scheduler_helper.h
- src/mds/schedule/topoAdapter.cpp
- src/mds/schedule/topoAdapter.h
> 【translate】mds/schedule

- build.sh
- docs/cn/build_and_run.md
- mk-deb.sh
- mk-tar.sh
Problem Summary:  add build.sh, add bazel version check, add build commit id
What's Changed: add build.sh, add bazel version check, add build commit id
How it Works: add build.sh, add bazel version check, add build commit id
> add build.sh, add bazel version check, add build commit id

- curve-ansible/roles/clean/files/recycle_chunks.sh
Change-Id: I44392dbf95527080bda3c9edcc564c4a626fd6b7
How it Works:
> recycle chunk under raft_snapshot

- curve-ansible/roles/clean/files/recycle_chunks.sh
optimize recycle_chunks.sh
How it Works:
> recycle_chunks do not deploy

- src/snapshotcloneserver/clone/clone_core.cpp
- test/snapshotcloneserver/test_clone_core.cpp
fix clone has multi dest file bug 
What's Changed:  when clone find same dest file also judge the inodeid
How it Works:
> fix clone multi dest file bug

- src/common/namespace_define.h
- src/mds/topology/topology_storage_codec.cpp
- src/mds/topology/topology_storage_codec.h
- src/mds/topology/topology_storge_etcd.cpp
- test/mds/topology/test_topology_storage_codec.cpp
> fix copyset codec bug

- src/chunkserver/raftsnapshot/curve_file_service.cpp
Change-Id: I972235588f16ddbb5175b634647470e167b67593
Modify the log level of CurveFileService to be consistent with braft file service.
How it Works:
> modify curve file service log level

- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/test_curve_stability_nbd.py
- robot/ansible_deploy.sh
- robot/curve_failover_robot.txt
> use ansible deploy

- src/chunkserver/raftsnapshot/curve_file_service.cpp
- src/common/namespace_define.h
- src/mds/topology/topology_storage_codec.cpp
- src/mds/topology/topology_storage_codec.h
- src/mds/topology/topology_storge_etcd.cpp
- src/snapshotcloneserver/clone/clone_core.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/mds/topology/test_topology_storage_codec.cpp
- test/snapshotcloneserver/test_clone_core.cpp
> Cherry-pick bugfix for snapshotcloneserver from master

- robot/Resources/keywords/base_operate.py
> fix kill process bug

- src/chunkserver/raftsnapshot/curve_file_service.cpp
- src/common/namespace_define.h
- src/mds/topology/topology_storage_codec.cpp
- src/mds/topology/topology_storage_codec.h
- src/mds/topology/topology_storge_etcd.cpp
- src/snapshotcloneserver/clone/clone_core.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/mds/topology/test_topology_storage_codec.cpp
- test/snapshotcloneserver/test_clone_core.cpp
> Cherry-pick some bugfix for snapshotcloneserver from master

- README_en.md
Issue Number: NULL 
Problem Summary: NULL
What's Changed: Add curve logo to readme file
How it Works: NULL
Side effects(Breaking backward compatibility? Performance regression?): NULL
> Add curve logo to readme file

- curvefs_python/BUILD_bak
- curvefs_python/__init__.py
- curvefs_python/configure.sh
- curvefs_python/curvefs_wrap.cxx
- mk-deb.sh
- mk-tar.sh
> curvefs_python: add build options for python2/3

- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/snapshot_clone_server.conf.j2
Problem Summary: add 2 clone conf to ansible template
What's Changed: add 2 clone conf to ansible template
How it Works: add 2 clone conf to ansible template
Side effects(Breaking backward compatibility? Performance regression?): no
> add 2 clone conf to ansible template

- curvefs_python/configure.sh
- mk-deb.sh
- mk-tar.sh
> fix: skip build curvefs when configure failed

- robot/Resources/keywords/fault_inject.py
> get down chunkserver chunk

- mk-deb.sh
- mk-tar.sh
fix bazel options for high gcc version (bazel option -faligned-new is depended)
> fix bazel build option

- src/client/io_tracker.cpp
- src/client/request_closure.cpp
- src/client/request_closure.h
- test/chunkserver/braft_cli_service2_test.cpp
- test/integration/client/unstable_chunkserver_exception_test.cpp
> fix: check whether own inflight count

- src/client/client_common.h
- src/client/io_tracker.cpp
- src/client/request_sender.cpp
- src/client/request_sender.h
- test/chunkserver/braft_cli_service2_test.cpp
> fix: forget set some fields in RequestSender

- src/client/chunk_closure.cpp
- src/client/mds_client.cpp
- src/client/metacache.cpp
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/namespace_service.cpp
- src/mds/schedule/recoverScheduler.cpp
Problem Summary: adjust log level
What's Changed: adjust log level
How it Works: adjust log level
> adjust log level

- test/chunkserver/braft_cli_service2_test.cpp
Change-Id: If291ad964eb7473a9c96971ea73eaf738da44e21
How it Works:
> fix braft_cli_service2_test

- src/client/client_config.cpp
- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/io_tracker.cpp
- src/client/io_tracker.h
- src/client/iomanager4file.h
- src/client/libcurve_client.cpp
- src/client/libcurve_file.cpp
- src/client/source_reader.cpp
- src/client/source_reader.h
- test/client/iotracker_splitor_unittest.cpp
- test/client/libcurve_client_unittest.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
> client: refactor SourceReader

- curve-ansible/common_tasks/wait_copysets_status_healthy.yml
- curve-ansible/deploy_curve.yml
- curve-ansible/release_disk_5%_space.yml
- curve-ansible/roles/generate_config/tasks/include/generate_config_with_template.yml
- curve-ansible/roles/install_package/tasks/include/copy_file_to_remote.yml
- curve-ansible/roles/install_package/tasks/include/install_deb_package.yml
- curve-ansible/roles/install_package/tasks/main.yml
- curve-ansible/roles/rapid_leader_schedule/defaults/main.yml
- curve-ansible/roles/rapid_leader_schedule/tasks/include/rapid_leader_schedule_with_tool.yml
- curve-ansible/roles/rapid_leader_schedule/tasks/main.yml
- curve-ansible/roles/rapid_leader_schedule/templates/check_leader_range.sh.j2
- curve-ansible/roles/restart_service/tasks/include/check_version_after_restart.yml
- curve-ansible/roles/restart_service/tasks/include/restart_chunkserver.yml
- curve-ansible/roles/restart_service/tasks/include/restart_mds.yml
- curve-ansible/roles/restart_service/tasks/include/restart_snapshotclone.yml
- curve-ansible/roles/set_leader_and_follower_list/tasks/include/get_etcd_leader_ip.yml
- curve-ansible/roles/set_leader_and_follower_list/tasks/include/get_mds_leader_ip.yml
- curve-ansible/roles/set_leader_and_follower_list/tasks/include/get_snapshot_leader_ip.yml
- curve-ansible/roles/set_leader_and_follower_list/tasks/main.yml
- curve-ansible/rolling_update_curve.yml
- curve-ansible/server.ini
- src/tools/schedule_tool.cpp
- src/tools/schedule_tool.h
- test/tools/mock/mock_mds_client.h
- test/tools/schedule_tool_test.cpp
Change-Id: I16ae65949bf27dd7b8a5a9c1fc27443a200c0acb
How it Works:
> leader schedule when deploy, and config backup

- curve-ansible/roles/install_package/tasks/include/copy_file_to_remote.yml
Change-Id: I4208d3b106e452b24608e04e4eb8d5847ede3195
How it Works:
> fix copy file to remote with mv

- curve-ansible/roles/rapid_leader_schedule/tasks/main.yml
Change-Id: Id477560a1cde85d6b109f8428af84382788617ef
Fix the bug that misjudge the rapid leader schedule.
How it Works:
> fix rapid leader schedule

- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/test_curve_stability_nbd.py
- robot/ansible_deploy.sh
- robot/curve_failover_robot.txt
- robot/init_env.sh
> add lazy clone file flatten and snapshot test

- src/mds/nameserver2/clean_task.h
- src/mds/nameserver2/clean_task_manager.cpp
- src/snapshotcloneserver/clone/clone_core.cpp
- test/mds/nameserver2/clean_task_manager_test.cpp
fix clean manager retry & clone from snapshot do not send clonesource
How it Works:
> mds : fix clean manager retry

- curve-ansible/roles/install_package/templates/nebd-daemon.j2
- nebd/nebd-package/DEBIAN/control
- nebd/nebd-package/usr/bin/nebd-daemon
- src/client/client_metric.h
- src/client/io_tracker.cpp
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/mds/schedule/operatorController.cpp
> backport: cherry-pick some bugfix to release1.0

- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/nebd-server.conf.j2
> fix: nebd-server.conf in ansible

- src/client/client_metric.h
- src/client/io_tracker.cpp
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/mds/schedule/operatorController.cpp
> client/mds: chang some log level

- src/client/lease_executor.h
- src/mds/nameserver2/curvefs.cpp
- src/mds/schedule/operatorController.cpp
- src/snapshotcloneserver/snapshot/snapshot_core.cpp
- test/mds/nameserver2/curvefs_test.cpp
- test/snapshotcloneserver/test_snapshot_core.cpp
> Cherry-pick 2 commit from master

- test/integration/client/unstable_chunkserver_exception_test.cpp
> unittest: lower the judgment threshold

- robot/Resources/keywords/test_curve_stability_nbd.py
- robot/curve_failover_robot.txt
> open test case:check md5 false

- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/mds.conf.j2
Problem Summary:  mds snapshot addr ansible config is error
What's Changed: fix mds snapshot_addr conf
How it Works: fix mds snapshot_addr conf
> fix mds snapshot_addr conf

- curve-ansible/roles/install_package/templates/chunkserver_deploy.sh.j2
- curve-chunkserver/home/nbs/chunkserver_deploy.sh
- curvefs_python/BUILD_bak
- proto/BUILD
- proto/common.proto
- proto/nameserver2.proto
- proto/topology.proto
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/namespace_service.cpp
- src/mds/nameserver2/namespace_service.h
- src/mds/topology/topology_service_manager.cpp
- src/tools/BUILD
- src/tools/copyset_check.cpp
- src/tools/copyset_check.h
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- test/mds/nameserver2/curvefs_test.cpp
- test/mds/nameserver2/namespace_service_test.cpp
- test/tools/copyset_check_core_test.cpp
- test/tools/copyset_check_test.cpp
- test/tools/curve_tool_factory_test.cpp
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_copyset_check_core.h
- test/tools/mock/mock_mds_client.h
- test/tools/mock/mock_namespace_service.h
Change-Id: I0bf2dbe171cab2080b05de6ea2bc0c59bd6c71ff
curve_ops_tool support list all volumes on majority-peers-offline copysets.
How it Works:
> mds/tools: add list volumes on majority-peers-offline copysets

- test/chunkserver/clone/BUILD
- test/chunkserver/clone/clone_copyer_test.cpp
- test/client/BUILD
- test/client/libcurve_client_unittest.cpp
- test/client/mock/mock_file_client.h
- test/tools/BUILD
Problem Summary: libcurve_client_unittest sometimes gets stuck on exit
What's Changed: Rewrite libcurve_client_unittest with mock
How it Works:
> unittest: rewrite libcurve_client_unittest

- robot/Resources/keywords/base_operate.py
> print exist process

- conf/mds.conf
- src/mds/server/mds.cpp
- src/mds/topology/topology_chunk_allocator.cpp
- src/mds/topology/topology_chunk_allocator.h
- src/mds/topology/topology_config.h
- test/mds/topology/test_topology_chunk_allocator.cpp
> mds: add config for enableLogicalPoolStatus

- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/mds.conf.j2
> ansible: add ansible config enableLogicalPoolStatus

- conf/mds.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/mds.conf.j2
- src/mds/server/mds.cpp
- src/mds/topology/topology_chunk_allocator.cpp
- src/mds/topology/topology_chunk_allocator.h
- src/mds/topology/topology_config.h
- test/mds/topology/test_topology_chunk_allocator.cpp
> Cherry-pick some bugfix to Release1.2

- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-chunkserver/home/nbs/chunkserver_ctl.sh
> curve-chunkserver: fix chunkserver_ctl.sh grep error

- robot/Resources/config/config.py
- robot/Resources/keywords/fault_inject.py
- robot/curve_choas.txt
> add choas tests

- curve-ansible/check_debain_package.yml
- curve-ansible/common_tasks/check_debain_package.yml
> curve-ansible: add check_debain.yml

- curve-ansible/ping.yml
> curve-ansible: add ping.yml to check ssh connection

- nbd/src/NBDController.cpp
- nbd/src/NBDTool.cpp
- nbd/src/define.h
- nbd/src/main.cpp
- nbd/src/util.cpp
- robot/Resources/keywords/test_curve_stability_nbd.py
> robot: redirect curve-nbd console log

- CHANGELOG-1.2.md
Problem Summary: add CHANGELOG-1.2.md
What's Changed: add CHANGELOG-1.2.md
How it Works: add CHANGELOG-1.2.md
> add CHANGELOG-1.2.md

- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-chunkserver/home/nbs/chunkserver_ctl.sh
> do not use wal pool

- curve-mds/home/nbs/etcd-daemon.sh
- curve-mds/home/nbs/mds-daemon.sh
- curve-snapshotcloneserver/home/nbs/snapshot-daemon.sh
> script: fix exit bug in daemon.sh

- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
What's Changed: translate build_and_run.md 
How it Works:
> docs: translate build_and_run.md

- src/mds/nameserver2/namespace_service.cpp
- test/common/test_timeutility.cpp
- tools/snaptool/clone_or_recover.py
Problem Summary: fix mds log level, fix snaptool
What's Changed: fix mds log level, fix snaptool
How it Works: fix mds log level, fix snaptool
Side effects(Breaking backward compatibility? Performance regression?):  NO
> fix mds log level, fix snaptool

- curve-ansible/roles/install_package/templates/snapshot-daemon.sh.j2
- curve-snapshotcloneserver/home/nbs/snapshot-daemon.sh
- src/client/libcurve_file.cpp
> fix: snapshot-daemon.sh and log-level in client

- src/tools/curve_cli.cpp
> curve-tools: add the support command DoSnapshotAll

- curvefs_python/curvefs_tool.py
Problem Summary: fix create vol bug
What's Changed: curvefs_tool.py
How it Works:
curve create --filename xxx --length xxx --user xxx --stripeCount xxx --stripeUnit xxx 
no side effects
> fix: curvefs_tool.py create vol stripe

- src/tools/status_tool.cpp
> curve-tools: add more info to display the logical pool

- src/tools/common.cpp
- src/tools/common.h
- src/tools/metric_name.h
- src/tools/status_tool.cpp
- src/tools/status_tool.h
- test/tools/status_tool_test.cpp
> curve_ops_tool: fix get walpool left size

- conf/client.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/client.conf.j2
- src/client/client_config.cpp
- src/client/config_info.h
- src/client/iomanager4file.cpp
- src/client/iomanager4file.h
- test/client/client_unittest_main.cpp
> client: add throttle.enable config

- src/chunkserver/clone_copyer.cpp
- src/client/io_tracker.cpp
- src/client/io_tracker.h
- src/client/iomanager4file.cpp
- src/client/iomanager4file.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- src/client/mds_client.cpp
- src/client/service_helper.cpp
- src/client/source_reader.cpp
- src/client/splitor.cpp
- src/client/splitor.h
- test/chunkserver/clone/clone_copyer_test.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/client/mock/mock_file_client.h
> client: add option for read/write stripe file as normal

- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/test_curve_stability_nbd.py
> use stripe vol

- src/mds/nameserver2/curvefs.cpp
Problem Summary:  fix stripe bug that too small stripeUnit cause io error
What's Changed: change mds CheckStripeParam
How it Works: change mds CheckStripeParam
>  bugfix/client: fix stripe bug that too small stripeUnit cause io error

- src/chunkserver/chunkserver.cpp
- src/chunkserver/chunkserver_metrics.cpp
- src/chunkserver/chunkserver_metrics.h
- src/chunkserver/config_info.cpp
- src/chunkserver/config_info.h
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/copyset_node_manager.h
- src/chunkserver/heartbeat.cpp
- src/chunkserver/passive_getfn.cpp
- src/chunkserver/passive_getfn.h
- src/chunkserver/raftlog/curve_segment.cpp
- src/chunkserver/raftlog/curve_segment.h
- src/chunkserver/raftlog/curve_segment_log_storage.cpp
- src/chunkserver/raftlog/curve_segment_log_storage.h
- src/chunkserver/trash.cpp
- test/chunkserver/metrics_test.cpp
- test/chunkserver/raftlog/test_curve_segment.cpp
- test/chunkserver/raftlog/test_curve_segment_log_storage.cpp
- test/chunkserver/trash_test.cpp
Problem Summary: Stat chunk bytes related metric not include WAL segment 
What's Changed: Browse commit for detail
How it Works: Browse commit for detail
Side effects(Breaking backward compatibility? Performance regression?): none
> chunkserver: stat chunk bytes related  metric include WAL segment 

- conf/mds.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/mds.conf.j2
- src/mds/common/mds_define.h
- src/mds/main/main.cpp
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/server/mds.cpp
- test/mds/nameserver2/chunk_allocator_test.cpp
- test/mds/nameserver2/clean_core_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
- test/mds/nameserver2/namespace_service_test.cpp
- test/tools/mds_client_test.cpp
- test/tools/status_tool_test.cpp
Problem Summary: change file param from hard code to config file
What's Changed:  change file param from hard code to config file
How it Works: change file param from hard code to config file
> mds: change file param from hard code to config file

- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
Issue Number: #325  
What's Changed: parameters' name
How it Works:
> fix a todo: rename parameters

- src/client/libcbd_libcurve.cpp
Issue Number: #327  
How it Works:
> fix a todo: add return value check

- README.md
- docs/en/deploy_en.md
> docs: translate deploy.md

- curve-ansible/roles/clean/files/recycle_chunks.sh
> ansible: fix calc max chunk id error when recycle copysets

- src/chunkserver/braft_cli_service.h
- src/chunkserver/braft_cli_service2.h
Submit again.
A simple code translation, The changes occurred in the following files:
/curve/src/chunkserver/braft_cli_service.h
/curve/src/chunkserver/braft_cli_service2.h
> Code translation;

- curve-ansible/roles/stop_service/tasks/include/stop_nebd.yml
> ansible: fix stop nebd error

- curve-ansible/roles/install_package/defaults/main.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
- mk-tar.sh
- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/DEBIAN/prerm
- nbd/nbd-package/etc/curve/curvetab
- nbd/nbd-package/usr/map_curve_disk.sh
- nbd/src/define.h
- nbd/src/main.cpp
> v1.0.4-beta

- nebd/nebd-package/DEBIAN/prerm
- tools/BUILD
- tools/curvefsTool.cpp
- tools/curvefsTool.h
> curve_tool: fix log

- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
> ansible: fix copy file failed

- src/common/fs_util.h
- src/common/string_util.h
- src/mds/nameserver2/curvefs.cpp
- src/tools/namespace_tool.cpp
- src/tools/namespace_tool_core.cpp
- src/tools/namespace_tool_core.h
- test/mds/nameserver2/fakes.h
- test/mds/nameserver2/namespace_service_test.cpp
- test/tools/mock/mock_namespace_tool_core.h
- test/tools/namespace_tool_core_test.cpp
- test/tools/namespace_tool_test.cpp
> tools: clean recycle bin with expire time

- conf/mds.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/mds.conf.j2
- src/common/concurrent/dlock.h
- src/mds/nameserver2/BUILD
- src/mds/nameserver2/clean_manager.cpp
- src/mds/nameserver2/clean_manager.h
- src/mds/nameserver2/clean_task.h
- src/mds/server/mds.cpp
- src/mds/server/mds.h
- src/snapshotcloneserver/clone/clone_closure.h
- src/snapshotcloneserver/clone/clone_service_manager.cpp
- src/snapshotcloneserver/clone/clone_service_manager.h
- src/snapshotcloneserver/clone/clone_task.h
> add dlock in discard

- test/common/rw_lock_test.cpp
> unit test:fix rw lock unit test fail

- monitor/grafana/dashboards/chunkserver.json
- monitor/grafana/dashboards/client.json
- monitor/grafana/dashboards/etcd.json
- monitor/grafana/dashboards/mds.json
- monitor/grafana/dashboards/report.json
- monitor/grafana/dashboards/snapshotcloneserver.json
update dashbord json
How it Works:
> monitor: update dashbord json

- curvefs/proto/BUILD
- curvefs/proto/common.proto
- curvefs/proto/mds.proto
- curvefs/proto/metaserver.proto
- curvefs/proto/space.proto
Problem Summary: add fs proto
What's Changed: add fs proto
How it Works: add fs proto
Side effects(Breaking backward compatibility? Performance regression?):  NO
> add curvefs proto

- src/mds/heartbeat/topo_updater.cpp
- test/mds/heartbeat/heartbeat_manager_test.cpp
fix/mds: modify stale heartbeat update error with warning
How it Works:
> fix/mds: modify stale heartbeat update error with warning

- curvefs/src/client/BUILD
- curvefs/src/client/block_device_client.cpp
- curvefs/src/client/block_device_client.h
- curvefs/src/client/config.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/curve_fuse_op.h
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/dir_buffer.cpp
- curvefs/src/client/dir_buffer.h
- curvefs/src/client/error_code.h
- curvefs/src/client/extent.h
- curvefs/src/client/extent_manager.cpp
- curvefs/src/client/extent_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_common.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/main.c
- curvefs/src/client/mds_client.cpp
- curvefs/src/client/mds_client.h
- curvefs/src/client/metaserver_client.cpp
- curvefs/src/client/metaserver_client.h
- curvefs/test/client/BUILD
- curvefs/test/client/main.cpp
> curvefs : add curvefs client framework

- .gitignore
- test/client/BUILD
- test/client/client_mdsclient_metacache_unittest.cpp
- test/client/client_metric_test.cpp
- test/client/client_session_unittest.cpp
- test/client/client_unittest_main.cpp
- test/client/fake/client_workflow_test.cpp
- test/client/libcbd_libcurve_test.cpp
- test/client/mds_failover_test.cpp
- test/resources.list
> test: seperate an unittest of client

- conf/chunkserver.conf.example
- curve-ansible/client.ini
- curve-ansible/common_tasks/check_if_nbd_exists_in_kernel.yml
- curve-ansible/deploy_curve.yml
- curve-ansible/deploy_curve_sdk.yml
- curve-ansible/deploy_nbd.yml
- curve-ansible/deploy_nebd.yml
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/rolling_update_curve_sdk.yml
- curve-ansible/rolling_update_nbd.yml
- curve-ansible/rolling_update_nebd.yml
- curve-ansible/server.ini
- curve-chunkserver/home/nbs/chunkserver_ctl.sh
> ansible: fixed some ansible bugs

- src/common/leaky_bucket.cpp
- src/mds/nameserver2/curvefs.cpp
- test/common/leaky_bucket_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
> common/mds: fix dynamic set LeakyBucket may hang requests and remove throttle parameters of directories

- curve-ansible/common_tasks/get_chunkserver_number.yml
- curve-ansible/common_tasks/restart_service.yml
- curve-ansible/deploy_nebd.yml
- curve-ansible/rolling_update_nebd.yml
- curve-ansible/start_nebd_server.yml
> ansible: fix get chunkserver number

- curve-ansible/roles/clean/files/recycle_chunks.sh
> ansible: fix calc max segment id error when recycle copysets

- curvefs/proto/BUILD
> build: fixed generate same name library

- src/common/s3_adapter.cpp
> common : fix s3 adaptor init config bug

- robot/Resources/config/config.py
- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/test_curve_stability_nbd.py
- robot/curve_choas.txt
- robot/curve_failover_robot.txt
> robot:add failover test case

- src/mds/heartbeat/topo_updater.cpp
- src/mds/schedule/scanScheduler.cpp
- src/mds/server/mds.cpp
- src/mds/topology/topology.cpp
- src/mds/topology/topology_item.h
> mds: fixed some bugs for scan

- src/client/copyset_client.cpp
- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/iomanager4file.cpp
- src/client/lease_executor.cpp
- src/client/lease_executor.h
- src/client/metacache.cpp
- test/client/BUILD
- test/client/lease_executor_test.cpp
- test/resources.list
> client: explicit stop LeaseExecutor in FileInstance::UnInitialize

- CHANGELOG-1.2.md
- CHANGELOG-1.3.md
> Doc: add v1.3.0 changelog

- curvefs/proto/BUILD
- curvefs/proto/common.proto
- curvefs/proto/mds.proto
- curvefs/proto/metaserver.proto
- curvefs/proto/space.proto
> curvefs : push proto change

- ut.sh
> add build curvefs ut test

- proto/schedule.proto
- proto/topology.proto
- src/mds/schedule/coordinator.cpp
- src/mds/schedule/coordinator.h
- src/mds/schedule/scheduleService/scheduleService.cpp
- src/mds/schedule/scheduleService/scheduleService.h
- src/mds/topology/topology.cpp
- src/mds/topology/topology.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/schedule_tool.cpp
- src/tools/schedule_tool.h
- src/tools/status_tool.cpp
- test/mds/mock/mock_topology.h
- test/mds/schedule/scheduleService/scheduleService_test.cpp
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology.cpp
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_topology_service.h
> tools: support set-scan-state command

- src/snapshotcloneserver/common/snapshotclone_meta_store.h
- src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.cpp
- src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.h
- src/snapshotcloneserver/snapshot/snapshot_core.cpp
- src/snapshotcloneserver/snapshot/snapshot_core.h
- src/snapshotcloneserver/snapshot/snapshot_task_manager.cpp
- test/integration/snapshotcloneserver/fake_snapshotclone_meta_store.cpp
- test/integration/snapshotcloneserver/fake_snapshotclone_meta_store.h
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
- test/snapshotcloneserver/mock_snapshot_server.h
- test/snapshotcloneserver/test_snapshot_core.cpp
- test/snapshotcloneserver/test_snapshot_service_manager.cpp
- test/snapshotcloneserver/test_snapshotclone_meta_store_etcd.cpp
> snapshotcloneserver: fixed cancel task lost

- conf/tools.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/tools.conf.j2
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.cpp
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
> curve_ops_tool: concurrent check copysets on server

- conf/tools.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/tools.conf.j2
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.cpp
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
This reverts commit c16e96336152cfe3c9710f8bdcd3419780da67f5.
How it Works:
> Revert "curve_ops_tool: concurrent check copysets on server"

- nbd/nbd-package/etc/curve/curvetab
- nbd/nbd-package/usr/bin/map_curve_disk.sh
> nbd: add auto mount options

- src/client/io_tracker.h
- src/client/splitor.cpp
- src/mds/nameserver2/clean_manager.cpp
- src/mds/nameserver2/clean_manager.h
- src/mds/nameserver2/clean_task.h
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/metric.cpp
- src/mds/nameserver2/metric.h
- src/mds/topology/topology_chunk_allocator.cpp
- test/mds/nameserver2/clean_discard_segment_task_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
- test/mds/nameserver2/mock/mock_clean_manager.h
> mds: fix clone volume missing throttle params and may start two or more tasks to clean same segment

- curvefs_python/BUILD_bak
- proto/BUILD
- proto/chunk.proto
- proto/heartbeat.proto
- src/chunkserver/chunkserver.cpp
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.h
- src/chunkserver/datastore/chunkserver_datastore.cpp
- src/chunkserver/datastore/chunkserver_datastore.h
- src/chunkserver/heartbeat.cpp
- src/chunkserver/heartbeat.h
- src/chunkserver/op_request.cpp
- src/chunkserver/scan_manager.cpp
- src/chunkserver/scan_manager.h
- src/mds/topology/topology.cpp
- test/chunkserver/datastore/datastore_mock_unittest.cpp
- test/chunkserver/mock_copyset_node.h
- test/chunkserver/scan_manager_test.cpp
> chunkserver: fix crc issues

- proto/BUILD
- proto/common.proto
- proto/heartbeat.proto
- proto/topology.proto
- src/mds/heartbeat/heartbeat_manager.cpp
- src/mds/heartbeat/topo_updater.cpp
- src/mds/topology/topology.cpp
- src/mds/topology/topology_item.cpp
- src/mds/topology/topology_item.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/status_tool.cpp
- src/tools/status_tool.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- test/tools/copyset_check_core_test.cpp
- test/tools/curve_tool_factory_test.cpp
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_mds_client.h
- test/tools/mock/mock_topology_service.h
> tools: support scan-status command and imporve status command

- src/mds/heartbeat/chunkserver_healthy_checker.cpp
- test/mds/heartbeat/chunkserver_healthy_checker_test.cpp
Problem Summary: unstable pendding empty chunkserver status to retired
What's Changed: unstable pendding empty chunkserver status to retired
How it Works: unstable pendding empty chunkserver status to retired
> unstable pendding empty chunkserver status to retired

- thirdparties/glog/glog.patch
cherry-pick from master: https://github.com/opencurve/curve/pull/424
How it Works:
> glog: fix chunkserver exit with core

- src/chunkserver/op_request.cpp
- src/chunkserver/scan_manager.cpp
- src/chunkserver/scan_manager.h
- test/chunkserver/scan_manager_test.cpp
> chunkserver: fix crc issue

- CHANGELOG-1.3.md
> doc: update changelog

- CHANGELOG-1.3.md
> docs: update release1.3 changelog

- src/mds/schedule/operatorStep.cpp
- src/mds/schedule/operatorStep.h
- src/mds/schedule/scanScheduler.cpp
- test/mds/schedule/operatorStep_test.cpp
- test/mds/schedule/scanScheduler_test.cpp
> mds: fix wrong judgment for scaning finished

- conf/tools.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/tools.conf.j2
- src/chunkserver/op_request.cpp
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.cpp
- src/tools/curve_tool_define.h
- src/tools/curve_tool_factory.cpp
- src/tools/curve_tool_main.cpp
- src/tools/status_tool.cpp
> curve_ops_tool: fix concurrent check copysets on server

- curve-ansible/roles/install_package/templates/nebd-daemon.j2
- nbd/nbd-package/etc/curve/curvetab
- nbd/nbd-package/usr/bin/map_curve_disk.sh
- nbd/src/ImageInstance.cpp
- nbd/src/ImageInstance.h
- nbd/src/NBDTool.cpp
- nbd/src/NBDTool.h
- nbd/src/define.h
- nbd/src/main.cpp
- nbd/src/util.cpp
- nbd/test/mock_image_instance.h
- nbd/test/nbd_config_test.cpp
- nebd/nebd-package/usr/bin/nebd-daemon
- nebd/src/part1/libnebd.cpp
- nebd/src/part1/libnebd.h
- nebd/src/part2/nebd_server.cpp
> nebd/curve-nbd: support multiple nebd

- conf/client.conf
- conf/cs_client.conf
- conf/py_client.conf
- conf/snap_client.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/client.conf.j2
- include/client/libcurve.h
- src/client/client_config.cpp
- src/client/config_info.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- test/client/client_mdsclient_metacache_unittest.cpp
> client: retry allocate segment until success

- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/server.ini
> ansible: support set chunkserver raft log protocol

- src/mds/heartbeat/chunkserver_healthy_checker.cpp
- src/mds/schedule/copySetScheduler.cpp
- src/mds/schedule/leaderScheduler.cpp
- src/mds/schedule/rapidLeaderScheduler.cpp
- src/mds/schedule/scheduler.cpp
- src/mds/schedule/scheduler.h
- src/mds/schedule/scheduler_helper.cpp
- src/mds/schedule/scheduler_helper.h
- src/tools/status_tool.cpp
- test/mds/heartbeat/chunkserver_healthy_checker_test.cpp
- test/mds/schedule/leaderScheduler_test.cpp
- test/mds/schedule/rapidLeaderSheduler_test.cpp
- test/mds/schedule/replicaScheduler_test.cpp
- test/mds/schedule/schedulerPOC/scheduler_poc.cpp
Problem Summary: Add pendding to v1.2
How it Works:
> Add pendding to v1.2

- nbd/src/util.cpp
> nbd: fix compile error

- curve-ansible/roles/install_package/tasks/include/install_etcd-daemon.yml
- curve-ansible/roles/install_package/templates/etcd-daemon.sh.j2
- curve-ansible/roles/install_package/templates/mds-daemon.sh.j2
- curve-ansible/rolling_update_curve.yml
> ansible: fix mds etcd daemon script

- robot/Resources/keywords/fault_inject.py
- robot/curve_failover_robot.txt
> robot:add online pendding test

- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/test_curve_stability_nbd.py
> robot:use block size 512 test

- replace-curve-repo.sh
> add glog mirror in replace-curve-repo.sh

- curve-ansible/roles/install_package/templates/snapshot-daemon.sh.j2
- curve-ansible/roles/restart_service/tasks/include/restart_nebd.yml
> ansible: fix snapshot-daemon.sh

- curvefs/conf/curvefs_client.conf
- curvefs/proto/space.proto
- curvefs/src/client/BUILD
- curvefs/src/client/base_client.cpp
- curvefs/src/client/base_client.h
- curvefs/src/client/config.h
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/error_code.h
- curvefs/src/client/extent.h
- curvefs/src/client/main.c
- curvefs/src/client/mds_client.cpp
- curvefs/src/client/mds_client.h
- curvefs/src/client/metaserver_client.cpp
- curvefs/src/client/metaserver_client.h
- curvefs/src/client/space_client.cpp
- curvefs/src/client/space_client.h
- curvefs/test/client/BUILD
- curvefs/test/client/base_client_test.cpp
- curvefs/test/client/mds_client_test.cpp
- curvefs/test/client/metaserver_client_test.cpp
- curvefs/test/client/mock_mds_base_client.h
- curvefs/test/client/mock_mds_service.h
- curvefs/test/client/mock_metaserver_base_client.h
- curvefs/test/client/mock_metaserver_service.h
- curvefs/test/client/mock_spacealloc_base_client.h
- curvefs/test/client/mock_spacealloc_service.h
- curvefs/test/client/space_client_test.cpp
- replace-curve-repo.sh
- test/resources.list
> curvefs/client: add metaserverclient and mdsclient

- monitor/grafana/dashboards/chunkserver.json
- monitor/grafana/dashboards/client.json
- monitor/grafana/dashboards/etcd.json
- monitor/grafana/dashboards/mds.json
- monitor/grafana/dashboards/report.json
- monitor/grafana/dashboards/snapshotcloneserver.json
- src/mds/heartbeat/topo_updater.cpp
- test/mds/heartbeat/heartbeat_manager_test.cpp
> cherry-pick from master

- src/chunkserver/copyset_node.cpp
- test/chunkserver/heartbeat_test_common.cpp
> fix/chunkserver: config change epoch update error

- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/DEBIAN/preinst
> nbd: backup and recover curvetab

- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
> ansible: backup curvetab if exist

- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/test_curve_stability_nbd.py
> robot: map device use --device

- CHANGELOG-1.2.md
> docs: change log for v1.2.1-rc0

- robot/init_env.sh
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/client/file_instance.cpp
- src/common/bitmap.cpp
- src/common/bitmap.h
- src/common/curve_define.h
- src/snapshotcloneserver/snapshot/snapshot_core.cpp
> client/chunkserver/snapshotcloneserver: add DLOG for debug CI bugs

- robot/Resources/keywords/test_curve_stability_nbd.py
> robot:Do not delete files when inconsistencies occur

- curve-ansible/roles/restart_service/tasks/include/restart_etcd.yml
- curve-ansible/roles/start_service/tasks/include/start_etcd.yml
> ansible: add time to etcd log file

- curvefs/proto/metaserver.proto
- curvefs/src/client/common/BUILD
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/common/extent.h
- curvefs/src/client/rpcclient/BUILD
- curvefs/src/client/rpcclient/base_client.cpp
- curvefs/src/client/rpcclient/base_client.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
> curvefs/client: modify mdsclient and metaserver client interface

- curve-ansible/roles/install_package/defaults/main.yml
> download jemalloc/daemon packages from nos

- docs/cn/deploy.md
- docs/en/deploy_en.md
> deployment: add prepartion step for libcurl-gnutls.so on CentOS

- curvefs/proto/BUILD
- curvefs/proto/common.proto
- curvefs/proto/metaserver.proto
- curvefs/src/client/base_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/mds/metaserver_client.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/dentry_storage.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/space/metaserver_client.cpp
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/dentry_storage_test.cpp
- curvefs/test/metaserver/dumpfile_test.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/metaserver_service_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/partition_test.cpp
Problem Summary: add metastore
What's Changed: split meta to partition
How it Works: metaserver proto add partiton
> add metastore

- curvefs/conf/metaserver.conf
- curvefs/proto/metaserver.proto
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash.h
- curvefs/src/metaserver/trash_manager.cpp
- curvefs/src/metaserver/trash_manager.h
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/metaserver_service_test.cpp
- curvefs/test/metaserver/mock_inode_storage.h
- curvefs/test/metaserver/trash_test.cpp
> metaserver : add trash impl

- docs/cn/deploy.md
- docs/en/deploy_en.md
- mk-tar.sh
> fixes some issue about mk-tar.sh and deployment

- ut.sh
> ut:test curve src ut

- CHANGELOG-1.0.md
> doc: add v1.0.3 & 1.0.4 changelog

- curvefs/src/metaserver/s3/metaserver_s3.cpp
- curvefs/src/metaserver/s3/metaserver_s3.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/metaserver_s3_adaptor_test.cpp
- curvefs/test/metaserver/metaserver_s3_test.cpp
> curvefs/src/metaserver: metaserver delete test

- curvefs/src/client/rpcclient/base_client.cpp
- curvefs/src/client/rpcclient/base_client.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/test/client/mock_mds_client.h
- curvefs/test/client/rpcclient/base_client_test.cpp
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/client/rpcclient/mock_mds_base_client.h
- curvefs/test/client/rpcclient/mock_mds_client.h
- curvefs/test/client/rpcclient/mock_topology_service.h
- curvefs/test/client/test_fuse_client.cpp
Problem Summary: curvefs/client:rpcclient add partition
How it Works:
> curvefs/client:rpcclient add partition

- curvefs/proto/common.proto
- curvefs/src/client/common/common.h
- curvefs/src/client/common/config.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/test/client/mock_mds_client.h
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/client/rpcclient/metacache_test.cpp
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/rpcclient/mock_metacache.h
- src/client/metacache_struct.h
> curvefs/client: add partition relative function for metacache

- curvefs/proto/mds.proto
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/mds/metaserverclient/metaserver_client.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/fs_manager_test2.cpp
- curvefs/test/mds/mds_service_test.cpp
- curvefs/test/mds/metaserver_client_test.cpp
- curvefs/test/mds/mock/mock_metaserver_client.h
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/topology/test_topology_manager.cpp
> curvefs/mds: create partition at createfs

- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/src/client/s3/disk_cache_base.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/src/common/BUILD
- curvefs/src/common/wrap_posix.cpp
- curvefs/src/common/wrap_posix.h
- curvefs/test/client/mock_disk_cache_base.h
- curvefs/test/client/mock_disk_cache_manager.h
- curvefs/test/client/mock_disk_cache_read.h
- curvefs/test/client/mock_disk_cache_write.h
- curvefs/test/client/mock_test_posix_wapper.h
- curvefs/test/client/test_disk_cache_base.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
- curvefs/test/client/test_fuse_client.cpp
- thirdparties/etcdclient/Makefile
> curvefs/client: add disk cache

- src/mds/copyset/copyset_manager.cpp
- src/mds/copyset/copyset_policy.cpp
- test/mds/copyset/test_copyset_manager.cpp
> mds : fix gen copyset max scatter-width bug

- curvefs/conf/curvefs_client.conf
- curvefs/src/client/client_operator.cpp
- curvefs/src/client/common/config.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/test/client/test_fuse_client.cpp
- src/client/mds_client.cpp
> curvefs client : fix test bugs

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/s3compact.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_manager.h
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/mock_s3_adapter.h
- curvefs/test/metaserver/mock_s3compactwq_impl.h
- curvefs/test/metaserver/s3compactwq_test.cpp
Problem Summary: add s3compact feature
What's Changed: curvefs/metaserver
How it Works: add s3compact workqueue to continuously merge s3chunks
> curvefs/metaserver: add S3Compact feature

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/tools/curvefs_topology_tool.cpp
- curvefs/src/tools/curvefs_topology_tool.h
- curvefs/src/tools/main.cpp
- curvefs/test/tools/curvefs_topology_tool_test.cpp
> curvefs/tools: fix duplicate bug

- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/rpcclient/base_client.h
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/test/client/rpcclient/metacache_test.cpp
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/rpcclient/mock_metacache.h
- src/client/metacache_struct.h
> curvefs/rpcclient: fix bugs from mdtest

- curvefs/proto/metaserver.proto
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/partition_test.cpp
> curvefs/metaserver: fix update nlink, check partition fsid and inode id

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/main.cpp
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
- thirdparties/glog/glog.patch
> curvefs/metaserver: add some braft-related flags to config file and backport some fixes from master

- curvefs/proto/common.proto
- curvefs/src/mds/fs_info_wrapper.h
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/main.cpp
- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/src/metaserver/main.cpp
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mds_service_test.cpp
> curvefs/mds: change createfs interface to an idempotent one

- curvefs/src/metaserver/partition.cpp
> curvefs/metaserver: fix core dump caused by message missing fields

- curvefs/src/mds/topology/topology_storge_etcd.cpp
> curvefs/mds: fix encode error

- curvefs/conf/curvefs_client.conf
- curvefs/conf/metaserver.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/error_code.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/main.c
- curvefs/test/client/test_fuse_client.cpp
> curvefs client : add releaseDir,fsync,background sync thread & fix pjdtest problem

- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/test/client/test_disk_cache_manager_impl.cpp
> curvefs/client: use disk cache

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/test/client/test_fuse_client.cpp
> curvefs client : fix write size

- curvefs/conf/curvefs_client.conf
> add disk cache option

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/test/client/test_fuse_client.cpp
> curvefs client : fix core dump when FuseOpDestroy

- conf/chunkserver.conf.example
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
- curve-ansible/server.ini
- deploy/local/chunkserver/conf/chunkserver.conf.0
- deploy/local/chunkserver/conf/chunkserver.conf.1
- deploy/local/chunkserver/conf/chunkserver.conf.2
- deploy/local/chunkserver/conf/chunkserver.conf.docker1
- deploy/local/chunkserver/conf/chunkserver.conf.docker2
- deploy/local/chunkserver/conf/chunkserver.conf.docker3
- deploy/local/chunkserver/conf/chunkserver.conf.docker4
- deploy/local/chunkserver/conf/chunkserver_docker.conf.0
- deploy/local/chunkserver/conf/chunkserver_docker.conf.1
- deploy/local/chunkserver/conf/chunkserver_docker.conf.2
- src/chunkserver/chunkserver.cpp
- src/chunkserver/clone_copyer.cpp
- src/chunkserver/clone_copyer.h
- test/chunkserver/clone/clone_copyer_test.cpp
> add curve file expired process

- curvefs/Makefile
- curvefs/src/metaserver/metaserver.cpp
Problem Summary: fix metaserver conf template
How it Works:
> fix metaserver conf template

- curvefs/src/client/s3/client_s3_cache_manager.cpp
"lruByte_ -= (*iter)->GetLen()" maybe infinity.
> curvefs/client: fix core dump in FsCacheManager Set

- curvefs/Makefile
- curvefs/devops/filter_plugins/filter.py
- curvefs/devops/vars/main.yml
- curvefs/src/client/main.c
- curvefs/src/mds/mds_service.cpp
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/register.cpp
- curvefs/src/tools/curvefs_topology_tool.cpp
- curvefs/src/tools/curvefs_topology_tool.h
- curvefs/test/tools/curvefs_topology_tool_test.cpp
- curvefs/test/tools/topo_example.json
> curvefs/tools: delete register metaserver in tools

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
>  curvefs/client: fix datacache flush get inode failed cause core dump

- curvefs/proto/metaserver.proto
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
>  curvefs/client: fix after 4k randwrite, randread caused coredump

- curvefs/proto/heartbeat.proto
- curvefs/proto/metaserver.proto
- curvefs/proto/topology.proto
- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/heartbeat/heartbeat_manager.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_storge_etcd.cpp
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/meta_operator.cpp
- curvefs/src/metaserver/copyset/meta_operator.h
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/src/metaserver/heartbeat.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver_service.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/mds/heartbeat/heartbeat_manager_test.cpp
- curvefs/test/mds/topology/test_topology.cpp
- curvefs/test/mds/topology/test_topology_helper.cpp
- curvefs/test/metaserver/heartbeat_test.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
> add metaserver metric and disk/mem use, delete unused code

- curvefs/devops/vars/client.yml
> curvefs/client: temporary preload jemalloc

- curvefs/conf/client.conf
- curvefs/src/client/common/common.h
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/mock_disk_cache_manager.h
- curvefs/test/client/mock_disk_cache_read.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
> curvefs/client: add prefethch read

- curvefs/src/metaserver/metastore.cpp
- curvefs/test/metaserver/metastore_test.cpp
> curvefs metaserver : keep create partition idempotence

- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/src/tools/topology/curvefs_build_topology_tool.cpp
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/metaserver/heartbeat_test.cpp
> curvefs: change choose metaserver policy when create copyset

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/metric/BUILD
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- src/common/dummyserver.h
> curvefs/client: add metric for client

- curvefs/conf/mds.conf
- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/mds.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_config.h
- curvefs/src/mds/topology/topology_metric.cpp
- curvefs/src/mds/topology/topology_metric.h
- curvefs/src/mds/topology/topology_storge_etcd.cpp
- curvefs/test/mds/topology/test_topology_metric.cpp
> add mds metric

- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_base.cpp
> curvefs/client: fix bug that multiple mounts at the same time

- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> robot:add fuse bps check'

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/mock_client_s3.h
- curvefs/test/client/mock_s3_adapter.h
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Adapting to Asynchronous upload to s3
> curvefs/client: Adapting to Asynchronous upload to s3

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
> curvefs/client: fix nocache scene read s3 object error

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_base.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/common/wrap_posix.cpp
- curvefs/src/common/wrap_posix.h
- curvefs/test/client/mock_test_posix_wapper.h
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
> curvefs:client: edit open parameter

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- src/common/s3_adapter.cpp
> curvefs/client: fix unit test bug

- curvefs/src/client/client_operator.cpp
- curvefs/src/client/client_operator.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/dentry_storage.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/metaserver/dentry_storage_test.cpp
> client: fixed unlink inode when rename with overwrite

- src/common/s3_adapter.cpp
> curvefs/client: fix coredump

- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_client.cpp
> curvefs client : add some fail handle logic for fuse client

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/main.cpp
> curvefs/client: fix client inconsistency of data

- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/test_disk_cache_write.cpp
> curvefs/client: aync upload write disk file

- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/error_code.cpp
- curvefs/src/client/error_code.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
> change log level of get inode

- README.md
- README_cn.md
> add notes for curvebs fio engine

- curvefs/conf/client.conf
- curvefs/conf/metaserver.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_client.cpp
> curvefs: use reasonable value for configurations

- curve-ansible/roles/install_package/tasks/include/install_nebd.yml
> ansible: fix install nebd lib path

- curvefs/conf/client.conf
> client: support generate random disk cache directory

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_cache_manager.h
- curvefs/test/client/mock_inode_cache_manager.h
> curvefs client : fix flush inode bug

- curvefs/conf/client.conf
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/src/client/s3/disk_cache_write.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
> curvefs/client: fix two coredump problems

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- src/common/s3_adapter.cpp
> curvefs/client: fix client write cause inconsistency of data

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
Issue Number: close #673 
How it Works:
> curvefs/client: fix client read cause inconsistency of data

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
Issue Number: close #679 
How it Works:
> curvefs client : fix performance problem of copying inode in lock

- curve-ansible/clean_nbd.yml
- curve-ansible/client.ini
- curve-ansible/roles/clean/tasks/include/clean_nbd.yml
- curve-ansible/roles/install_package/defaults/main.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
- mk-tar.sh
- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/DEBIAN/prerm
- nbd/nbd-package/etc/systemd/system/map_curve_disk.service
- nbd/nbd-package/usr/bin/map_curve_disk.sh
> curve-nbd: change auto mount service to systemd

- robot/Resources/config/config.py
- robot/Resources/config/profile
- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/Resources/keywords/mythread.py
- robot/curve_fs_robot.txt
> robot:add P1 level failover test cases

- .gitignore
- curvefs/Makefile
- curvefs/README.md
- curvefs/conf/client.conf
- curvefs/conf/etcd.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/conf/tools.conf
- curvefs/devops/Dockerfile
- curvefs/docker/Dockerfile
- curvefs/docker/entrypoint.sh
- curvefs/util/image.sh
- curvefs/util/install.sh
- curvefs/util/servicectl.sh
> makefile: support make image

- robot/Resources/config/config.py
- robot/Resources/config/profile
- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/Resources/keywords/mythread.py
- robot/curve_fs_robot.txt
- ut.sh
> robot:add rename test

- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
Issue Number: close #673 
How it Works:
> curvefs/client: refactor the code read data from s3info

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/fs_cache_manager_test.cpp
Issue Number: close #684 
How it Works:
> curvefs/client: fix read lru bug

- thirdparties/brpc/root_BUILD.patch
> arm64: change build option o0 to o2

- curvefs/devops/util/tmpl.sh
- curvefs/util/image.sh
> ansible: fixed template regex ignore trailing space

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
Issue Number: close #673 
How it Works:
> curvefs/client:fix datacache flush bug cause inconsistency of data

- CHANGELOG-1.0.md
- CHANGELOG-1.2.md
> curve: update changelog

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
Issue Number: close #716 #715  
How it Works:
> curvefs/client:fix datacache is release and write at the same time cause core dump

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/mock_client_s3_adaptor.h
Issue Number: close #718  
How it Works:
> curvefs/client:fix read old inode cause inconsistency of data

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_write.cpp
> curvefs/client: async upload after reboot

- curvefs/src/client/s3/client_s3_cache_manager.cpp
Issue Number: close #720  
How it Works:
> curvefs/client:fix curve-fuse coredump

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
Issue Number: close #679  
How it Works:
> make io smooth

- curve-ansible/common_tasks/install_with_yum_apt.yml
- curve-ansible/host_vars/localhost.yml
- curve-ansible/roles/format_chunkserver/tasks/include/prepare_chunkserver_without_disk_format.yml
- curve-ansible/roles/install_package/templates/chunkserver_deploy.sh.j2
> ansible: fix deploy bugs

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
Issue Number: close #735  
How it Works:
> curvefs/client: refactor the code datacache's dataBuf

- curvefs/conf/client.conf
- curvefs/src/client/rpcclient/mds_client.cpp
Issue Number: close #732 
Problem Summary: https://github.com/opencurve/curve/issues/732#issuecomment-979659922
What's Changed: lower down some configurations
How it Works:
> curvefs/rpcclient: fix io hang when mds host power down

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/mock_client_s3.h
- curvefs/test/client/test_disk_cache_manager_impl.cpp
Fixs: https://github.com/opencurve/curve/issues/709
Issue Number: close #709  
How it Works:
> fix umount bug

- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> robot:add umount fs test

- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> Fs：robot:get 'ps fuse' first pid

- curvefs/src/metaserver/dumpfile.cpp
- curvefs/src/metaserver/storage.h
- thirdparties/glog/glog.patch
> glog: now we can logging normally in child process even if async enabled.

- curvefs/docker/entrypoint.sh
Issue Number: close #747  https://github.com/opencurve/curveadm/issues/20  
How it Works:
> docker: update entrypoint.

- src/tools/copyset_check_core.cpp
> curve-ops-tools: fix chunkserver ip:port error

- curvefs/docker/Dockerfile
- curvefs/src/tools/curvefs_tool_define.h
fix name error and conf 
How it Works:
> curvefs/tools: fix name & conf

- curvefs/README.md
Added doc for compiling CurveFS ​​on CentOS-8
Issue Number: close #807 
How it Works:
> curvefs/doc: Update README.md

- curvefs/docker/Dockerfile
> fix name & conf

- curvefs/src/metaserver/dumpfile.cpp
- curvefs/src/metaserver/storage.h
- curvefs/test/metaserver/storage_test.cpp
> curvefs/metaserver: fixed metastore reload fail and report INVALID_CHECKSUM

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/src/common/utils.cpp
- curvefs/src/common/utils.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_write.cpp
add the function that control the size of disk cache.
Issue Number: close #757  
How it Works:
> curvefs/client: adapter disk cache size

- README.md
- README_cn.md
> add curvefs introduction in README

- curvefs/Makefile
- curvefs/src/metaserver/s3/metaserver_s3.cpp
- curvefs/test/metaserver/metaserver_s3_adaptor_test.cpp
- curvefs/test/metaserver/metaserver_s3_test.cpp
add test to fix branch cover not enough
How it Works:
> metaserver/s3: add branch cover 

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
fix ChunkCacheManagerPtr and FileCacheManagerPtr no release
Issue Number: close #742  
How it Works:
> curvefs/client: fix ChunkCacheManagerPtr and FileCacheManagerPtr no release

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
fix ChunkCacheManagerPtr and FileCacheManagerPtr no release
Issue Number: close #742  
How it Works:
> curvefs/client:fix ChunkCacheManagerPtr and FileCacheManagerPtr no release

- .gitignore
- curvefs/docker/Dockerfile
- curvefs/docker/base/Dockerfile
- curvefs/docker/base/Makefile
- curvefs/util/image.sh
Issue Number: close #825 
Problem Summary: updated base image automatic when make curvefs image
How it Works:
> docker: updated base image automatic when make curvefs image (#825).

- curvefs/src/mds/schedule/scheduler.cpp
- curvefs/src/mds/schedule/topoAdapter.cpp
- curvefs/src/mds/schedule/topoAdapter.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/schedule/mock_topoAdapter.h
- curvefs/test/mds/schedule/recoverScheduler_test.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
The randomly choose metaserver maybe unbalanced.
Use the policy based on disk capacity.
Issue Number: close #841  
How it Works:
> curvefs/mds: Change the policy of create copyset

- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> Fs: robot use curveadm test

- curvefs/src/client/curve_fuse_op.cpp
Issue Number: close #866
How it Works:
> curve-fuse: enable splice

- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
1. If the flushing file is removed, then clean up all caches
2. The logic of UpdateWriteCacheMap here has a reverse call, and it leads to
chunkCacheManager_->rwLockWrite_ becomes public and needs to be optimized
3. Truncate becomes smaller, and the corresponding cache needs to be released
Issue Number: close #737  
How it Works:
>  curvefs/client: deal with some remaining issues

- curvefs/proto/topology.proto
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/src/mds/topology/topology_service.cpp
- curvefs/src/mds/topology/topology_service.h
- curvefs/src/tools/README.md
- curvefs/src/tools/curvefs_tool.cpp
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/curvefs_tool_factory.cpp
- curvefs/src/tools/curvefs_tool_factory.h
- curvefs/src/tools/list/curvefs_topology_list.cpp
- curvefs/src/tools/list/curvefs_topology_list.h
- curvefs/src/tools/status/curvefs_mds_status.cpp
- curvefs/src/tools/status/curvefs_metaserver_status.cpp
- curvefs/src/tools/status/curvefs_status_base_tool.cpp
- curvefs/src/tools/status/curvefs_status_base_tool.h
- curvefs/test/tools/curvefs_tool_factory_test.cpp
Issue Number: close #879  
show the topology of cluster 
1. add list-toplogy rpc in mds/topology
2. add list-topology in curvefs_tool
3. add some function about topology in mds/topology
How it Works:
2. add list-topology in curvefs_tool, list-topology send list-topologyrequest to mds
> Curvefs-tools: show topology

- curvefs/conf/tools.conf
- curvefs/devops/tools.yml
- curvefs/src/tools/BUILD
- curvefs/src/tools/README.md
- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/create/curvefs_create_fs.h
- curvefs/src/tools/create/curvefs_create_topology_tool.cpp
- curvefs/src/tools/create/curvefs_create_topology_tool.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/curvefs_tool_factory.cpp
- curvefs/src/tools/curvefs_tool_factory.h
- curvefs/test/tools/BUILD
- curvefs/test/tools/curvefs_build_topology_tool_test.cpp
Issue Number: close #891  
1. use curvefs_tool to create fs
2, rename build-topology to create-topology
curvefs_tool add create-fs command
How it Works:
curvefs_tool send create-fs rpc to mds/topology
> curvefs/tool: add create-fs

- curvefs/conf/client.conf
- curvefs/conf/etcd.conf
- curvefs/conf/tools.conf
- curvefs/docker/Dockerfile
- curvefs/docker/entrypoint.sh
> curveadm: change project layout and rename some variables.

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/src/client/s3/disk_cache_base.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/mock_client_s3_adaptor.h
- src/common/s3_adapter.h
Issue Number: close #910   
How it Works:
> curvefs/client: add s3Adaptor and diskCache metrics

- curvefs/conf/client.conf
Issue Number: close #909  
How it Works:
> curvefs/client:modify client conf

- curvefs/src/client/s3/client_s3_adaptor.cpp
Issue Number: close #912  
How it Works:
> curvefs/client:fix diskCache.diskCacheType=0,fuse_client failed to activate

- curvefs/src/mds/metaserverclient/metaserver_client.cpp
> curvefs/mds: add log when rpc error to metaserver

- curvefs/conf/mds.conf
- curvefs/src/metaserver/copyset/config.h
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/copyset/copyset_service.cpp
- curvefs/src/metaserver/copyset/trash.cpp
- curvefs/src/metaserver/copyset/trash.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
- curvefs/test/metaserver/copyset/copyset_node_manager_test.cpp
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
- curvefs/test/metaserver/copyset/copyset_reloader_test.cpp
- curvefs/test/metaserver/copyset/copyset_service_test.cpp
- curvefs/test/metaserver/copyset/raft_cli_servic2_test.cpp
- curvefs/test/metaserver/copyset/trash_test.cpp
Issue Number: close #917 #921
Problem Summary: see #917 #921 
How it Works:
> curvefs/metaserver: fix copyset trash not start and uncorrect trash dir

- curvefs/src/metaserver/inode_storage.cpp
Caution: after this commit, capaction will have error, do not open it in
config, and we will fix it later.
Issue Number: close #929  
How it Works:
> remove merge two inode in storage updateInode

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/tools/version/curvefs_version_tool.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/mock_s3_adapter.h
- curvefs/test/metaserver/copyset/raft_log_codec_test.cpp
- nbd/src/BUILD
- nbd/src/main.cpp
- nebd/src/common/nebd_version.cpp
- src/common/BUILD
- src/common/lru_cache.h
- src/common/macros.h
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
- src/common/stringstatus.cpp
Issue Number: close #849
How it Works:
> s3adapter: get/put object zero-copy

- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/test/client/client_s3_adaptor_test.cpp
1.Fix the issue that the release version fails to compile
2.delete unnecessary unit test cases
Issue Number: close #928  
How it Works:
> curvefs/client:Fix the issue that the release version fails to compile

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
Issue Number: close #965  
How it Works:
> curvefs/client: clear unnecessary logs

- monitor/target_json.py
> monitor: fix refresh when curve_ops_tool return fail

- curvefs/conf/tools.conf
1. set s3.blocksize=4194304
2. set s3.chunksize 67108863
How it Works:
> curvefs_tool: fix s3 conf

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
> curvefs/client: optimize trim strategy

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.h
> curvefs/client: add throttle for disk cache

- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/list/curvefs_topology_list.cpp
- curvefs/src/tools/list/curvefs_topology_list.h
- curvefs/src/tools/list/curvefs_topology_tree_json.cpp
- curvefs/src/tools/list/curvefs_topology_tree_json.h
add output json file which can be used for create-topology
Issue Number: close #975  
How it Works:
> curvefs/tool: list-topology output json file

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/test/metaserver/metastore_test.cpp
- src/common/s3_adapter.cpp
Issue Number: #995
Problem Summary: cherry-pick from master, master pr https://github.com/opencurve/curve/pull/997
How it Works:
> fix insert inode fail when load deleting partition

- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> robot:add metaserver copyset migrate test

- monitor/grafana/dashboards/chunkserver.json
- monitor/grafana/dashboards/client.json
> monitor: update chunkserver.json and client.json

- README.md
> README: add Double Week Meetings

- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/test/metaserver/metaserver_test.cpp
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
Issue Number: closes #1025 
Problem Summary: see #1025 
How it Works:
> metaserver: fix deadlock after restart

- src/mds/copyset/copyset_policy.cpp
Signed-off-by: locallocal <locallocal@163.com>
clean code.
How it Works:
> mds/copyset: change copyseyNum to copysetNum.

- docs/en/chunkserver_design_en.md
fix 中文版 url in chunkserver_design_en.md
> doc: fix chunkserver doc url

- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/storage.h
- curvefs/src/metaserver/trash.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/mock_inode_storage.h
Issue Number: close #960  
How it Works:
> curvefs metaserver : update inode avoid copying

- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
> curvefs improve the inode and dentry cache lock

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/metaserver_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
> backport #1062 to release2.0

- CHANGELOG-2.0.md
> doc: add changelog-2.0.md

- curvefs/src/client/fuse_client.cpp
- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/create/curvefs_create_fs.h
- curvefs/src/tools/curvefs_tool.h
- curvefs/test/client/test_fuse_client.cpp
1. curvefs_tool has add create-fs
2. fix some error output
How it Works:
> curvefs/client: rm create fs in init

- docs/cn/monitor.md
- docs/en/monitor_en.md
- monitor/README.md
- monitor/grafana/provisioning/dashboards/chunkserver.json
- monitor/grafana/provisioning/dashboards/client.json
- monitor/grafana/provisioning/dashboards/etcd.json
- monitor/grafana/provisioning/dashboards/mds.json
- monitor/grafana/provisioning/dashboards/report.json
- monitor/grafana/provisioning/dashboards/snapshotcloneserver.json
fix grafana dashboard config path and an error doc link.
How it Works:
> fix grafana dashboard config path and an error doc link

- README.md
- README_cn.md
> add doc for deploying cluster by curveadm

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
curvefs/client: fix client release read data cache core dump
Issue Number: close #1050  
How it Works:
> curvefs/client: fix client release read data cache core dump

- nbd/src/NBDServer.cpp
fix misspell in nbd server log.
What's Changed: null
How it Works: null
Side effects(Breaking backward compatibility? Performance regression?): null
> nbd: fix misspell log.

- curvefs/test/metaserver/metaserver_test.cpp
> test/metaserver: fix confilct port in MetaserverTest

- nbd/src/NBDServer.cpp
- nebd/src/part1/nebd_client.cpp
What's Changed: Clean all typos with 's/faield/failed/g'.
How it Works:
> fixes typos

- curvefs/src/tools/copyset/curvefs_copyset_base_tool.cpp
> fix copyset status error

- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/rpcclient/mock_metaserver_service.h
> curvefs client : fix bug of getleader always fails causes stack overflow

- curvefs/src/client/rpcclient/task_excutor.cpp
Issue Number: close #1137  
How it Works:
> curvefs client : fix bug of rpc overtime time not backoff

- curvefs/conf/tools.conf
set
s3.blocksize=4194304
s3.chunksize=67108864
How it Works:
> curvefs_tool:fix_s3_conf

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/mock_client_s3.h
- curvefs/test/metaserver/mock_metaserver_s3.h
Issue Number: close #1054  
How it Works:
> curvefs/client: add download s3 data crc

- conf/chunkserver.conf
- conf/chunkserver.conf.example
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
- deploy/local/chunkserver/conf/chunkserver.conf.0
- deploy/local/chunkserver/conf/chunkserver.conf.1
- deploy/local/chunkserver/conf/chunkserver.conf.2
- src/chunkserver/chunkserver.cpp
- src/chunkserver/config_info.h
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.h
- src/chunkserver/datastore/chunkserver_datastore.cpp
- src/chunkserver/datastore/chunkserver_datastore.h
- src/chunkserver/op_request.cpp
- src/fs/ext4_filesystem_impl.cpp
- src/fs/ext4_filesystem_impl.h
- src/fs/local_filesystem.h
- src/fs/wrap_posix.cpp
- src/fs/wrap_posix.h
- test/chunkserver/copyset_node_test.cpp
- test/chunkserver/copyset_service_test.cpp
- test/chunkserver/datastore/datastore_mock_unittest.cpp
- test/fs/mock_local_filesystem.h
Issue Number: close #1033  
How it Works:
> chunkserver: modify write op return without synchronization

- curvefs/src/client/client_operator.cpp
- curvefs/src/client/client_operator.h
- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_client.cpp
and unlink source directory inode when source and destination
directory are different for rename().
Issue Number: close #1153 
How it Works:
> curvefs/client: fixed without link destination directory inode

- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/usr/bin/map_curve_disk.sh
- test/kvstorageclient/etcdclient_test.cpp
> ansible: fix auto map script

- curvefs/src/mds/fs_manager.cpp
- curvefs/src/tools/curvefs_tool.cpp
- curvefs/src/tools/curvefs_tool.h
- src/common/s3_adapter.cpp
1. fix no error output in curvefs_tool
2. fix some error in s3Adapter
3. remove s3info error show in mds
Issue Number: close #1162 
How it Works:
before:
> curvefs/tool&mds: create-fs error

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/copyset/copyset_node_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/mock_s3compactwq_impl.h
- curvefs/test/metaserver/s3compactwq_test.cpp
backport #1157 to branch release2.0
> curvefs/metaserver: let s3 compact task store a shared copyset node

- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_metric.cpp
- curvefs/src/mds/topology/topology_metric.h
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/src/metaserver/storage/memory_storage.cpp
- curvefs/test/mds/topology/test_topology_metric.cpp
curvefs: add metric for mds topology to update metaserver metric
> curvefs: add metric for mds topology to update metaserver metric

- curvefs/src/tools/usage/curvefs_space_base_tool.cpp
usage data from kb to b
Modify the conversion function
How it Works:
> curvefs_tool/fix_metadatausage_show_error

- curvefs/src/client/s3/client_s3_cache_manager.cpp
> curvefs clinet : fix core dump of DataCache::Flush

- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/heartbeat/topo_updater.cpp
Issue Number: #1181
Problem Summary: topology partition num metric is wrong
How it Works:
> curvefs: fix partition num in topology metric

- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
Issue Number: close #1188 
How it Works:
> curvefs client :fix core dump of DataCache::Flush & fix rpc timeout time not backoff

- CHANGELOG-2.1.md
> doc: add changelog-2.1.md

- docs/cn/curvefs_meta_balance_design.md
Issue Number: #1053
Problem Summary: add curvefs meta balance design doc
> doc: add curvefs meta balance design doc

- curvefs/src/client/s3/client_s3_cache_manager.cpp
> curvefs/client: change log level

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/main.c
- curvefs/test/client/test_fuse_client.cpp
> curvefs: support listxattr

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/main.c
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
Issue Number: close #1213 #1209 #1201 #1197  
How it Works:
> curvefs/client: fix bug issue

- curvefs/src/client/curve_fuse_op.cpp
Issue Number: #1210 
Problem Summary: fix curvefs release read return Bad File Description
init fuse_bufvec struct before it use
> fix curvefs release read return Bad File Description

- test/chunkserver/clone/clone_core_test.cpp
- test/chunkserver/clone/op_request_test.cpp
Issue Number: close #1222
Problem Summary: see #1222 
How it Works:
> unittest: fix test/chunkserver/clone/clone_test always coredump

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- src/common/leaky_bucket.cpp
- src/common/leaky_bucket.h
- src/common/lru_cache.h
- test/common/lru_cache_test.cpp
Issue Number: close #1215  
Issue Number: close #1175   
Issue Number: close #1190
> curvefs/client: fix lru bug

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
Issue Number: close #1249
How it Works:
> metaserver: fix empty configuration after load snapshot

- robot/Resources/keywords/fs_fault_inject.py
> robot: add hexdump consistency test file

- curvefs/src/client/fuse_client.cpp
- curvefs/test/mds/metaserver_client_test.cpp
> curvefs: fix mds unit test

- curvefs/conf/mds.conf
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds.cpp
Issue Number: close #1271 
How it Works:
> curvefs-mds: fix an uninitialized that spawn infinite threads

- curvefs/conf/client.conf
- curvefs/src/client/BUILD
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/data_cache_test.cpp
- curvefs/test/client/file_cache_manager_test.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
- src/common/lru_cache.h
- test/common/lru_cache_test.cpp
- test/mds/mock/mock_etcdclient.h
Issue Number: close #996  
Issue Number: close #1235   
Issue Number: close #1251
> curvefs/client: perf optimize

- curvefs/src/client/BUILD
> edit build

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/metric/client_metric.h
> curvefs: add client op metric

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/main.c
implement statfs for df (need todo)
How it Works:
> curvefs/client: statfs

- .gitignore
- curvefs/monitor/README.md
- curvefs/monitor/curve-monitor.sh
- curvefs/monitor/docker-compose.yml
- curvefs/monitor/grafana-report.py
- curvefs/monitor/grafana/dashboards/client.json
- curvefs/monitor/grafana/dashboards/etcd.json
- curvefs/monitor/grafana/dashboards/mds.json
- curvefs/monitor/grafana/dashboards/metaserver.json
- curvefs/monitor/grafana/grafana.ini
- curvefs/monitor/grafana/provisioning/dashboards/all.yml
- curvefs/monitor/grafana/provisioning/datasources/all.yml
- curvefs/monitor/prometheus/prometheus.yml
- curvefs/monitor/target.ini
- curvefs/monitor/target_json.py
- curvefs/monitor/update_dashboard.sh
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/tools/status/curvefs_mds_status.cpp
- curvefs/src/tools/status/curvefs_status_base_tool.cpp
1. add curvefs monitor
2. curvefs_tool status-mds show dummy port for dummy mds
3. add port in mountpoints, change mountpoint from {hostname}:{mountpoint} to {hostname}:{port}:{mountpath}
How it Works:
> curvefs/monitor: promethus

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/main.c
> Revert "curvefs/client: statfs"

- .github/pull_request_template.md
> modify pr tempalate

- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/s3compactwq_test.cpp
Issue Number: close #1263 
How it Works:
> curvefs/metaserver:fix s3compaction stackoverflow

- curvefs/conf/client.conf
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_read.cpp
Issue Number: #1275  
How it Works:
> curvefs/client: edit config and log

- curvefs/conf/client.conf
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_read.cpp
Issue Number: #1275  
How it Works:
> curvefs/client:：edit config and log

- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
> curvefs/client: add op metrics

- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/test/client/test_inodeWrapper.cpp
backport bugfix to branch release2.2
> curve-fuse: fix missing update extent cache

- curvefs/Makefile
- curvefs/README.md
- curvefs/util/build.sh
Quick Start
---
```
$ make build dep=1 
```
OR
```
$ make dep
$ make build
```
> makefile: now support build dependencies by alone.

- .gitignore
- docker/debian10/Dockerfile
- docker/debian11/Dockerfile
- docker/debian9/Dockerfile
> curvebs/dockerfile: fixed remove unuseful file.

- curvefs/conf/client.conf
- curvefs/proto/metaserver.proto
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/BUILD
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/meta_operator.cpp
- curvefs/src/metaserver/copyset/meta_operator.h
- curvefs/src/metaserver/copyset/metric.cpp
- curvefs/src/metaserver/copyset/metric.h
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
> curvefs: add applied index in client read rpc requests

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
> curvefs/client: edit logs

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
> curvefs/client: edit log

- curvefs/src/client/curve_fuse_op.cpp
> curvefs: fix getxattr affects write performance bug

- conf/client.conf
- curvefs/docker/debian10/Dockerfile
- curvefs/docker/debian11/Dockerfile
- curvefs/docker/debian9/Dockerfile
- curvefs/src/client/fuse_client.cpp
- curvefs/test/volume/bitmap_allocator_test.cpp
- curvefs/util/image.sh
- src/client/client_common.h
- src/client/client_config.cpp
- src/client/client_config.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
> curvefs: adapt to curveadm to support curvebs as data backend

- curvefs/src/client/fuse_client.cpp
> curvefs/client: modify getxattr log level

- curvefs/proto/metaserver.proto
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
backport #1359 to branch release2.2
> curvefs: fix a compatible issue which caused by modify FsFileType

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/curve_fuse_op.cpp
Issue Number: #1278
How it Works:
> curvefs: add switch for fuse splice

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
> curvefs/client: fix update xattr affect write performance

- curvefs/src/client/s3/client_s3_cache_manager.cpp
Issue Number: #1373  
How it Works:
> curvefs/client: fix bug of io hang

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
Issue Number: #1331  
How it Works:
> curvefs/client: fix bug cachedisk never trim

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/monitor/grafana/provisioning/dashboards/etcd.json
- curvefs/monitor/grafana/provisioning/dashboards/mds.json
- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
1. move dashbord to provisioning/
2. rm datasource uid in json
How it Works:
> curevfs/monitor: Increase data item unit and remove datasource uid

- curvefs/src/mds/mds.cpp
- src/leader_election/leader_election.cpp
- src/leader_election/leader_election.h
- src/mds/server/mds.cpp
- src/snapshotcloneserver/snapshotclone_server.cpp
- test/leaderelection/leader_election_test.cpp
> fix typo about CampaignLeader

- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
> curvefs/client: edit some logs level

- docs/cn/curve工具.md
add doc about curve tool
How it Works:
> Doc: restructure curve tool

- include/client/BUILD
- include/client/libcbd.h
- include/client/libcurve.h
- include/client/libcurve_define.h
- mk-deb.sh
- mk-tar.sh
- src/client/BUILD
- src/client/libcbd_ext4.cpp
- src/client/libcbd_libcurve.cpp
- test/client/libcbd_ext4_test.cpp
- test/client/libcbd_libcurve_test.cpp
Issue Number: #1396 
How it Works:
> add c-styled header file to curve-sdk

- curvefs/conf/client.conf
Issue Number: #1027  
How it Works:
> curvefs/client: Adjust the number of retries to the maximum to avoid an error when the number of retries is reached

- docs/cn/gmock.md
- docs/cn/gtest.md
> doc: add gtest/gmock documention

- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/metaserver/copyset/meta_operator.cpp
#1361 can't be reproduced locally, so add some verbose logs
> curvefs: add some verbose log to reproduce #1361

- curvefs/proto/common.proto
- curvefs/proto/mds.proto
- curvefs/src/mds/fs_info_wrapper.h
- curvefs/src/mds/mds_service.cpp
- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/test/mds/fs_info_wrapper_test.cpp
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/fs_manager_test2.cpp
- curvefs/test/mds/mds_service_test.cpp
Issue Number: #1356  
[4.1](https://github.com/opencurve/curve/blob/d5f8188fe51d60c38591827be7f71579ed27d3c6/docs/cn/curvefs-client%E7%BB%9F%E4%B8%80%E7%BC%93%E5%AD%98%E8%AE%BE%E8%AE%A1.md#41-%E5%88%9B%E5%BB%BA%E6%96%87%E4%BB%B6%E7%B3%BB%E7%BB%9F%E5%92%8C%E5%88%9D%E5%A7%8B%E5%8C%96%E6%B5%81%E7%A8%8B)
support hybrid fs creation
1. add hybrid fs type in proto
2. add create hybird fs in mds
3. add create hybird fs in curvefs/tool
How it Works:
> curvefs: support creating hybrid fs type

- curvefs/src/metaserver/dentry_manager.cpp
Issue Number: #1434 
Problem Summary: wrong log level
How it Works:
> curvefs/metaserver: fixed wrong log level (#1434).

- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
> curvefs/client: add metric for FileCacheManager and ChunkCacheManager

- curvefs/src/client/BUILD
- curvefs/src/client/fuse_common.h
- curvefs/src/client/main.cpp
Issue Number: #1422 
parse args and update argc/argv before pass to fuse_opt_parse 
How it Works:
> curvefs/client: add parser for --mdsAddr

- curvefs/src/mds/topology/topology_metric.cpp
- curvefs/src/mds/topology/topology_metric.h
> curvefs/topology: add fs inodeNum metric

- conf/chunkserver.conf
- conf/chunkserver.conf.example
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
- deploy/local/chunkserver/conf/chunkserver.conf.0
- deploy/local/chunkserver/conf/chunkserver.conf.1
- deploy/local/chunkserver/conf/chunkserver.conf.2
- src/chunkserver/chunkserver.cpp
Issue Number: #1255 
What's Changed: Change copyset.max_inflight_requests to chunkserver.max_inflight_requests
How it Works:
> Change copyset.max_inflight_requests to chunkserver.max_inflight_requests

- curvefs/test/client/test_fuse_client.cpp
The unit test case may failed some times in in concurrent case.
How it Works:
> curvefs/client: fix unit test which may failed in concurrent cases.

- robot/Resources/config/config.py
- robot/Resources/keywords/deploy.py
> robot:add s3 use curvebs test

- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/mds/topology/topology_manager.cpp
> curvefs/mds: fix miss set txid when create partition

- curvefs/src/client/rpcclient/task_excutor.h
> curvefs/client: fix node overflow

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
Issue Number: #1240  
How it Works:
> curvefs/client: fix read failure in multi-mount scenario

- docs/cn/curvefs_architecture.md
- docs/cn/curvefs缓存和生命周期管理.md
> Correct documentation errors

- curvefs/docker/debian9/base/Dockerfile
- curvefs/docker/debian9/compile/Dockerfile
- curvefs/src/tools/curvefs_tool_define.h
- docker/debian9/base/Dockerfile
- docker/debian9/compile/Dockerfile
- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
Issue Number: #1281,#1401, #1425 
How it Works:
1. Modify docs/cn/build_and_run.md
2. Fixed some missing dependencies in build-debian9
> curve: fix build error in mk-deb.sh and mk-tar.sh

- curvefs/monitor/docker-compose.yml
- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
Issue Number: #1420 
How it Works:
> curvefs/monitor: fix unit error

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
…
Issue Number: #742  
How it Works:
> curvefs/client: fix fileCacheManager and chunkCacheManager is not released problem

- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
> curvefs/client: fix the data iteration error when rpc retry.

- curvefs/src/client/fuse_s3_client.cpp
Issue Number: #1495  
How it Works:
> curvefs/client: Fix the problem of not opening diskcache datacache not flush

- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/src/metaserver/dentry_manager.h
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/dentry_storage.h
- curvefs/src/metaserver/partition.cpp
> curvefs/metaserver: skip find dentry when loading from snapshot

- curvefs/conf/metaserver.conf
- curvefs/src/client/BUILD
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/common/BUILD
- curvefs/src/common/dynamic_vlog.cpp
- curvefs/src/common/dynamic_vlog.h
- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/main.cpp
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore_fstream.cpp
- curvefs/src/metaserver/metastore_fstream.h
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/src/metaserver/storage/storage_fstream.h
- curvefs/test/metaserver/copyset/copyset_node_manager_test.cpp
Issue Number: #1469 #1467
How it Works:
> curvefs/metaserver: fix copysets can't reload concurrently and support dynamic vlog

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
> curvefs/mds: fix create partition error at parallel case

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- src/common/s3_adapter.h
> curvefs/client: use FakeS3Adapter to inject more metadata for metaserver

- curvefs/docker/debian10/entrypoint.sh
- curvefs/docker/debian11/entrypoint.sh
- curvefs/docker/debian9/entrypoint.sh
- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/src/metaserver/metastore_fstream.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/storage/rocksdb_storage.cpp
- curvefs/src/metaserver/storage/rocksdb_storage.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/s3compactwq_test.cpp
- docker/debian10/entrypoint.sh
- docker/debian11/entrypoint.sh
- docker/debian9/entrypoint.sh
- src/common/interruptible_sleeper.h
- src/common/wait_interval.cpp
- test/common/wait_interval_test.cpp
- thirdparties/glog/glog.patch
> pick to v2.2.0

- curvefs/proto/common.proto
- curvefs/src/mds/heartbeat/topo_updater.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_metric.cpp
- curvefs/src/mds/topology/topology_metric.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/metaserver/inode_manager_test.cpp
1. add file type in partition
2. add filetype2inodeNum in heartbeat
3. add isdeleted and old in inode_manager.updateInode
How it Works:
You can get the corresponding data through the metrics of mds
Note that since these data are reported by heartbeat, there is deviation
> curvefs/topology: add fs_filetype inodeNum metric

- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
> curvefs/client: fix applied index not set bug

- curvefs/monitor/target_json.py
- curvefs/proto/mds.proto
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/rpcclient/base_client.cpp
- curvefs/src/client/rpcclient/base_client.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/mds/fs_info_wrapper.cpp
- curvefs/src/mds/fs_info_wrapper.h
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds_service.cpp
- curvefs/src/mds/metric/fs_metric.cpp
- curvefs/src/mds/metric/fs_metric.h
- curvefs/src/mds/metric/metric.cpp
- curvefs/src/mds/metric/metric.h
- curvefs/src/tools/list/curvefs_fsinfo_list.cpp
- curvefs/src/tools/umount/curvefs_umount_fs_tool.cpp
- curvefs/test/client/rpcclient/base_client_test.cpp
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/client/rpcclient/mock_mds_base_client.h
- curvefs/test/client/rpcclient/mock_mds_client.h
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mds_service_test.cpp
- curvefs/test/mds/persist_kvstorage_test.cpp
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
Issue Number: #1458  
1. Use message moupoint instead of string
2. fix monitor unit error
How it Works:
> curvefs: fix check mountpoint exist error

- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/test/client/rpcclient/metacache_test.cpp
> curvefs/clinet: fix update partition in metacache error

- curvefs/src/mds/topology/topology.cpp
- curvefs/test/mds/topology/test_topology.cpp
Issue Number: #1535
How it Works:
> fix partition id become to 0 when mds restart #1535

- robot/perf_test.py
How it Works:
Modify the following parameters in the script as required：
size = '50G'   # test file size
testpath = '/home/curvefs'   # test path
filenum = 5 # Example Test the number of concurrent files in the path
> add perf test scripts

- curvefs/src/tools/umount/curvefs_umount_fs_tool.cpp
> curvefs:tool fix umount fs not set port

- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/test/client/rpcclient/test_task_executor.cpp
Issue Number: #1538
How it Works:
> curve-fuse: fix create inode doesn't reselect partition when previous partition is full

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/test/client/test_disk_cache_manager.cpp
- src/common/configuration.cpp
Issue Number: #1526  
How it Works:
> curvefs/client: add file limit can cache

- curvefs/conf/mds.conf
- curvefs/src/mds/BUILD
- curvefs/src/mds/main.cpp
> curvefs/mds: add log level

- curvefs/proto/topology.proto
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/lease/lease_excutor.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/src/mds/topology/topology_service.cpp
- curvefs/src/mds/topology/topology_service.h
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/curvefs_tool_factory.cpp
- curvefs/src/tools/delete/curvefs_delete_partition_tool.cpp
- curvefs/src/tools/delete/curvefs_delete_partition_tool.h
- curvefs/test/mds/mock/mock_metaserver_client.h
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/topology/test_topology.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/mds/topology/test_topology_metric.cpp
- curvefs/test/mds/topology/test_topology_service.cpp
1. implement the delete partition api in mds and tool.
2. persistent distributed partition number in cluster info to etcd.
3. modify the logic of partition cache in client/metacache if partition have been delete.
How it Works:
> curvefs: add delete partition in tool and mds

- curvefs/src/metaserver/copyset/meta_operator.cpp
- curvefs/src/metaserver/copyset/metric.cpp
- curvefs/src/metaserver/copyset/metric.h
Issue Number: #1497
What's Changed: curvefs: add metric metaserver on apply
How it Works:
> curvefs: add metric metaserver on apply

- curvefs/proto/metaserver.proto
- curvefs/src/client/client_operator.cpp
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/test/client/mock_dentry_cache_mamager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/partition_clean_test.cpp
- curvefs/test/metaserver/partition_test.cpp
Issue Number: #1490  
How it Works:
> bugfix: rmdir cause parent inode nlink = 0, that report an EIO

- curvefs/conf/metaserver.conf
- curvefs/src/client/rpcclient/metaserver_client.cpp
- src/common/configuration.cpp
> curvefs: modify the metaserver default configuration worker_count

- curvefs/src/metaserver/copyset/meta_operator.cpp
This reverts commit 17ad7f846e303cda24c1ab3beedb50a901d4547e.
> Revert "curvefs: add some verbose log to reproduce #1361"

- curvefs/proto/metaserver.proto
- curvefs/src/client/client_operator.cpp
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/test/client/mock_dentry_cache_mamager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/partition_clean_test.cpp
- curvefs/test/metaserver/partition_test.cpp
This reverts commit 2944a9960b038c60112414b2e329730d443def0c.
How it Works:
> Revert "bugfix: rmdir cause parent inode nlink = 0, that report an EIO"

- curvefs/test/client/lease/lease_executor_test.cpp
Issue Number: #1512  
How it Works:
> curvefs/test: fix the lease executor test fails probabilistically

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/copyset/meta_operator.h
- curvefs/src/metaserver/copyset/metric.cpp
- curvefs/src/metaserver/copyset/metric.h
- curvefs/src/metaserver/metaserver_service.cpp
> curvefs/metaserver: statistic arrival request for copyset per second

- curvefs/docker/debian9/compile/Dockerfile
- docker/debian9/compile/Dockerfile
> curve: add bazel-0.17.2

- curvefs/conf/client.conf
> curvefs/conf: defalut close cto

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
- src/common/lru_cache.h
- test/common/lru_cache_test.cpp
Issue Number: #1361  
How it Works:
> curvefs/client: fix Inconsistent data issues-1361

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
Issue Number: #1591  
How it Works:
> curvefs/client: fix statfs problem

- MAINTAINERS.md
Signed-off-by: lixiaocui <ilixiaocui@163.com>
How it Works:
> doc: add maintainer list

- CHANGELOG-2.2.md
> [skipci] docs: added v2.2 changelog.

- LICENSE
- curve-ansible/roles/generate_config/templates/grafana.ini.j2
- curve-ansible/roles/generate_config/templates/prometheus.yml.j2
- curvefs/monitor/curve-monitor.sh
- curvefs/monitor/docker-compose.yml
- curvefs/monitor/grafana-report.py
- curvefs/monitor/grafana/grafana.ini
- curvefs/monitor/grafana/provisioning/dashboards/all.yml
- curvefs/monitor/grafana/provisioning/datasources/all.yml
- curvefs/monitor/prometheus/prometheus.yml
- curvefs/monitor/target.ini
- curvefs/monitor/target_json.py
- curvefs/monitor/update_dashboard.sh
- monitor/curve-monitor.sh
- monitor/docker-compose.yml
- monitor/grafana-report.py
- monitor/grafana/grafana.ini
- monitor/grafana/provisioning/dashboards/all.yml
- monitor/grafana/provisioning/datasources/all.yml
- monitor/prometheus/prometheus.yml
- monitor/target.ini
- monitor/target_json.py
- monitor/update_dashboard.sh
> 【skipci】remove unnecessary license headers

- src/common/lru_cache.h
Issue Number: #1627  
How it Works:
> curvefs/client: exchange call map size

- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/mds/main.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/register.cpp
- curvefs/src/metaserver/storage/converter.cpp
- curvefs/test/client/mock_dentry_cache_mamager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/metaserver/dentry_storage_test.cpp
> curvefs: fix listDentry may exceed the limit

- curvefs/src/mds/metaserverclient/metaserver_client.cpp
Signed-off-by: baijiaruo <baijiaruo@126.com>
Issue Number: #1610  
How it Works:
> curvefs/mds: fix create filesystem timeout

- Community_Guidelines.md
> curve: add curve open source community guidelines doc

- docs/cn/curvefs_improve_ls.md
> 【skipci】curvefs/doc: add how to improve the performance of ls -* doc

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
- src/common/lru_cache.h
Issue Number: #1627  
How it Works:
> curvefs/client: fix problem of perf decline

- curvefs/src/client/s3/disk_cache_manager.cpp
Issue Number: #1628  
How it Works:
> curvefs/client: get fs ratio more timely

- curvefs/src/client/s3/client_s3_cache_manager.cpp
Signed-off-by: baijiaruo <baijiaruo@126.com>
Issue Number: #1659  
How it Works:
> curvefs/client: fix client core dump by AddReadDataCache

- CHANGELOG-2.3.md
> [skipci] docs: added v2.3 changelog

- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/test/client/rpcclient/metacache_test.cpp
Issue Number: #1665 
How it Works:
> curve-fuse: fix SEGV when creating partition concurrently

- replace-curve-repo.sh
> replace nbd github repo with gitee

- README.md
- README_cn.md
- docs/cn/build_and_run.md
- docs/cn/curvefs_improve_ls.md
- docs/en/build_and_run_en.md
> 【skipci】curve: modify the docs about build

- curvefs/monitor/docker-compose.yml
- curvefs/monitor/target_json.py
1. fix prom verison
2. fix target_json run fail in python3.5
How it Works:
> curvefs/monitor: fix prom version

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/mds/mds_service.cpp
change log level of some fuseop function
> curvefs/client: change log level of some fuseop function

- curvefs/src/mds/metaserverclient/metaserver_client.cpp
The previous pr doesn't work and fix it.
https://github.com/opencurve/curve/commit/4a87cbd184eaac9caa09137a106eae686c2a233c
How it Works:
> curvefs/mds: fix createfs timeout

- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
Signed-off-by: Wine93 <wine93.info@gmail.com>
How it Works:
> [skipci] docs: updated build step.

- curvefs/src/metaserver/inode_storage.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
> curvefs/metaserver: remove the unnecessary get process in inodeStore

- curvefs/proto/metaserver.proto
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_storage.cpp
Issue Number: #1653
What's Changed: Change related log level to WARNING in this case.
> metaserver: add STORAGE_CLOSED status code

- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
Issue Number: #1688
How it Works:
> curvebs: fix mismatch config item in chunkserver.conf.j2

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
Issue Number: #1672 
How it Works:
> filter offline metaserver when regist

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
> Revert "curvefs/client: fix data in read disk cache is more larger than the a…"

- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
Issue Number: #1708  
How it Works:
> curvefs/client: add metric for diskcache usedbytes

- docs/cn/snapshotcloneserver_interface.md
Signed-off-by: Wangpan <aspirer2004@gmail.com>
How it Works:
> [skipci] Update snapshotcloneserver_interface.md

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/monitor/grafana/provisioning/dashboards/etcd.json
- curvefs/monitor/grafana/provisioning/dashboards/mds.json
- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/mds/mds.cpp
- curvefs/src/metaserver/metaserver.cpp
> curvefs/monitor: add dashboard templates

- curvefs/conf/metaserver.conf
> curvefs: change raft_sync to false as default

- curvefs/conf/tools.conf
- curvefs/src/tools/curvefs_tool.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
Send rpc requests repeatedly.
Issue Number: #1678  
How it Works:
> curvefs/tool: Adjust the logic of how to retry

- curvefs/conf/metaserver.conf
- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/monitor/grafana/provisioning/dashboards/etcd.json
- curvefs/monitor/grafana/provisioning/dashboards/mds.json
- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/mds/mds.cpp
- curvefs/src/metaserver/metaserver.cpp
> curvefs: change raft_sync to false as default and add curvefs monitor dashboards

- curvefs/src/client/s3/disk_cache_manager.h
> curvefs/client: move unused variable

- CHANGELOG-2.3.md
> [skipci] docs: edit v2.3 changelog

- CHANGELOG-2.3.md
> 【skipci】curve: add metadata performance to changelog-v2.3

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/copyset.go
- tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/list/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/query/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/status.go
- tools-v2/pkg/config/config.go
- tools-v2/pkg/output/output.go
How it Works:
```
curve fs status copyset
+-------------+--------+-------------------------------------------------+
| copyset key | status |                     explain                     |
+-------------+--------+-------------------------------------------------+
| 4294967297  |  warn  | |op status: COPYSET_OP_STATUS_COPYSET_NOTEXIST| |
| 4294967298  |   ok   |                                                 |
| 4294967299  |   ok   |                                                 |
| 4294967300  |   ok   |                                                 |
| 4294967301  |   ok   |                                                 |
| 4294967302  |   ok   |                                                 |
| 4294967303  |   ok   | …
```
> Curve/tool: fs status copyset

- curvefs/proto/metaserver.proto
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
> Revert "curvefs: Merge updateInode and GetOrModifyS3ChunkInfo 2 rpcs in backg…"

- tools-v2/doc/README.md
> [skipci] curve/tool: add install in doc

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/metric/client_metric.h
> curvefs/client: add icache s3ChunkInfoSize metric

- test/client/fake/mds_workflow_test.cpp
> fix compile release failure

- tools-v2/doc/README.md
Add a configuration file download address
Signed-off-by: SiKu <Cyber-SiKu@outlook.com>
How it Works:
> [skipci] curve/tool-v2: Update README.md

- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/volume/default_volume_storage.cpp
- curvefs/src/client/volume/extent_cache.cpp
- curvefs/src/client/volume/extent_slice.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/storage/converter.cpp
- curvefs/src/metaserver/storage/converter.h
- curvefs/src/metaserver/storage/rocksdb_storage.h
- curvefs/src/volume/bitmap_allocator.cpp
- curvefs/src/volume/bitmap_allocator.h
- curvefs/src/volume/block_group_loader.cpp
- curvefs/src/volume/block_group_loader.h
- curvefs/src/volume/block_group_manager.cpp
- curvefs/src/volume/block_group_updater.cpp
- curvefs/src/volume/free_extents.cpp
- curvefs/src/volume/free_extents.h
- curvefs/test/client/volume/extent_cache_merge_test.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/storage/converter_test.cpp
- curvefs/test/volume/bitmap_allocator_test.cpp
- curvefs/test/volume/block_group_loader_test.cpp
- curvefs/test/volume/block_group_updater_test.cpp
- curvefs/test/volume/space_manager_test.cpp
- src/common/bitmap.cpp
- src/common/bitmap.h
Issue Number: #1457, #1461
How it Works:
> curve-fuse: fix coredump when reload volume space

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
Signed-off-by: baijiaruo <baijiaruo@126.com>
Issue Number: #1074  
How it Works:
> curvefs/client: Read process memory copy 2 times problem modification

- test/integration/client/mds_exception_test.cpp
> fix name error

- curvefs/src/metaserver/copyset/meta_operator.cpp
- curvefs/src/metaserver/copyset/metric.cpp
- curvefs/src/metaserver/copyset/metric.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore_fstream.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/s3compact.cpp
- curvefs/src/metaserver/s3compact.h
- curvefs/src/metaserver/s3compact_inode.cpp
- curvefs/src/metaserver/s3compact_inode.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_manager.h
- curvefs/src/metaserver/s3compact_worker.cpp
- curvefs/src/metaserver/s3compact_worker.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/s3compact/BUILD.bazel
- curvefs/test/metaserver/s3compact/main.cpp
- curvefs/test/metaserver/s3compact/mock_s3_adapter.h
- curvefs/test/metaserver/s3compact/mock_s3compact_inode.h
- curvefs/test/metaserver/s3compact/mock_s3infocache.h
- curvefs/test/metaserver/s3compact/s3compact_test.cpp
- curvefs/test/metaserver/s3compact/s3compact_worker_test.cpp
Issue Number: #1653 
How it Works:
> metaserver: optimize s3 compaction thread model

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/volume/block_device_aio.cpp
- curvefs/src/volume/block_device_aio.h
- curvefs/src/volume/block_device_client.cpp
- curvefs/src/volume/block_device_client.h
- curvefs/src/volume/block_group_loader.cpp
- curvefs/test/volume/block_device_aio_test.cpp
- curvefs/test/volume/block_device_client_test.cpp
> curve-fuse: use bs aio interfance

- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/metaserver/dentry_storage_test.cpp
> curvefs: fix list empty directory return not found

- curvefs/src/client/fuse_client.cpp
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/space/manager.cpp
Signed-off-by: Hanqing Wu <wuhanqing@corp.netease.com>
Issue Number: #1781 
How it Works:
> curve-fuse: stop lease before sending umount fs request (#1781)

- curvefs/conf/mds.conf
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/schedule/copysetSchedule.cpp
- curvefs/src/mds/schedule/scheduler.h
- curvefs/src/mds/schedule/topoAdapter.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_config.h
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/test/mds/BUILD
- curvefs/test/mds/metaserver_balance_poc.cpp
- curvefs/test/mds/mock/mock_metaserver_client.h
- curvefs/test/mds/mock/mock_topoAdapter.h
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/schedule/coordinator_test.cpp
- curvefs/test/mds/schedule/copysetScheduler_test.cpp
- curvefs/test/mds/schedule/leaderScheduler_test.cpp
- curvefs/test/mds/schedule/recoverScheduler_test.cpp
- curvefs/test/mds/schedule/scheduler_test.cpp
- curvefs/test/mds/schedule/topoAdapter_test.cpp
- curvefs/test/mds/topology/test_topology.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
Issue Number: #1650 #1453
How it Works:
> Optimize metadata balance

- curvefs/src/client/fuse_client.cpp
> curvefs/client: fix readdirplus return inode attr error in hardlink scene

- tools-v2/go.mod
- tools-v2/go.sum
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/copyset.go
- tools-v2/internal/utils/proto.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/check/copyset/gap.go
- tools-v2/pkg/cli/command/curvefs/query/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/etcd/etcd.go
- tools-v2/pkg/cli/command/curvefs/status/mds/mds.go
- tools-v2/pkg/cli/command/curvefs/status/metaserver/metaserver.go
- tools-v2/pkg/cli/command/curvefs/usage/inode/inode.go
- tools-v2/pkg/config/config.go
Issue Number: #1686  
How it Works:
> curve/tool-v2: check copyset log behind

- Makefile
- curvefs/util/build.sh
- util/build.sh
> build: support build deps by alone.

- conf/s3.conf
- thirdparties/aws/Makefile
support
1. ip
2. ip:port
3. hostname
4. hostname:port
How it Works:
> update aws-sdk-cpp: add ip and custom port support

- curvefs/src/client/inode_cache_manager.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
> curvefs/client: fix RefreshInode do not refresh when inode exist

- conf/s3.conf
- thirdparties/aws/Makefile
backport https://github.com/opencurve/curve/pull/1795
How it Works:
> Backport PR #1795 to release2.4

- test/chunkserver/braft_cli_service_test.cpp
- ut.sh
Signed-off-by: Hanqing Wu <wuhanqing@corp.netease.com>
How it Works:
> export aws sdk shared libraries

- src/common/lru_cache.h
> update: optimize LRUCache memory usage

- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
> curvefs: update metaserver grafana dashboard json

- src/common/configuration.cpp
- src/common/configuration.h
- test/common/configuration_test.cpp
> common: fix load config error with comment

- curvefs/src/client/curve_fuse_op.cpp
> curvefs/client: fix concurrent mknode return input/output error

- robot/Resources/config/config.py
- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fs_fault_inject.py
> robot:use curveadm 1.0 test

- tools-v2/pkg/cli/command/curvefs/warmup/add/add.go
It turned out that only judging whether moutpoint is the prefix of the
warm-up file is used to judge whether it is a subdirectory, which leads
to /a/bc/d being considered a subdirectory of /a/b/.
How it Works:
> curve/toosl-v2: fix warmup path

- curvefs/src/client/common/common.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_client.cpp
> curvefs: fix refresh inode in getInodeAttr everytime when read

- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
- ut.sh
> Support ut and failover parallel testing

- curvefs/src/mds/heartbeat/topo_updater.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/heartbeat/topo_update_test.cpp
> update topology partition next id

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/main.cpp
- curvefs/util/build.sh
- ut.sh
- util/build.sh
> curve: fix build erro in debian11

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- src/common/concurrent/task_thread_pool.h
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
> backport pr#1874 to release 2.4

- curvefs/proto/metaserver.proto
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
> curvefs: remove some code not used anymore

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
Signed-off-by: Hanqing Wu <wuhanqing@corp.netease.com>
How it Works:
> curve-fuse: fix miss use GetInodeAttr[Locked]

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
> curvefs: fix s3 adaptor metric type error

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/main.cpp
- curvefs/util/build.sh
- ut.sh
- util/build.sh
> Fix build error 2.4

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/proto/metaserver.proto
- curvefs/src/client/common/common.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
> cherry-pick pr1891 pr1896 pr1901 to branch2.4

- robot/Resources/config/config.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
- robot/curve_init.txt
> robot:add pjdtest

- curvefs/docker/debian10/base/Dockerfile
- curvefs/docker/debian10/compile/Dockerfile
- curvefs/docker/debian11/base/Dockerfile
- curvefs/docker/debian11/compile/Dockerfile
- curvefs/docker/debian9/base/Dockerfile
- curvefs/docker/debian9/compile/Dockerfile
> curve/docker: build & make image in docker

- curvefs/src/tools/copyset/curvefs_copyset_base_tool.cpp
- curvefs/src/tools/copyset/curvefs_copyset_base_tool.h
Issue Number: #1881  
How it Works:
> curvefs/tool: fix check copyset op status

- .bazelrc
- util/build.sh
> curve:fix compiling fail in higher gcc

- docs/cn/curve通过tar包手动部署sdk.md
> [skipci]add curve sdk手动部署文档

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/s3compact_manager.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
> curve: add region to aws s3 client option

- src/tools/status_tool.cpp
- src/tools/status_tool.h
Signed-off-by: Zhao ZeYu <2302370185@qq.com>
Issue Number: #1055  
Problem Summary: curve_ops_tool show space usage of every logicalpool
How it Works:
> CurveBS: curve_ops_tool show space usage of every logicalpool

- curvefs/src/tools/copyset/curvefs_copyset_base_tool.cpp
> curvefs/tool: fix check copyset opStatus

- .github/auto_assign-issues.yml
- .github/auto_assign.yml
> github: add auto assign of issue/pr

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/test/client/test_fuse_client.cpp
> curvefs/client:optimize warmup performance

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_inode_cache_manager.cpp
> curvefs: fix batch get inodeattr when readdir

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/test/client/test_fuse_client.cpp
backport:: https://github.com/opencurve/curve/pull/1930
> curvefs/client:ptimize warmup performance

- curvefs/conf/client.conf
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
> curvefs: fix refresh inode will overwrite data in cache when enabel cto

- curvefs/src/client/fuse_client.cpp
> curvefs/client: fix deadlock when readdir and update parent xattr when write

- README.md
- README_cn.md
> [skipci]docs: add CNCF code of conduct in readme to meet CNCF's request

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/client/xattr_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
> curvefs: implement setxattr interface.

- README.md
- README_cn.md
- docs/README.md
- docs/practical/curvebs_nfs.md
Signed-off-by: DemoLiang 
Issue Number:  none
通过curvebs 部署块存储测试集群
通过nfs-server部署nfs服务，提供可挂载的nfs服务
通过nfs挂载提供curvebs的共享存储使用
How it Works:
> [skipci] feat: 增加curvebs nfs 共享存储实践 

- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/namespace_tool.cpp
- src/tools/namespace_tool_core.cpp
- src/tools/namespace_tool_core.h
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_mds_client.h
- test/tools/namespace_tool_core_test.cpp
Signed-off-by: jolly-sy <757050468@qq.com>
How it Works:
> curvebs|tools:curve_ops_tool support extend volume

- util/install.sh
> install: added playground.

- tools-v2/internal/error/error.go
fix bs list zone typo
Signed-off-by: Tsonglew <tsonglew@gmail.com>
How it Works:
> fix bs list zone typo

- README.md
- README_cn.md
- docs/cn/测试环境配置信息.md
1. add curve test hardware config
2. fix some invalid link in readme
> [skipci]add test hardware config and fix readme invalid link

- docs/cn/curveBS 多nebd支持.md
> [skipci] add multi nebd support doc

- WORKSPACE
Issue Number: #2033 
Replace the old commit with the new version of the commit, and solve some build problem.
How it Works:
Side effects(Breaking backward compatibility? Performance regression?): None
> [compile] update the braft vesion

- docs/README.md
fix missing docs links
Signed-off-by: zyb521 <zyb_521@126.com>
How it Works:
> [skipci]fix missing docs links

- curvefs/src/client/main.cpp
The current implementation of this interface is problematic, resulting in inconsistent metadata
> curvefs/client:the implementation of readdirplus is problematic

- curvefs/src/client/kvclient/BUILD
- curvefs/src/client/kvclient/kvclient.h
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/kvclient/memcache_client.cpp
- curvefs/src/client/kvclient/memcache_client.h
- curvefs/test/client/BUILD
- curvefs/test/client/client_memcache_test.cpp
- ut.sh
> curvefs: add global cache client like memcached

- Community_Guidelines.md
- Community_Guidelines_cn.md
add commit message required
How it Works:
> [skipci]Doc/guide commit msg

- Makefile
- util/build.sh
Signed-off-by: lixiaocui1 <lixiaocui1@corp.netease.com>
How it Works:
> compile: fix Makefile and build.sh error

- util/image.sh
> fix image.sh

- docs/cn/curvefs_integration_testing.md
introduce curvefs integration testing design
> docs: curvefs integration testing

- .bazelrc
- conf/chunkserver.conf
- conf/chunkserver.conf.example
- src/chunkserver/chunkserver.cpp
- src/chunkserver/config_info.h
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/copyset_node_manager.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.h
- src/chunkserver/datastore/chunkserver_datastore.h
- test/chunkserver/chunkserver_test_util.cpp
- test/chunkserver/copyset_node_manager_test.cpp
- test/chunkserver/copyset_node_test.cpp
> sync by threadpool

- docs/cn/curve-raft-compatibility.md
> add curve raft suport peerid

- CHANGELOG-2.4.md
> [skipci] add v2.4 changelog

- curvefs/src/metaserver/partition_cleaner.cpp
- curvefs/src/metaserver/partition_cleaner.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash.h
query fsinfo once when delete inode
Close #2137
How it Works:
> [fix]curvefs/metaserver: query fsinfo once

- Makefile
- util/build.sh
- util/image.sh
- util/install.sh
> fix compile script

- curvefs/src/metaserver/partition_cleaner.cpp
- curvefs/src/metaserver/partition_cleaner.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash.h
> Rlease 2.3 fix curvefs/metaserver query fs info once

- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
Indicate the version of bazel
How it Works:
> [skipci][doc]build and run: bazel version

- curvefs/conf/client.conf
> curvefs/client: change the default value of s3

- curvefs/conf/client.conf
- curvefs/src/client/async_request_closure.cpp
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/test/client/mock_dentry_cache_mamager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- src/common/lru_cache.h
- test/common/lru_cache_test.cpp
> curvefs/client: change icache and dcache (lru cache) to lru cache with timeout

- docs/cn/curvefs_volume_space_deallocate.md
> [skipci]add curvefs volume space deallocate doc

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- src/common/s3_adapter.h
Signed-off-by: CodeFarmerPK <CodeFarmer.PK@Gmail.com>
Issue Number: #2020 
How it Works:
> curvefs/client: limited download retry times

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/proto.go
- tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/query/copyset/copyset.go
Issue Number: #1994  
How it Works:
> curve/toolsv2: fix deadlock

- ut.sh
- util/build.sh
> ci: fix curvbs buiild in ut.sh

- src/mds/topology/topology_metric.cpp
- src/mds/topology/topology_metric.h
- test/mds/topology/test_topology_metric.cpp
signed-off-by: hzwuhongsong [hzwuhongsong@corp.netease.com](mailto:hzwuhongsong@corp.netease.com)
> curvebs/mds: add curvebs logicpool io metric

- src/mds/topology/topology_metric.cpp
- src/mds/topology/topology_metric.h
- test/mds/topology/test_topology_metric.cpp
> curvebs/mds: add cluster io metrics

- docs/cn/Curve监控指标解析.md
> doc: add curve metric analyze

- curvefs/docker/debian9/entrypoint.sh
- docker/debian9/base/Dockerfile
> [fix] rm memcached in base image

- CHANGELOG-2.5.md
> add CHANGELOG-2.5.md

- util/install.sh
Set the correct source directory according to fs/bs
Issue Number: #2192  
How it Works:
> [fix]curvefs/monitor: install shell

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
use object instaed of pointer
Issue Number: #2208  
How it Works:
> [fix]curvefs/client: fix client core dump

- curvefs/src/metaserver/s3compact_inode.cpp
> curvefs: should release s3adapter if we donot need compact

- curvefs/proto/metaserver.proto
- curvefs/src/client/common/common.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/test/client/test_fuse_client.cpp
> curvefs: fix getxattr return wrong length

- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- test/mds/nameserver2/curvefs_test.cpp
Issue Number: #2221
How it Works:
> curvebs/mds: constrains stripe in one segment

- tools-v2/README.md
> [doc]toolsv2/bs: add finished work

- .clang-format
- developers_guide.md
- developers_guide_cn.md
- docs/cn/build_and_run.md
- docs/cn/clangd.md
- docs/en/build_and_run_en.md
Problem Summary: https://github.com/opencurve/curve/issues/2193
How it Works:
> [skipci] [docs] add clang-format and add some info to dev guides

- .clangd
- .gitignore
- docs/cn/clangd.md
Signed-off-by: Ziy1-Tan <ajb459684460@gmail.com>
Problem Summary: https://github.com/opencurve/curve/pull/2228
1. Add `.clangd` template and add into `.gitignore`
2. Replace `True[False]` with `Yes[No]`, referring to clangd docs.
How it Works:
> [skipci] [docs] add .clangd template and configuration guide

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Issue Number: #1918  
How it Works:
> curvefsd/client: fix bug that read redundant data(#1918)

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/test/client/test_fuse_s3_client.cpp
- src/common/s3_adapter.h
cherry-pick: https://github.com/opencurve/curve/pull/2237  https://github.com/opencurve/curve/pull/2216
> curvefs/client: warmup optimize

- curvefs/docker/debian9/Dockerfile
- docker/debian9/Dockerfile
- docker/debian9/base/Dockerfile
> [fix]docker: reduce the number of mirror layers

- proto/topology.proto
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
> curvebs/mds: add getChunkserverInCluster rpc api

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/create/cluster/logicalPool.go
- tools-v2/pkg/cli/command/curvebs/create/cluster/physicalPool.go
- tools-v2/pkg/cli/command/curvebs/create/cluster/server.go
- tools-v2/pkg/cli/command/curvebs/create/cluster/topo.go
- tools-v2/pkg/cli/command/curvebs/create/cluster/zone.go
- tools-v2/pkg/cli/command/curvebs/create/create.go
- tools-v2/pkg/cli/command/curvefs/create/topology/zone.go
- tools-v2/pkg/cli/curvecli.go
- tools-v2/pkg/config/bs.go
Issue Number: #2253
How it Works:
```
$ curve -c curve.yaml bs create topology --clustermap topology.json
+---------------+--------------+-----------+--------+
|     NAME      |     TYPE     | OPERATION | PARENT |
+---------------+--------------+-----------+--------+
| pool1         | physicalpool | add       |        |
+---------------+--------------+           +--------+
| zone1         | zone         |           | pool1  |
+---------------+              +           +        +
| zone2         |              |           |        |
+---------------+              +           +        +
| zone3         |              |           |        |
+---------------+--------------+           +--------+
| localhost_0_0 | server       |           | zone1  | …
```
> tools-v2: add cli `bs create topology`

- curvefs/src/client/warmup/warmup_manager.cpp
> [fix]curvefs/client/warmupManager:fix FetchS3ObjectsPoolMutex_

- robot/Resources/keywords/fs_fault_inject.py
- robot/curve_fs_robot.txt
> robot:Cluster check using new tool

- curvefs/docker/debian9/Dockerfile
- docker/debian9/Dockerfile
- docker/debian9/compile/Dockerfile
- tools-v2/Makefile
- tools-v2/README.md
- tools-v2/pkg/config/curve.yaml
- util/build.sh
- util/image.sh
- util/install.sh
> [feat]toolsv2: build to image

- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
> [fix]curvefs/client: test coredump

- README.md
- README_cn.md
- docs/en/snapshotcloneserver_en.md
Problem Summary: fix some typos.
How it Works:
> fix some typos

- src/chunkserver/chunkserver.cpp
- src/mds/topology/topology_metric.cpp
- src/mds/topology/topology_metric.h
- src/snapshotcloneserver/main.cpp
- test/mds/topology/test_topology_metric.cpp
> curvebs: add some topo metric

- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_fuse_client.cpp
> [fix]curvefs/client:coredump

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_memcache_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/data_cache_test.cpp
- curvefs/test/client/file_cache_manager_test.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
- curvefs/test/client/mock_client_s3_adaptor.h
- curvefs/test/client/mock_client_s3_cache_manager.h
- curvefs/test/client/test_fuse_s3_client.cpp
- tools-v2/internal/error/error.go
> [feat]curvefs/client:add memcache to warmup

- curvefs/src/client/common/config.h
- curvefs/test/client/test_disk_cache_manager_impl.cpp
> [fix]curvefs/test/client/coredump

- tools-v2/go.mod
Issue Number:  
Problem Summary: remove unused items in `go.mod`
How it Works:
> remove unused dependencies

- README.md
> [skipci]doc: add github star story and contrib.rocks

- curvefs/test/client/test_inodeWrapper.cpp
> test: client: Fix typo in test_inodeWrapper

- curvefs/src/client/kvclient/memcache_client.h
> curvefs/client: memcache client set nullptr after operation fail

- mk-tar.sh
> [fix]mk-star

- docs/practical/curvefs_rainbond.md
> [skipci]doc: add curvefs practice on rainbond

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
> [feat]curvefs/client:warmup metric

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/curve_fuse_op.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/main.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
1. Move `mountfs to mds` from FuseOpInit to FuseInit
2. fix coredump when mount fs fail
3. fix deadlock when init fail curve fuse exit
How it Works:
> [fix] mountpoint residual

- README.md
- developers_guide.md
- developers_guide_cn.md
- docs/cn/build_and_run.md
- docs/cn/gmock.md
- docs/en/build_and_run_en.md
For OSPP 2023 and Developer Activities
- We can make some extra steps and links;
- Contributors can build and contribute more smoothly.
How it Works:
> [skipci]docs: make build and contribute guide more friendly

- curvefs/docker/debian9/Dockerfile
- docker/debian9/Dockerfile
- docker/debian9/compile/Dockerfile
- docker/debian9/curve-tgt/Dockerfile
- docker/debian9/curve-tgt/Makefile
- nebd/src/part2/file_entity.cpp
1. add tgtd to image
2. add modprobe
How it Works:
> [fix]make tgtd to curvebs image

- src/chunkserver/copyset_node.cpp
> curvebs: fix segfault when enable O_DSYNC

- nebd/src/part2/file_entity.cpp
- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/delete/peer/peer.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/copyset.go
- tools-v2/pkg/cli/command/curvebs/query/query.go
- tools-v2/pkg/cli/command/curvebs/query/seginfo/seginfo.go
- tools-v2/pkg/cli/command/curvebs/update/peer/peer.go
- tools-v2/pkg/config/bs.go
How it Works:
```bash
curve bs query chunk --path /test1 --offset 1008600000 
+-------+-------------+---------+------------+------------------+
| CHUNK | LOGICALPOOL | COPYSET |   GROUP    |     LOCATION     |
+-------+-------------+---------+------------+------------------+
| 61    | 1           | 61      | 4294967357 | 10.182.2.46:8301 |
|       |             |         |            | 10.182.2.46:8302 |
|       |             |         |            | 10.182.2.46:8300 |
+-------+-------------+---------+------------+------------------+
```
> [feat]tools-v2: bs query chunk

- curvefs/src/mds/fs_manager.cpp
Moved to after checking whether fs exists to ensure compatibility
How it Works:
> [fix]mds/fsManager:check fs name

- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/update/file/file.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/config/bs.go
Issue Number: #2394 
How it Works:
```bash
curve bs update file --path /test2/test1 --size 10gib
Error: failed to expand file[/test2/test1] to 10 GiB, err: kShrinkBiggerFile
curve bs update file --path /test2/test1 --size 21gib
+---------+
| RESULT  |
+---------+
| success |
+---------+
```
> [feat]tools-v2: extend file

- tools-v2/pkg/cli/command/curvebs/create/file/create.go
- tools-v2/pkg/cli/command/curvebs/update/file/file.go
- tools-v2/pkg/config/bs.go
> [feat] fix tools-v2 size

- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
add only support x86 notice
How it Works:
> [skipci][fix]build and run readme

- docker/debian9/compile/Dockerfile
> [skipci][fix]upgrade clang version

- docker/debian9/compile/Dockerfile
- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
- util/image.sh
> [fix] build document and sh

- docs/cn/build_and_run.md
- docs/en/build_and_run_en.md
> [skipci][doc] recommand debian10

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/metric.go
- tools-v2/internal/utils/row.go
- tools-v2/internal/utils/string.go
- tools-v2/pkg/cli/command/curvebs/list/list.go
- tools-v2/pkg/cli/command/curvebs/list/logicalPool/logicalPool.go
- tools-v2/pkg/cli/command/curvebs/list/space/space.go
- tools-v2/pkg/cli/command/curvebs/query/pool/chunk.go
1. fix README.md
2. add bs list space 3 fix some error in bs list logicalpool
How it Works:
> [feat]tools-v2: add space

- tools-v2/docs/zh/develop.md
刚刚仔细下文档，发现其中仍存在目录错误的问题，目前已修改。
please take a look~
> [skipci] doc: tools-v2/develop.md(delete some useless menu)

- curvefs/src/client/inode_wrapper.cpp
Issue Number: #2428  
How it Works:
> curvefs/client: fix log level

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/proto.go
- tools-v2/pkg/cli/command/curvebs/list/dir/dir.go
- tools-v2/pkg/cli/command/curvebs/update/throttle/throttle.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/config/bs.go
- tools-v2/pkg/config/config.go
Issue Number: #2358  
How it Works:
> [feat] add bs update throttle

- curvefs/src/client/inode_wrapper.cpp
> [skipci]curvefs/client: fix log level

- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvebs/list/client/client.go
- tools-v2/pkg/cli/command/curvebs/list/logicalPool/logicalPool.go
- tools-v2/pkg/cli/command/curvebs/list/server/server.go
- tools-v2/pkg/cli/command/curvebs/list/zone/zone.go
- tools-v2/pkg/cli/command/curvefs/list/partition/partition.go
- tools-v2/pkg/cli/command/curvefs/query/fs/fs.go
- tools-v2/pkg/cli/command/curvefs/query/metaserver/metaserver.go
make response to request
How it Works:
> [fix]rpclist

- tools-v2/pkg/cli/command/curvebs/list/zone/zone.go
Problem Summary: list zone return empty errors
What's Changed: modify tools-v2/pkg/cli/command/curvebs/list/zone/zone.go
How it Works:
> [fix]tools-v2: list zone error collection

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/string.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/copyset/copyset.go
- tools-v2/pkg/config/bs.go
> [feat]tools-v2: add Getcopyset

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/metric.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/check/check.go
- tools-v2/pkg/cli/command/curvebs/check/operator/operator.go
- tools-v2/pkg/config/bs.go
> [feat] tools-v2: add bs check-operator

- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/curvecli.go
- tools-v2/pkg/config/config.go
> [fix] format flag

- conf/mds.conf
- util/install.sh
1. Package monitor into docker image
2. Narrow the time interval of mds topo metric udpate for curve website
How it Works:
> update curvebs mds topo metric update time and install.sh

- tools-v2/README.md
> [skipci][fix] fix readme

- conf/mds.conf
- proto/topology.proto
- src/mds/topology/topology_metric.cpp
- src/mds/topology/topology_metric.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology_metric.cpp
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- util/image.sh
- util/install.sh
> cherry-pick some commits

- README.md
- README_cn.md
> update cncf sandbox project notice

- developers_guide.md
- developers_guide_cn.md
- docs/cn/mds.md
- docs/cn/monitor.md
- docs/en/mds_en.md
- docs/en/monitor_en.md
Problem Summary: Modify document
1. modified:   developers_guide.md
2. modified:   developers_guide_cn.md
3. modified:   docs/cn/mds.md
4. modified:   docs/cn/monitor.md
5. modified:   docs/en/mds_en.md
6. modified:   docs/en/monitor_en.md
> [skipci] doc: update doc(mds, monitor, developers_guide)

- README.md
> [skipci]add CurveFS+MinIO S3 Gateway practical to README.md

- README_cn.md
> [skipci]add CurveFS+MinIO S3 Gateway practical to README_cn.md

- curvefs/src/client/s3/disk_cache_base.cpp
- mk-tar.sh
> [fix] build in debian11

- tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/status/copyset/get_copyset_status.go
when get copyset status fail, interface is nil
How it Works:
> [fix]tools-v2: fix some error about check copyset

- tools-v2/internal/utils/flag.go
- tools-v2/internal/utils/template/cobra.go
- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/curvecli.go
> [fix] config and cobrautil rely

- tools-v2/pkg/cli/command/curvebs/list/logicalPool/logicalPool.go
- tools-v2/pkg/cli/command/curvebs/list/space/space.go
- tools-v2/pkg/cli/command/curvebs/status/mds/mds.go
> [fix] list space error

- curvefs/conf/client.conf
- curvefs/src/client/filesystem/rpc_client.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
> curvefs/client: fixed some minor bugs.

- tools-v2/docs/zh/develop.md
> [fix][skipci] relace harbor with opencurve

- test/chunkserver/datastore/filepool_mock_unittest.cpp
> unittest: fix filepool test invalid memory access

- curvefs/src/metaserver/trash.cpp
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/trash_test.cpp
> curvefs/client: fix s3 object will not be removed

- conf/chunkserver.conf
- conf/chunkserver.conf.example
- deploy/local/chunkserver/conf/chunkserver.conf.0
- deploy/local/chunkserver/conf/chunkserver.conf.1
- deploy/local/chunkserver/conf/chunkserver.conf.2
> curvebs/chunkserver: enable odsync by default

- docker/Dockerfile
> fix make curvebs image

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/volume/default_volume_storage.cpp
- curvefs/src/client/volume/extent_cache.cpp
- curvefs/src/client/volume/fuse_volume_client.cpp
- curvefs/src/mds/space/service.cpp
- curvefs/src/mds/space/volume_space.cpp
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/metacli_manager.cpp
- curvefs/src/metaserver/metacli_manager.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metastore_fstream.cpp
- curvefs/src/metaserver/space/inode_volume_space_deallocate.cpp
- curvefs/src/metaserver/space/inode_volume_space_deallocate.h
- curvefs/src/metaserver/space/volume_deallocate_manager.cpp
- curvefs/src/metaserver/trash.cpp
- curvefs/src/volume/block_group_manager.cpp
- curvefs/src/volume/space_manager.cpp
- curvefs/test/mds/space/volume_space_test.cpp
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/copyset/copyset_node_block_group_test.cpp
- curvefs/test/metaserver/metacli_manager_test.cpp
- curvefs/test/metaserver/space/inode_volume_space_deallocate_test.cpp
- curvefs/test/metaserver/trash_test.cpp
1. fuse_volume_client just flush inode but do not flush data in Flush
How it Works:
> [curvefs] support volume backend: fix bugs

- curvefs/src/client/rpcclient/metacache.h
Problem Summary: CurveFS: delete apply index in client
How it Works:
> [feat] CurveFS: delete apply index in client

- tools-v2/pkg/cli/command/curvebs/status/cluster/cluster.go
> [fix]error about status cluster no offline chunkserver

- tools-v2/internal/utils/template/cobra.go
- tools-v2/pkg/cli/command/completion/completion.go
- tools-v2/pkg/cli/curvecli.go
> [feat] add completion

- replace-curve-repo.sh
> correct replace script

- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/delete/file/file.go
> [fix] Fixed delete file not returning status code error

- util/build.sh
bazel build full target is too slow.
get_target make all build serial now, if we build all, we should be parallel...
> speed up bazel build

- tools-v2/pkg/config/curve.yaml
> [doc] fix config err

- curvefs/src/client/curve_fuse_op.cpp
> fix curvefs client metric name

- MAINTAINERS.md
> [skipci] Update MAINTAINERS.md

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/test/client/test_disk_cache_manager.cpp
> Feat/curvefs/client/change disk cache conf on fly release2.6

- docker/debian11/curve-tgt/Dockerfile
- docker/debian11/curve-tgt/Makefile
> [skipci][fix] curve-sdk image

- curvefs/test/client/test_fuse_volume_client.cpp
> [fix]curvefs/client: ut fail

- tools-v2/README.md
close: #2580
close: #2581
update documents about `bs delete volume` command, pr #2713
> update documents about `bs delete volume` command

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/test_fuse_s3_client.cpp
add feat support symlink by fuseOpReadLink
How it Works:
> [feat]curvefs/client:support warmup sym link

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/metric/BUILD
- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/metric/client_metric_test.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/metaserver/copyset/raft_cli_service2_test.cpp
- src/chunkserver/clone_copyer.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
1. add writeToS3
2. add readFromS3
3. add writeToDiskCache
4. add readFromDiskCache
5. add writeToKVCache
6. add readFromKVCache
How it Works:
> [feat]split s3/diskcache/kvcache io metric

- conf/client.conf
- src/client/chunk_closure.cpp
- src/client/client_config.cpp
- src/client/client_metric.h
- src/client/config_info.h
- src/client/request_closure.cpp
- src/client/request_closure.h
- src/client/request_context.h
- test/client/client_metric_test.cpp
> curvebs(client): add slow request metric

- robot/Resources/config/config.py
- robot/Resources/config/profile
- robot/Resources/keywords/base_operate.py
- robot/Resources/keywords/deploy.py
- robot/Resources/keywords/fault_inject.py
- robot/Resources/keywords/fs_fault_inject.py
- robot/Resources/keywords/mythread.py
- robot/Resources/keywords/test_snapshot_s3.py
- robot/curve_choas.txt
- robot/curve_failover_robot.txt
- robot/curve_fs_robot.txt
- robot/init_env.sh
- robot/perf_test.py
> robot: add snapshot test and use new tools and curveadm to test

- curvefs/conf/tools.conf
> [fix] disable sum in dir

- replace-curve-repo.sh
> [fix] replace spdlog mirror

- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mds_service_test.cpp
Issue Number: #2590 
How it Works:
> [feat]: curvefs: replace BucketExist with putobject

- curvefs/docker/openeuler/Dockerfile
- curvefs/docker/openeuler/entrypoint.sh
- docker/openeuler/Dockerfile
- docker/openeuler/base/Dockerfile
- docker/openeuler/base/Makefile
- docker/openeuler/compile/Dockerfile
- docker/openeuler/compile/Makefile
- docker/openeuler/curve-tgt/Dockerfile
- docker/openeuler/curve-tgt/Makefile
- docker/openeuler/entrypoint.sh
Issue Number: #2612  
How it Works:
> [feat] Adaptor Openeuler 22.03-lts-sp2

- .bazelrc
- .github/workflows/cppcheck.yml
- Makefile
- curvefs/src/client/filesystem/meta.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/mds/schedule/scheduler.cpp
- curvefs/src/metaserver/s3compact_inode.cpp
- curvefs/src/tools/create/curvefs_create_topology_tool.cpp
- curvefs/src/volume/free_extents.cpp
- nebd/src/common/configuration.cpp
- nebd/src/part2/metafile_manager.cpp
- src/chunkserver/copyset_node_manager.cpp
- src/client/client_config.cpp
- src/common/configuration.cpp
- src/mds/schedule/leaderScheduler.cpp
- src/mds/schedule/recoverScheduler.cpp
- src/mds/schedule/scheduler.cpp
- src/mds/schedule/scheduler_helper.cpp
- src/tools/curve_format_main.cpp
- src/tools/mds_client.cpp
- src/tools/status_tool.cpp
- tools/curvefsTool.cpp
- ut.sh
- util/build_in_image.sh
- util/cppcheck/cppcheck.suppressions
- util/ut_in_image.sh
> [ci] Cppcheck action, sanitizers and warning fix

- replace-curve-repo.sh
> [skipci][fix]replace fmt mirror

- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- src/common/s3_adapter.h
> [fix] metric latency error

- curvefs/src/mds/topology/topology.cpp
> fix curvefs mds get metaserver

- curvefs/src/client/s3/disk_cache_write.cpp
> fix diskcache lru bug

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
1. fix diskcache used error
2. add diskcache total
3. add trim metric
1. fix diskcache used error
2. add diskcache total
3. add trim metric
How it Works:
> [feat]curvefs/client diskcache monitor

- tools-v2/Makefile
> [fix]enable go modules

- docs/cn/clangd.md
> [skipci]fix the error word

- src/chunkserver/concurrent_apply/concurrent_apply.cpp
- src/chunkserver/concurrent_apply/concurrent_apply.h
add some functions which curvefs maybe use~
How it Works:
> [refactor] CurveBS: add some common functions

- curvefs/monitor/target_json.py
> [feat]curvefs/monitor: support plugin

- curvefs/src/metaserver/s3/metaserver_s3.cpp
- src/common/s3_adapter.cpp
> fix some unnecessary error logs

- docker/debian11/compile/Dockerfile
> build: install clang-format-14 in dev docker

- mk-tar.sh
> [skipci][feat]mk-tar.sh: only support python3

- curvefs/monitor/grafana/provisioning/dashboards/memcached.json
> [skipci][feat]curvefs/monitor: add memcached

- curvefs/monitor/grafana/provisioning/dashboards/cluster.json
- curvefs/src/mds/BUILD
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_storage.cpp
- curvefs/src/mds/metric/fs_metric.cpp
- curvefs/src/mds/metric/fs_metric.h
- curvefs/src/mds/metric/metric.cpp
- curvefs/src/mds/metric/metric.h
- curvefs/test/mds/mds_metric_test.cpp
> [feat]add cluster usage

- util/build_in_image.sh
- util/image.sh
- util/install.sh
> [fix] build error

- conf/mds.conf
- conf/snapshot_clone_server.conf
- docker/debian11/Dockerfile
- src/mds/server/mds.cpp
- src/mds/server/mds.h
- src/snapshotcloneserver/snapshotclone_server.cpp
- src/snapshotcloneserver/snapshotclone_server.h
- src/tools/metric_name.h
- thirdparties/etcdclient/etcdclient.go
> etcd support enable auth

- curvefs/src/metaserver/partition.cpp
- src/common/concurrent/rw_lock.h
> Fix metaserver deadlock caused by bthread coroutine switching

- curvefs/src/client/kvclient/memcache_client.h
memcached memory leak when occur an exception
How it Works:
> curvefs/client: fix memory leak of memcached

- curvefs/test/metaserver/copyset/raft_cli_service2_test.cpp
> curvefs/client: fix unittest failed

- .obm.cfg
- curvefs/sdk/README.md
- curvefs/sdk/java/native/BUILD
- curvefs/sdk/java/pom.xml
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/flink/CurveFileSystemFactory.java
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/flink/CurveFileSystemTableFactory.java
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/hadoop/CurveFSInputStream.java
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/hadoop/CurveFSTalker.java
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/hadoop/CurveFileSystem.java
- curvefs/sdk/java/src/main/java/io/opencurve/curve/fs/hadoop/Main.java
- curvefs/sdk/libcurvefs/libcurvefs.cpp
- docker/ubuntu22/compile/Dockerfile
- docker/ubuntu22/compile/Makefile
- docker/ubuntu22/compile/setup.sh
- util/playground.sh
Issue Number: 
How it Works:
- curvefs-hadoop sdk adds the maven shade plugin packaging plugin to support jna and be compatible with user identification in the scenario of hadoop
- optimize some code logic
> curvefs/sdk: add maven build plugin,optimize the logic of parsing input parameters in flink

- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
Fixed a bug where warm-up progress may not be added
How it Works:
> [fix]curvefs/client: warmup may no progress

- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvefs/update/fs/fs.go
> tools-v2: fix update fs bug

- curvefs/src/client/s3/disk_cache_manager.cpp
> [fix]curvefs/client: diskcache may deadlock

- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
Fixed a bug where warm-up progress may not be added
How it Works:
> [fix]curvefs/client: warmup process

- curvefs/src/client/kvclient/memcache_client.h
> curvefs/client: too many logs

- curvefs/docker/debian11/entrypoint.sh
- curvefs/docker/openeuler/entrypoint.sh
- docker/debian11/entrypoint.sh
- docker/openeuler/entrypoint.sh
> [fix] fix entrypoint bug for monitor role

- curvefs/src/client/s3/disk_cache_manager.cpp
> [fix] fix the error that modify diskTrimCheckIntervalSec on the fly

- README.md
- README_cn.md
> [skipci] change docs website

- src/chunkserver/chunkserver.cpp
- src/chunkserver/copyset_node.cpp
- src/chunkserver/datastore/chunkserver_chunkfile_v2.cpp
- src/chunkserver/datastore/file_pool.cpp
- src/chunkserver/datastore/file_pool.h
- src/chunkserver/heartbeat.cpp
- src/chunkserver/heartbeat.h
- src/chunkserver/op_request.cpp
- src/client/request_context.h
- src/client/request_sender.cpp
- src/client/splitor.cpp
- src/fs/ext4_filesystem_impl.cpp
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_stat.cpp
> fix two bugs of release1.5

- curvefs/test/client/test_fuse_volume_client.cpp
- curvefs/test/metaserver/trash_test.cpp
> curvefs/metaserver: fix unittest bugs

- bazel/gmock.BUILD
- src/client/BUILD
- src/client/source_reader.cpp
- src/client/source_reader.h
- test/client/source_reader_test.cpp
> curvebs(client): Fix segment fault when opening clonesource files concurrently

- curvefs/src/metaserver/trash.cpp
- curvefs/test/metaserver/copyset/raft_cli_service2_test.cpp
- curvefs/test/metaserver/trash_test.cpp
> fix trash loop and utest

- tools-v2/Makefile
- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvefs/list/list.go
- tools-v2/pkg/cli/command/curvefs/list/space/space.go
- tools-v2/pkg/config/fs.go
> Feat(space): support query usage of fs

- src/mds/server/mds.cpp
- src/mds/snapshotcloneclient/BUILD
- src/mds/snapshotcloneclient/snapshotclone_client.cpp
- src/mds/snapshotcloneclient/snapshotclone_client.h
- test/kvstorageclient/etcdclient_test.cpp
- test/mds/nameserver2/mock/mock_snapshotclone_client.h
- test/mds/snapshotcloneclient/test_snapshotclone_client.cpp
- test/tools/etcd_client_test.cpp
> curvebs(mds): Fix fail to get clone source reference

- src/chunkserver/copyset_node.h
- src/chunkserver/raftlog/curve_segment.cpp
> fix/chunkserver: memory slow leak
