opencurve/curve

- src/client/chunk_closure.cpp
- src/client/lease_executor.cpp
- src/client/libcurve_file.cpp
- src/client/libcurve_snapshot.cpp
- src/client/mds_client.cpp
- src/client/mds_client_base.cpp
- src/client/metacache.cpp
- src/client/service_helper.cpp
- src/client/splitor.cpp
Problem Summary: Change some client log level
> change client log level

- src/chunkserver/raftlog/curve_segment.cpp
- src/chunkserver/raftlog/curve_segment.h
Fix the bug that _direct_fd will not be close when segment destructed.
How it Works:
> fix bug that will not close _direct_fd

- src/chunkserver/copyset_node.cpp
flush all tasks before leader start to prevent read inconsistency
How it Works:
> flush all tasks before leader start

- test/integration/client/chunkserver_exception_test.cpp
- test/integration/client/config/topo_example_1.json
fix client integration test failed which caused by create copysets too slow
What's Changed:  change copyset num from 300 to 30
How it Works:
> unittest: fix client integration test failed

- proto/topology.proto
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- test/tools/copyset_check_core_test.cpp
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_mds_client.h
- test/tools/mock/mock_topology_service.h
…sets health
Change-Id: I8fdb353323595b583dd2a31f5b6b397b8539bade
How it Works:
> Check if copysets on chunkservers consistent with mds when check copyset health.

- .gitignore
- src/chunkserver/copyset_node.cpp
- test/chunkserver/copyset_node_test.cpp
> bug fix chunkserver will not offline when disk error sometimes

- conf/client.conf
- src/client/client_common.h
- src/client/client_config.h
- src/client/config_info.h
- src/client/io_tracker.cpp
- src/client/io_tracker.h
- src/client/libcurve_client.cpp
- src/client/libcurve_file.h
- src/client/request_scheduler.cpp
- src/client/source_reader.cpp
- src/client/source_reader.h
- src/client/splitor.cpp
- src/client/splitor.h
- test/client/fake/fakeMDS.h
- test/client/fake/mock_schedule.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_common_test.cpp
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
> client read not allocate segment

- src/chunkserver/datastore/file_pool.cpp
- test/chunkserver/datastore/BUILD
- test/chunkserver/datastore/filepool_unittest.cpp
In MDSExceptionTest 
two thread running FilePool::GetFile (getFileFromPool=false) get the same filename, and write concurrently, one of them failed in rename operation:
I 2020-12-23T15:03:40.595710+0800 2375935 file_pool.cpp:289] src path = ./moduleException1/chunkfilepool//268, dist path = ./moduleException1/copysets/4294967574/log/curve_log_inprogress_00000000000000000001
I 2020-12-23T15:03:40.595726+0800 2375978 copyset_node.cpp:434] Copyset: (1, 274, 4294967570), peer id: 127.0.0.1:22225:0 become leader, term is: 2
I 2020-12-23T15:03:40.595696+0800 2375911 file_pool.cpp:289] src path = ./moduleException1/chunkfilepool//268, dist path = ./moduleException1/copysets/4294967572/log/curve_log_inprogress_00000000000000000001
I 2020-12-23T15:03:40.609778+0800 2375935 …
> fix atomic bug of FilePool::GetFile()

- test/chunkserver/braft_cli_service2_test.cpp
- test/integration/cluster_common/cluster_basic_test.cpp
in cluster_basic_test
mds start error on InitEtcdClient(), and produced coredump
log:
{"level":"warn","ts":"2020-12-29T11:17:52.264+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-e074fa9d-964b-4feb-ad0f-23a198366627/127.0.0.1:2301","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
2020-12-29 11:17:52.264637 I | session of current mds(127.0.0.1:2310) occur error
E 2020-12-29T11:17:52.264657+0800 1779304 leader_election.cpp:79] 127.0.0.1:2310 leader observe for prefix:07leader occur error, errcode: 23
I 2020-12-29T11:17:52.264678+0800 1779304 leader_election.cpp:86] mds is existing due to the error of leader observation
I 2020-12-29T11:17:52.264693+0800 1779256 …
> fix config error in cluster_basic_test

- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/status_tool.cpp
- src/tools/status_tool.h
- test/tools/curve_cli_test.cpp
- test/tools/mock/mock_mds_client.h
- test/tools/status_tool_test.cpp
- test/tools/version_tool_test.cpp
> Calculate chunkserver left space of each physical pool

- nbd/src/NBDTool.cpp
- nbd/src/NBDTool.h
- nbd/src/define.h
- nbd/src/main.cpp
- nbd/src/util.cpp
- nbd/test/nbd_tool_test.cpp
- robot/Resources/keywords/test_curve_stability_nbd.py
> nbd: unmap wait process exit

- proto/topology.proto
- src/mds/topology/topology.cpp
- src/mds/topology/topology.h
- src/mds/topology/topology_chunk_allocator.cpp
- src/mds/topology/topology_item.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- test/mds/mock/mock_topology.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology.cpp
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- tools/curvefsTool.cpp
add allocate status when create logicalpool and add SetLogicalPool to tools
How it Works:
> mds: add set logicalpool status

- proto/nameserver2.proto
- src/client/client_common.h
- src/client/lease_executor.cpp
- src/client/lease_executor.h
- src/client/mds_client.cpp
- src/client/metacache.h
- src/client/request_context.h
- src/client/request_sender.cpp
- src/client/service_helper.cpp
- src/client/service_helper.h
- src/client/splitor.cpp
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/helper/namespace_helper.h
- src/mds/nameserver2/namespace_service.cpp
- test/client/BUILD
- test/client/client_mdsclient_metacache_unittest.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/client/mds_client_test.cpp
- test/client/mock/BUILD
- test/client/mock/mock_namespace_service.h
- test/client/request_sender_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
Previously, when client reads and writes data within the length of the source file, rpc will carry the source file information.
Now, only when client reads and writes data within the range that source file' segment is allocated, and file status is CloneMetaInstalled, rpc will carry the source file information.
How it Works:
> client: send request source info only when clone source file segment is allocated and file status is CloneMetaInstalled

- nebd/etc/nebd/nebd-server.conf
- nebd/src/part2/define.h
- nebd/src/part2/file_service.cpp
- nebd/src/part2/file_service.h
- nebd/src/part2/nebd_server.cpp
- nebd/src/part2/util.cpp
- nebd/src/part2/util.h
- nebd/test/part2/file_service_unittest.cpp
> nebd-server: drop failed reqeusts' rpc

- src/client/lease_executor.h
What's Changed: use `bthread::Mutex` and `btherad::ConditionVariable` in `RefreshSessionTask`
How it Works:
> client: fix potential dead lock in close file

- curvefs_python/cbd_client.cpp
- curvefs_python/cbd_client.h
- curvefs_python/curve_type.h
- curvefs_python/curvefs.py
- curvefs_python/curvefs_tool.py
- curvefs_python/curvefs_wrap.cxx
- curvefs_python/parser.py
- include/client/libcurve.h
- proto/nameserver2.proto
- src/client/client_common.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/client/mds_client_base.cpp
- src/client/mds_client_base.h
- src/client/service_helper.cpp
- src/client/splitor.cpp
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/namespace_service.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/client/libcurve_interface_unittest.cpp
- test/integration/client/common/file_operation.cpp
- test/integration/client/common/file_operation.h
- test/integration/client/config/topo_example.json
- test/integration/client/mds_exception_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
What's Changed: add stripe feature
How it Works:
> client/mds: merge stripe feature and unit test

- curvefs_python/cbd_client.cpp
- curvefs_python/cbd_client.h
- curvefs_python/curvefs.py
- curvefs_python/curvefs_tool.py
- curvefs_python/curvefs_wrap.cxx
- curvefs_python/libcurvefs.h
- curvefs_python/parser.py
- include/client/libcurve.h
- proto/nameserver2.proto
- src/client/client_metric.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/client/mds_client_base.cpp
- src/client/mds_client_base.h
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/namespace_service.cpp
- src/mds/nameserver2/namespace_service.h
- test/mds/nameserver2/curvefs_test.cpp
- test/mds/nameserver2/namespace_service_test.cpp
> curvefs: recovey recyclebin file

- src/chunkserver/trash.cpp
- src/chunkserver/trash.h
> chunkserver: fix bug about trash bytes metric

- nbd/src/NBDController.cpp
- nbd/src/NBDController.h
- nbd/src/util.cpp
- nbd/src/util.h
- test/common/test_timeutility.cpp
> nbd: fix concurrent nbd map

- conf/s3.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/s3.conf.j2
- src/common/curve_define.h
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
> snapshotcloneserver: add s3 throttle

- tools/recyclebin-clean
Problem Summary: Need a script to clean the recycle bin regularly
What's Changed: Added script.
How it Works: You can add this script to your `crontab` list to clean the recycle bin regularly, ex:
```
30 01 * * * /path/to/recylebin-clean -f -p 80 > /path/to/log
```
The above cron task means：
* Execute the clean task at 1:30 am every day
* Force clean recycle bin when get space information error (a large-capacity recycle bin **may** cause this error)
* Otherwise, the recycle bin will be cleaned only when the recyclable percentage is greater than 80%
Side effects(Breaking backward compatibility? Performance regression?): none
> tools: added script to clean recycle bin for crontab

- curve-ansible/common_tasks/restart_service.yml
- curve-ansible/common_tasks/stop_service.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_retain_chunkfilepool.yml
- curve-ansible/roles/clean/tasks/include/clean_chunkserver_with_disk_format.yml
- curve-ansible/roles/format_chunkserver/tasks/include/prepare_chunkserver_with_disk_format.yml
- curve-ansible/roles/install_package/templates/chunkserver_deploy.sh.j2
- curve-ansible/roles/restart_service/tasks/include/restart_etcd.yml
- curve-ansible/roles/restart_service/tasks/include/restart_mds.yml
- curve-ansible/roles/restart_service/tasks/include/restart_nebd.yml
- curve-ansible/roles/restart_service/tasks/include/restart_snapshotclone.yml
- curve-ansible/roles/start_service/tasks/include/start_nebd.yml
- curve-ansible/roles/stop_service/tasks/include/stop_etcd.yml
- curve-ansible/roles/stop_service/tasks/include/stop_mds.yml
- curve-ansible/roles/stop_service/tasks/include/stop_nebd.yml
- curve-ansible/roles/stop_service/tasks/include/stop_snapshotcloneserver.yml
- curve-ansible/rolling_update_nebd.yml
- curve-ansible/server.ini
- curve-chunkserver/home/nbs/chunkserver_deploy.sh
> ansible: improve daemon restart

- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
Issue Number:  
Problem Summary: #323
wrap initializing code of raft node options into a function
* src/chunkserver/copyset_node.h
* src/chunkserver/copyset_node.cpp
How it Works:
a simple warpping
There seems to be lots of `// todo` which probably already be fixed, and that makes me confused so much.
Can I get in touch with someone privately (like adding wechat) to get some tips? I'm really interested in distributed system & storage and learned a lot of theory, but have a poor experience in large-scale engineering & c++ programming because I am still in my sophomore year......anyway thanks a lot for open source this project
> fix a todo: wrap initializing code of raft node options into a function

- conf/chunkserver.conf.example
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/chunkserver.conf.j2
- src/chunkserver/chunkserver.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/define.h
- src/chunkserver/datastore/file_pool.cpp
- src/chunkserver/datastore/file_pool.h
- src/common/string_util.h
- src/fs/wrap_posix.cpp
- src/tools/curve_format_main.cpp
- test/chunkserver/datastore/datastore_mock_unittest.cpp
- test/chunkserver/datastore/filepool_unittest.cpp
- test/chunkserver/datastore/mock_file_pool.h
- test/chunkserver/raftlog/test_curve_segment.cpp
- test/chunkserver/raftlog/test_curve_segment_log_storage.cpp
- test/integration/chunkserver/chunkserver_basic_test.cpp
- test/integration/chunkserver/chunkserver_concurrent_test.cpp
> chunkserver: added clean chunk feature

- conf/client.conf
- conf/cs_client.conf
- conf/py_client.conf
- conf/snap_client.conf
- curve-ansible/roles/generate_config/defaults/main.yml
- curve-ansible/roles/generate_config/templates/client.conf.j2
- include/client/libcurve.h
- src/client/client_config.cpp
- src/client/config_info.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- test/client/client_mdsclient_metacache_unittest.cpp
> client: retry allocate segment until success

- curve-chunkserver/home/nbs/chunkserver_deploy.sh
Fixes: issue #349
Issue Number: close #349 
What's Changed: add disk partition and virtual disk support when deploy chunkserver.
How it Works: use regular to handle lsblk prefix of disk partition and virtual disk.
> ansible: support disk partition and vd* as chunkserver

- curve-ansible/roles/install_package/defaults/main.yml
- curve-ansible/roles/install_package/tasks/include/install_curve-nbd.yml
- mk-tar.sh
- nbd/nbd-package/DEBIAN/postinst
- nbd/nbd-package/DEBIAN/prerm
- nbd/nbd-package/etc/curve/curvetab
- nbd/nbd-package/usr/map_curve_disk.sh
- nbd/src/define.h
- nbd/src/main.cpp
> nbd: add auto map at boot

- nbd/src/NBDTool.cpp
- nbd/src/define.h
- nbd/src/main.cpp
- nbd/src/util.cpp
- nbd/src/util.h
> nbd: prevent mounted device to unmap

- src/client/client_metric.h
- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/client/mds_client_base.cpp
- src/client/mds_client_base.h
- src/client/source_reader.cpp
- src/common/string_util.h
- test/client/client_mdsclient_metacache_unittest.cpp
- test/client/client_metric_test.cpp
- test/client/client_session_unittest.cpp
- test/client/client_userinfo_unittest.cpp
- test/client/copyset_client_test.cpp
- test/client/file_instance_test.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/client/libcurve_interface_unittest.cpp
After #172 and #209, source volume data of the clone volume can be read within the client through SourceReader, and each source volume was also opened and represented by a FileInstance, but `FileInstance::mdsclient_` points to `FileClient::mdsClient_`, so after FileClient is destroyed, `FileInstance::mdsclient_` becomes dangling pointer.
To fix this problem, we let `FileClient::mdsClient_` be a shared_ptr, and each FileInstance holds ownership of it.
> client: fix segment fault in SourceReader

- mk-deb.sh
- mk-tar.sh
Issue Number: close #215 #216
Make sure the required temp so file exist when building python package with `mk-tar.sh` and `mk-deb.sh`
How it Works: 
Backup and Restore the required temp so file before `bazel build` action when building python package. See #215 for detail
N/A
> scripts: fix python build error

- proto/copyset.proto
- src/chunkserver/copyset_node_manager.cpp
- src/chunkserver/copyset_node_manager.h
- src/chunkserver/copyset_service.cpp
- src/chunkserver/copyset_service.h
- src/tools/curve_cli.cpp
- src/tools/curve_cli.h
- test/chunkserver/copyset_service_test.cpp
- test/tools/curve_cli_test.cpp
- test/tools/mock/mock_copyset_service.h
> tools: fixed remove broken copyset after remove peer

- src/mds/schedule/copySetScheduler.cpp
- src/mds/schedule/leaderScheduler.cpp
- src/mds/schedule/rapidLeaderScheduler.cpp
- src/mds/schedule/scheduler.cpp
- src/mds/schedule/scheduler.h
- src/mds/schedule/scheduler_helper.cpp
- src/mds/schedule/scheduler_helper.h
- src/tools/status_tool.cpp
- test/mds/schedule/leaderScheduler_test.cpp
- test/mds/schedule/rapidLeaderSheduler_test.cpp
- test/mds/schedule/replicaScheduler_test.cpp
- test/mds/schedule/schedulerPOC/scheduler_poc.cpp
schedule out copyset from online and pendding chunkserver
How it Works: 
schedule out copyset from online and pendding chunkserver
> schedule pendding online chunkserver

- src/client/copyset_client.cpp
- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/iomanager4file.cpp
- src/client/lease_executor.cpp
- src/client/lease_executor.h
- src/client/metacache.cpp
- test/client/BUILD
- test/client/lease_executor_test.cpp
- test/resources.list
When uninit FileClient and some files are not closed, in FileInstance's destructor it will destroy LeaseExecutor, but LeaseExecutor's destructor will wait for backend lease task to stop, so without explicit close a file, thread will be stuck here.
Explicit call `LeaseExecutor::Stop` in `FileInstance::UnInitialize`
No
> client: explicit stop LeaseExecutor in FileInstance::UnInitialize

- src/mds/heartbeat/chunkserver_healthy_checker.cpp
- test/mds/heartbeat/chunkserver_healthy_checker_test.cpp
Problem Summary: set unstable pendding empty chunkserver status to retired
How it Works:
> set unstable pendding empty chunkserver status to retired

- curvefs_python/BUILD_bak
- proto/BUILD
- proto/chunk.proto
- proto/heartbeat.proto
- src/chunkserver/chunkserver.cpp
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.h
- src/chunkserver/datastore/chunkserver_datastore.cpp
- src/chunkserver/datastore/chunkserver_datastore.h
- src/chunkserver/heartbeat.cpp
- src/chunkserver/heartbeat.h
- src/chunkserver/op_request.cpp
- src/chunkserver/scan_manager.cpp
- src/chunkserver/scan_manager.h
- src/mds/topology/topology.cpp
- test/chunkserver/datastore/datastore_mock_unittest.cpp
- test/chunkserver/mock_copyset_node.h
- test/chunkserver/scan_manager_test.cpp
> chunkserver: fix crc issues

- proto/BUILD
- proto/common.proto
- proto/heartbeat.proto
- proto/topology.proto
- src/mds/heartbeat/heartbeat_manager.cpp
- src/mds/heartbeat/topo_updater.cpp
- src/mds/topology/topology.cpp
- src/mds/topology/topology_item.cpp
- src/mds/topology/topology_item.h
- src/mds/topology/topology_service.cpp
- src/mds/topology/topology_service.h
- src/mds/topology/topology_service_manager.cpp
- src/mds/topology/topology_service_manager.h
- src/tools/copyset_check_core.cpp
- src/tools/copyset_check_core.h
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/status_tool.cpp
- src/tools/status_tool.h
- test/mds/topology/mock_topology.h
- test/mds/topology/test_topology_service.cpp
- test/mds/topology/test_topology_service_manager.cpp
- test/tools/copyset_check_core_test.cpp
- test/tools/curve_tool_factory_test.cpp
- test/tools/mds_client_test.cpp
- test/tools/mock/mock_mds_client.h
- test/tools/mock/mock_topology_service.h
> tools: support scan-status command and imporve status command

- src/client/io_tracker.h
- src/client/splitor.cpp
- src/mds/nameserver2/clean_manager.cpp
- src/mds/nameserver2/clean_manager.h
- src/mds/nameserver2/clean_task.h
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/curvefs.h
- src/mds/nameserver2/metric.cpp
- src/mds/nameserver2/metric.h
- src/mds/topology/topology_chunk_allocator.cpp
- test/mds/nameserver2/clean_discard_segment_task_test.cpp
- test/mds/nameserver2/curvefs_test.cpp
- test/mds/nameserver2/mock/mock_clean_manager.h
> mds: fix clone volume missing throttle params and may start two or more tasks to clean same segment

- thirdparties/glog/glog.patch
chunkserver will exit with core dump when receive SIGINT 
Issue Number: close #425  
1. we compile a debug version, and  locate abort() as follwing:
2. abort happens when destruct (static bthread::TimerThread timer_) in curve::common::LeakyBucket.
The  lifecycle of static member variable in class  is the same as process
3.  bthread::TimerThread destruct with run() exit. run() need log print before exit.
4. log print need get vmodule_lock, which is a globle static variable
5.  globle static variable and  class static member variable  are both detruct before process exit. But the order of their destruction is determined by the compiler. If  vmodule_lock destruct before bthread::TimerThread, the process will core dump
change static Mutex vmodule_lock -> …
> glog: fix chunkserver exit with core

- proto/copyset.proto
- src/chunkserver/copyset_node_manager.cpp
- src/chunkserver/copyset_node_manager.h
- src/chunkserver/copyset_service.cpp
- src/chunkserver/copyset_service.h
- src/tools/curve_cli.cpp
- src/tools/curve_cli.h
- test/chunkserver/copyset_service_test.cpp
- test/tools/curve_cli_test.cpp
- test/tools/mock/mock_copyset_service.h
> tools: fixed remove copyset after remove peer

- src/snapshotcloneserver/common/snapshotclone_meta_store.h
- src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.cpp
- src/snapshotcloneserver/common/snapshotclone_meta_store_etcd.h
- src/snapshotcloneserver/snapshot/snapshot_core.cpp
- src/snapshotcloneserver/snapshot/snapshot_core.h
- src/snapshotcloneserver/snapshot/snapshot_task_manager.cpp
- test/integration/snapshotcloneserver/fake_snapshotclone_meta_store.cpp
- test/integration/snapshotcloneserver/fake_snapshotclone_meta_store.h
- test/integration/snapshotcloneserver/snapshotcloneserver_concurrent_test.cpp
- test/snapshotcloneserver/mock_snapshot_server.h
- test/snapshotcloneserver/test_snapshot_core.cpp
- test/snapshotcloneserver/test_snapshot_service_manager.cpp
- test/snapshotcloneserver/test_snapshotclone_meta_store_etcd.cpp
> snapshotcloneserver: fixed cancel task lost

- nbd/nbd-package/etc/curve/curvetab
- nbd/nbd-package/usr/bin/map_curve_disk.sh
> nbd: add auto mount options

- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/roles/install_package/templates/mds-daemon.sh.j2
- curve-ansible/roles/install_package/templates/snapshot-daemon.sh.j2
> scripts: fix potential overflow when cnovert ip to value

- curve-ansible/roles/install_package/templates/chunkserver_ctl.sh.j2
- curve-ansible/roles/install_package/templates/mds-daemon.sh.j2
- curve-ansible/roles/install_package/templates/snapshot-daemon.sh.j2
- src/client/client_metric.h
- src/client/copyset_client.cpp
- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/lease_executor.cpp
- src/client/lease_executor.h
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- src/client/mds_client.cpp
- src/client/mds_client.h
- src/client/mds_client_base.cpp
- src/client/mds_client_base.h
- src/client/metacache.cpp
- src/client/source_reader.cpp
- src/common/string_util.h
- test/client/BUILD
- test/client/client_mdsclient_metacache_unittest.cpp
- test/client/client_metric_test.cpp
- test/client/client_session_unittest.cpp
- test/client/client_userifo_unittest.cpp
- test/client/copyset_client_test.cpp
- test/client/file_instance_test.cpp
- test/client/iotracker_splitor_unittest.cpp
- test/client/lease_executor_test.cpp
- test/client/libcurve_interface_unittest.cpp
- test/client/mock/mock_namespace_service.h
- test/resources.list
What's Changed: backport #368 #358 #464  to release1.2
How it Works:
> backport some bug fix to release1.2

- src/client/libcurve_file.cpp
Prometheus doesn't support metric name like an address "0x556168fe1720"
How it Works:
> client: fix a bvar name

- curvefs/src/mds/metaserver_client.h
- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/s3/metaserver_s3.cpp
- curvefs/src/metaserver/s3/metaserver_s3.h
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.h
- curvefs/test/client/BUILD
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/metaserver_s3_adaptor_test.cpp
- curvefs/test/metaserver/metaserver_s3_adaptor_test.h
- curvefs/test/metaserver/moc_metaserver_s3_adaptor.h
- curvefs/test/metaserver/mock_metaserver_s3.h
metaserver deletes objects from S3,  thses objects belong to inode
use delete(inode) function. 
curvefs/src/metaserver/s3/metaserver_s3_adaptor.h
curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
curvefs/src/metaserver/s3/metaserver_s3.cpp
curvefs/src/metaserver/s3/metaserver_s3.h
How it Works:
> Fs metaserver delete

- curvefs/conf/curvefs_client.conf
- curvefs/conf/mds.conf
- curvefs/proto/mds.proto
- curvefs/src/mds/BUILD
- curvefs/src/mds/chunkid_allocator.cpp
- curvefs/src/mds/chunkid_allocator.h
- curvefs/src/mds/common/storage_key.h
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/mds.h
- curvefs/src/mds/mds_service.cpp
- curvefs/src/mds/mds_service.h
- curvefs/test/mds/BUILD
- curvefs/test/mds/chunkid_allocator_test.cpp
- curvefs/test/mds/mds_service_test.cpp
- curvefs/test/mds/mds_test.cpp
- curvefs/test/mds/mock_chunkid_allocator.h
- curvefs/test/mds/mock_etcdclient.h
add allocate chunkId in mds and persist chunkId in etcd
add AllocateS3Chunk in nds services;
add ChunkIdAllocator in mds ;
persist chunkId in etcd
How it Works:
when get allocate chunkid request, check the chunkIds pool is exhausted or not;
if the pool is not exhausted,
return a chunk id;
else
allocate a pool chunkId
AllocateS3Chunk service was in space, now is in mds.
some request not change.
the AllocateS3Chunk service in space is not removed.
> chunkid to etcd

- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/src/metaserver/dentry_storage.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/metaserver/dentry_storage_test.cpp
- curvefs/test/metaserver/partition_test.cpp
1. ListDentry returns NOT_FOUND when no matches
2. Set partition minimum start id to ROOTINODEID+1
How it Works:
> curvefs/metaserver: fix some bugs

- curvefs/src/metaserver/inode_storage.cpp
when first write s3type inode, update inode will crash in the empty assert in "void MemoryInodeStorage::MergeTwoS3ChunkInfoMap"
How it Works:
> curvefs/metaserver: fix crash when first write of s3 inode

- nebd/src/part1/libnebd.h
When this header file is included by C code, keyword 'struct' must be used.
Issue Number: #646
add keyword struct.
How it Works:
No
> In C language, keyword 'struct' must be used.

- curvefs/src/common/s3util.h
- curvefs/test/metaserver/metaserver_s3_adaptor_test.cpp
- curvefs/test/metaserver/s3compactwq_test.cpp
move fsid and inode front of s3obj name
How it Works:
> curvefs/common: move fsid,inode front of s3obj name

- mk-deb.sh
- mk-tar.sh
After installed these packages, developers no longer need to
make a copy of libnebd.h from curve source repository. This makes
easier for third-party developers, before this, for example,
fio and polarfs etcs are forced to make a copy of the file.
Issue Number: ##664
How it Works:
> make packages include libnebd.h.

- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Issue Number: close #686 
AWS SDK initapi/shutdownapi should be only called once in one program.
Multi s3adapter in a program will cause problem. Seperate shutdown from deinit function.
How it Works:
> curve: make s3sdk init/shutdown only be called once

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/mock_client_s3.h
When the background is flush copy dataWCacheMap_, the write thread may modify dataWCacheMap_ without locking.
It has been confirmed that UpdateWriteCacheMap is not required
When the background is flush copy dataWCacheMap_, the write thread may modify dataWCacheMap_ without locking.
It has been confirmed that UpdateWriteCacheMap is not required
Issue Number: close #739  
How it Works:
> curvefs/client: fix vdbench fuse to appear coredump

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/mock_client_s3.h
- curvefs/test/client/test_disk_cache_manager_impl.cpp
before upload success, the s3 is disable, then the thread will block
Issue Number: close #709  
How it Works:
> curvefs/client: fix umount bug

- curvefs/docker/Dockerfile
- curvefs/src/tools/curvefs_tool_define.h
1. fix curvefs_tool name error in --example
2. solve the problem of missing curvefs_tool configuration file, mkdir
/etc/curvefs when make docker image and sync conf file when deploy
Issue Number: close #729  
The curvefs_tool configuration file is not synchronized
dockerfile 
How it Works:
When building the docker image, create /etc/curvefs,
sync config file when deploy
> curvefs_tool: fix curvefs_tool name & fix config

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
Fixs: https://github.com/opencurve/curve/issues/750
Issue Number: close #750  
Problem Summary: when use disk cache and disk cache is full, we forget to upload obj to s3
How it Works:
> curvefs/client: fix problem that after disk cache full, obj forget to upload

- curvefs/src/mds/BUILD
- curvefs/src/metaserver/BUILD
- curvefs/src/space/BUILD
Issue Number: close #747
rename mds/metaserver/space of curvefs to `curvefs-mds`/`curvefs-metaserver`/`curvefs-space` to consistent with `curve-fuse`
> curvefs: rename bazel BUILD binary name

- curvefs/src/client/main.c
solve the proble when use curve-fuse -h will core dumped in
UnInitFuseClient, since fuse client object is not construct when use -h.
Issue Number: close #745  
How it Works:
> curvefs/client : fix core after curve-fuse -h

- curvefs/proto/metaserver.proto
- curvefs/src/client/client_operator.cpp
- curvefs/src/metaserver/dentry_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/metaserver/dentry_manager_test.cpp
> curvefs/metaserver: fix metastore reload failed when dentry already exists

- curvefs/src/metaserver/dumpfile.cpp
- curvefs/test/metaserver/dumpfile_test.cpp
Issue Number: close #768
Problem Summary: The length of the saved string exceeds the limit
How it Works:
> curvefs/metaserver: fixed the length of the saved string exceeds the limit size.

- curvefs/docker/Dockerfile
- curvefs/src/tools/curvefs_tool_define.h
1. fix curvefs_tool name error in --example
2. solve the problem of missing curvefs_tool configuration file, mkdir
/etc/curvefs when make docker image and sync conf file when deploy
Issue Number: close #729  
The curvefs_tool configuration file is not synchronized
dockerfile 
How it Works:
When building the docker image, create /etc/curvefs,
sync config file when deploy
> fix curvefs_tool name & fix config

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_read.cpp
Issue Number: close #798  
after cache disk has been dropped, then we must return failed.
> curvefs/client: fix inconsistent after cache disk has been dropped

- curvefs/docker/Dockerfile
- curvefs/src/metaserver/dumpfile.cpp
- curvefs/src/metaserver/storage.h
- curvefs/test/metaserver/storage_test.cpp
Issue Number: close #803
Problem Summary: metastore reload fail and report INVALID_CHECKUM
How it Works:
> curvefs/metaserver: fixed metastore reload fail and report INVALID_CHECKSUM

- curvefs/src/mds/mds.cpp
- curvefs/src/metaserver/metaserver.cpp
Issue Number: close #804 
Leader observation is handled in another detached thread,
and when observe leader failed, it raises a SIGTERM in the detached thread.
By default, we didn't register handler for SIGTERM, so the process should exit directly.
But, in current scenario, it seems the SIGTERM signal is ignored.
To avoid this problem, register handler for SIGTERM through brpc's flags graceful_quit_on_sigterm
> curvefs-mds/curvefs-metaserver: install SIGTERM handler

- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
Issue Number: close #796
when metaserver restart, each raft group will reload from snapshot and then
call CopysetNode::on_configuration_committed.
currently, we didn't implement on_configuration_committed, and reset configuration in on_snapshot_load has a bug, so leads to ListPeers return empty configuration.
let on_snapshot_load just recover metastore, and reset copyset configuration in on_configuration_committed.
> curvefs-metaserver: fix restart metaserver lose copyset configuration

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_manager.h
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/src/metaserver/s3infocache.cpp
- curvefs/src/metaserver/s3infocache.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/mock_s3_adapter.h
- curvefs/test/metaserver/mock_s3compactwq_impl.h
- curvefs/test/metaserver/mock_s3infocache.h
- curvefs/test/metaserver/s3compactwq_test.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
prerequisite #678 
add S3InfoCache and S3AdapterManager
when do s3compact, get S3Info from cache or MDS.
How it Works:
> curvefs/metaserver: s3compact add multi s3info support

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/inode_wrapper.h
fix poor random read performance after random write
Through testing and metrices analysis, it is found that the performance bottleneck is mainly in the copy of the inode, and the copy is only to obtain the length, so there is no need
Issue Number: close #809  
How it Works:
> curvefs/client: fix poor random read performance after random write

- curvefs/src/metaserver/s3/metaserver_s3.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/test/metaserver/metaserver_s3_test.cpp
When deleting an s3 object, the s3 object is deleted by someone else,
it will return a failed code
Issue Number: close #829 
when delete fail check the s3 object status, if not exist return normal.
How it Works:
> metaserver/s3_adaptor: fix delete s3 object error

- conf/tools.conf
- curve-ansible/roles/generate_config/templates/tools.conf.j2
- src/tools/curve_tool_define.h
- src/tools/curve_tool_main.cpp
- src/tools/mds_client.cpp
- src/tools/namespace_tool_core.cpp
Issue Number: close #831
curve_ops_tool uses hard code `root` to check whether a user is root, so when deploying curve with different `curve_root_username` and `curve_root_password`, MDS will report `kOwnerAuthFail`
How it Works:
> curve_ops_tool: adapt to user-defined root user and password

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/metaserver/trash.cpp
1. default dir size to 4096
2. fix a trash dtime setting bug, otherwize tash will not keep 7 days
Issue Number: close #795，#827 
How it Works:
> curvefs/client&metaserver: fix dir size & trash dtime bug

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/metaserver/trash.cpp
1. default dir size to 4096
2. fix a trash dtime setting bug, otherwize tash will not keep 7 days
Issue Number: close #795，#827 
How it Works:
> curvefs client,metaserver: fix dir size & trash dtime bug

- curvefs/proto/cli2.proto
- curvefs/src/metaserver/copyset/copyset_conf_change.cpp
- curvefs/src/metaserver/copyset/copyset_conf_change.h
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/copyset/copyset_reloader.cpp
- curvefs/src/metaserver/copyset/raft_cli_service2.cpp
- curvefs/src/metaserver/copyset/raft_cli_service2.h
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/src/metaserver/heartbeat.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/copyset/copyset_node_conf_change_test.cpp
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
- curvefs/test/metaserver/copyset/copyset_node_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/copyset/mock/mock_copyset_node.h
- curvefs/test/metaserver/copyset/mock/mock_copyset_node_manager.h
- curvefs/test/metaserver/copyset/raft_cli_servic2_conf_change_test.cpp
- curvefs/test/metaserver/copyset/raft_cli_servic2_test.cpp
- curvefs/test/metaserver/heartbeat_task_executor_test.cpp
- src/fs/local_filesystem.h
Issue Number: close https://github.com/opencurve/curve/issues/763
This PR makes metaserver support configuration changes and executes configuration changes issued by MDS.
How it Works:
Overall approaches are similar to ChunkServer, but have a few modifications.
e.g.,
- add a mutex to protect ongoing configuration change
- raft cli service2 handles TransferLeader/AddPeer/RemovePeer/ChangePeer requests by calling the corresponding copyset node rather than the internal raft node, otherwise, CopysetNode's GetConfChange can't catch this configuration change.
- ...
> curvefs/metaserver: support config change

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/test/client/test_disk_cache_write.cpp
when read one file from disk write cache failed, continue to upload
other files
Issue Number: close #877
> curvefs/client: fix bug that abort uplaod when read one file failed

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/fs_cache_manager_test.cpp
fix readCacheMaxByte is zero, curve-fuse is segment fault.
Issue Number: close #857  
How it Works:
>  curvefs/client: fix readCacheMaxByte is zero, curve-fuse is segment fault.

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
when two rename operators executed in the different diretories at the same time,
the second one maybe get the old txid to prepare, it lets transaction manager
beleive that the previous one is failed and to rollback it, it will causes the
first operation prepare items lost even if itself return success (#855).
Issue Number: close #855
How it Works:
> curvefs/client: fixed concurrent rename causes txid to be overwritten

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/src/metaserver/s3infocache.cpp
- curvefs/src/metaserver/s3infocache.h
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/mock_inode_storage.h
- curvefs/test/metaserver/mock_s3infocache.h
- curvefs/test/metaserver/s3compactwq_test.cpp
current mapping from (off, len) to objname is wrong, index in s3objname is wrong.
wrong understanding: a s3chunk(chunkid) is split in to several fixed sized s3objs, and index them from 0
correct understanding: index = offset_in_a_chunkindex/s3_object_max_size
> curvefs/metasever: correct misunderstood of index in s3objname

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/test/client/test_disk_cache_write.cpp
when read one file from disk write cache failed, continue to upload
other files
Issue Number: close #877
> curvefs/client: fix bugs that abort uplaod when read one file failed

- src/client/libcurve_file.cpp
- src/common/string_util.h
Issue Number: close #895 
Problem Summary: a metric name is hexstring
if expose two different metrics with the same name, bvar will complain name is already exposed. so I just use an address to distinguish them, but forget a prefix. In this PR, add back the prefix.
How it Works:
> curve-client: fix an illegal metric name

- curvefs/src/client/s3/client_s3.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/mock_s3_adapter.h
curvefs/client: update inode cache and retry ReadFromS3 when obj does not
exist. because objs may be deleted by s3compact, client inode cache is
stale.
> curvefs/client: retry ReadFromS3 when needed

- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/s3compact.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_manager.h
we need erase s3compact from vector when partition is deleted
> curvefs/metaserver: fix s3compact crash when partition have been deleted

- curvefs/test/metaserver/copyset/copyset_service_test.cpp
- curvefs/test/metaserver/copyset/raft_cli_servic2_conf_change_test.cpp
- curvefs/test/metaserver/copyset/raft_cli_servic2_test.cpp
Issue Number: close #930 
currently, we run all unittests parallelly in a single host,
and most unittests consume lots of CPU, therefore there's a chance that
default rpc timeout 500ms is not enough.
set default rpc timeout to 10 seconds
> unittest/metaserver: enlarge default rpc timeout to 10 seconds

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
fix truncate file is too slow to reach a large length
Issue Number: close #914  
How it Works:
> curvefs/client: fix truncate file is too slow to reach a large length

- curvefs/conf/metaserver.conf
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition_cleaner.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/metaserver/partition_clean_test.cpp
Issue Number: #883 
Problem Summary: fix some bug when delete fs
1. Mds mark partition to DELETING after call metaserver DeletePartition.
2. When GetInode, delete check Partition status.
3. Only leader copyset can should delete inode and partition from raft.
4. s3 param conf in metaserver.conf and client.conf is mismatch. Change theas param same.
How it Works:
> curvefs/mds:fix delete fs

- curvefs/conf/tools.conf
- curvefs/src/mds/mds.cpp
- curvefs/src/tools/check/curvefs_copyset_check.cpp
- curvefs/src/tools/check/curvefs_copyset_check.h
- curvefs/src/tools/copyset/curvefs_copyset_base_tool.cpp
- curvefs/src/tools/copyset/curvefs_copyset_base_tool.h
- curvefs/src/tools/copyset/curvefs_copyset_status.cpp
- curvefs/src/tools/copyset/curvefs_copyset_status.h
- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/create/curvefs_create_fs.h
- curvefs/src/tools/curvefs_tool.cpp
- curvefs/src/tools/curvefs_tool.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/curvefs_tool_factory.cpp
- curvefs/src/tools/curvefs_tool_metric.cpp
- curvefs/src/tools/delete/curvefs_delete_fs_tool.cpp
- curvefs/src/tools/delete/curvefs_delete_fs_tool.h
- curvefs/src/tools/list/curvefs_copysetinfo_list.cpp
- curvefs/src/tools/list/curvefs_fsinfo_list.cpp
- curvefs/src/tools/query/curvefs_copyset_query.cpp
- curvefs/src/tools/query/curvefs_copyset_query.h
- curvefs/src/tools/query/curvefs_fs_query.cpp
- curvefs/src/tools/query/curvefs_fs_query.h
- curvefs/src/tools/query/curvefs_metaserver_query.cpp
- curvefs/src/tools/query/curvefs_metaserver_query.h
- curvefs/src/tools/query/curvefs_partition_query.cpp
- curvefs/src/tools/query/curvefs_partition_query.h
- curvefs/src/tools/umount/curvefs_umount_fs_tool.cpp
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
Issue Number: close #932 #922 #945 
1. fix some error in  create-fs
2. fix some error output in curvefs_tool
3. adjust output of umount-fs
4. adjust output of create-fs: add fs exist (create same fs name but the
parameters are inconsistent)
5. adjust output of query-copyset: indicate that the number of statuses
is inconsistent with the peers in the info
6. adjust output of query-fs: add fs not found
7. adjust output of delete-fs: add fs not found
8. fix check-copyset
9. fix query-copyset fail when query same copyset: add requset
copysetkey when sure
How it Works:
> curvefs/tool: fix error

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/test/metaserver/metastore_test.cpp
- src/common/s3_adapter.cpp
Issue Number:  #995
Problem Summary: fix insert inode fail when load deleting partition
How it Works:
> fix insert inode fail when load deleting partition

- curvefs/conf/mds.conf
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/copyset/copyset_service.cpp
- curvefs/test/metaserver/copyset/copyset_node_manager_test.cpp
- curvefs/test/metaserver/copyset/copyset_service_test.cpp
curvefs: fix create copyset when exist already. If peers are all the same will success, otherwise return exist.
#998 
How it Works:
> curvefs: fix create copyset when exist already.

- curvefs/src/mds/heartbeat/copyset_conf_generator.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/test/mds/topology/test_topology.cpp
curvefs mds heartbeat doesn't delete copyset creating.
The empty conf will send to metaserver to delete copysets which don't exist in mds, but when the copyset just created in metaserver and have not add to topology, the metaserver heartbeat will contain these copysets' infomation.
#999 
How it Works:
> curvefs mds heartbeat doesn't delete copyset creating.

- curvefs/src/client/fuse_client.cpp
- curvefs/src/tools/create/curvefs_create_fs.cpp
- curvefs/src/tools/create/curvefs_create_fs.h
- curvefs/src/tools/curvefs_tool.h
- curvefs/test/client/test_fuse_client.cpp
1. curvefs_tool has add create-fs
2. fix some error output
Issue Number: close #891  
How it Works:
> curvefs/client: rm create fs in init

- curvefs/conf/metaserver.conf
- curvefs/conf/tools.conf
- curvefs/proto/topology.proto
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/mds/heartbeat/copyset_conf_generator.cpp
- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/schedule/topoAdapter.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
- curvefs/src/metaserver/register.cpp
- curvefs/src/metaserver/register.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/list/curvefs_topology_tree_json.cpp
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/mds/heartbeat/heartbeat_manager_test.cpp
- curvefs/test/mds/topology/test_topology_helper.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/mds/topology/test_topology_service.cpp
…cluster communicate itself and some external services support for client and management tools.
If all the services start on the same ip+port will affect the communication within the cluster when the heavy stress from client.
Start the services needed by outsied on another ip+port as a external server.
#973 
How it Works:
> curvefs metaserver supports external services

- curvefs/src/tools/README.md
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/delete/curvefs_delete_fs_tool.cpp
- curvefs/src/tools/delete/curvefs_delete_fs_tool.h
1. add -noconfirm for delete-fs
2. adjust delete-fs confirm input
3. Readme fix
Issue Number: close #843  
How it Works:
> curvefs/tool: delete-fs

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_inode_cache_manager.cpp
Issue Number: close #935  
Update inode asynchronously， so that update inode will not block each others.
> curvefs client : update inode async

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.h
- src/common/leaky_bucket.cpp
- src/common/leaky_bucket.h
- src/common/throttle.cpp
- test/common/leaky_bucket_test.cpp
- test/common/throttle_test.cpp
> curve/common: optimize leaky bucket algorithm

- curvefs/conf/metaserver.conf
- curvefs/proto/metaserver.proto
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/s3compact.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_manager.h
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/s3compactwq_test.cpp
1. refactor s3compact code
2. with diskcache write cache enable, metadata may be
newer than data in s3. so we will meet s3 read failure,
add retry to workaround this situation.
3. change GetOrModifyS3ChunkInfo request process, to keep order in s3chunkinfolist
> refactor s3compact code & workaround read failure when diskcachetype=2

- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_wq_impl.cpp
we need release s3adapter after get one(SetupS3Adapter) in a compactchunks
we will only get/release in compactchunks function
> curvefs/metaserver: fix s3adapter get/release bug

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
Issue Number: close #1025 #1056
after restarting metaserver, all previous copysets will be created and recover from raft snapshot, during recovery, it will also restart partition clean tasks, and each task needs corresponding copyset node.
deadlock happens because creating and recovering a copyset is protected by CopysetNodeManager's lock, but partition clean tasks also acquire this lock to get corresponding copyset node.
another problem is when copyset needs purge, we forget to stop related tasks like partition cleaning task, s3 compact tasks. so, when these tasks start to execution, metaserver will end up with segment fault.
this patch passes CopysetNode when creating MetaStore, so partition clean task no need to acquire the lock, and, also call …
> metaserver: fix deadlock and remove related tasks when copyset stop

- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/rpcclient/mock_metaserver_service.h
Issue Number: close #1067 
How it Works:
> curvefs client : fix bug of getleader always fails causes stack overflow

- curvefs/src/tools/copyset/curvefs_copyset_base_tool.cpp
- curvefs/src/tools/status/curvefs_copyset_status.cpp
Issue Number: close #1022 #1026 
when get all coysetinfo (in curvefs_copyset_status) has error,
tools would not to check copyset status,
so get health instaed of unhealthy
How it Works:
> curvefs/tool: fix copyset health check error

- curvefs/src/mds/heartbeat/copyset_conf_generator.cpp
- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/heartbeat/topo_updater.cpp
- curvefs/src/mds/topology/topology.cpp
- curvefs/test/mds/heartbeat/heartbeat_manager_test.cpp
- curvefs/test/mds/topology/test_topology.cpp
Issue Number: #1061
The tool shows that some copysets were not migrated successfully. Because the copyset did not update its candidate from heartbeat. So it will fail when change peer copyset.
What's Changed:  Update copyset cadidate when heartbeat
> curvefs update copyset condidate

- curvefs/conf/client.conf
- curvefs/proto/metaserver.proto
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/trash.cpp
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/test_helper.cpp
NOTES:
Now we implemented close-to-open consistency and multi-mountpoint for one filesystem.
A file written by a client, closed, and then opened by any client can read the latest data.
The scenario where multiple mount points modify the same resource ( Any modification to a
file ) at the same time is not guaranteed.
How it Works:
> curvefs: a curve filesystem can be mounted by multi fuse clients

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_read.cpp
- curvefs/src/client/s3/disk_cache_read.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_read.cpp
- curvefs/test/client/test_disk_cache_write.cpp
- src/common/lru_cache.h
- test/common/lru_cache_test.cpp
> curvefs/client: adapter lru list for disk cache

- curvefs/conf/tools.conf
set
s3.blocksize=4194304
s3.chunksize=67108864
How it Works:
> curvefs_tool:fix_s3_conf

- test/common/mock_s3_adapter.h
fs_mageger ut error:
C++ exception with description "Resource temporarily unavailable"
due to not set asyncThreadNum and not mock void init(const
S3AdapterOption &), ut will call init function and create thread by uninit
value.
How it Works:
> fix_fs_manager_ut

- curvefs/conf/metaserver.conf
- curvefs/proto/metaserver.proto
- curvefs/proto/topology.proto
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/metaserver/metaserver_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
Issue Number: #938 
Problem Summary:  
1. persist metaserver meta info in local filesystem, persist this struct
```
message MetaServerMetadata {
required uint32 version = 1;
required uint32 id = 2;
required string token = 3;
required uint32 checksum = 4;
}
```
2. When metasever regist to mds, if mds already has metaserver with same ip and port, and metaserver in mds already has copyset, reject this request.
How it Works:
> persist metaserver meta info

- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/test/client/test_disk_cache_write.cpp
> curvefs/client: fix bug when upload failed.

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/copyset/copyset_node_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node_manager.h
- curvefs/src/metaserver/s3compact_manager.cpp
- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/copyset/copyset_node_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/mock_s3compactwq_impl.h
- curvefs/test/metaserver/s3compactwq_test.cpp
Issue Number: close #1155 
previously, s3 compact task stores a raw pointer of copyset,
so after copyset is been purged, s3 compact task will cause
curvefs-metaserver process exited.
now, let s3 compact task store a shared copyset node.
> curvefs/metaserver: let s3 compact task store a shared copyset node

- curvefs/conf/tools.conf
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/mds/mds_test.cpp
1. Fix the summary info of hardlink when enableSumInDIr if false. Because batch get inodeAttr is divided by batch limit, the struct std::set will not deal with hardlink.
2. Fix UpdateParentInodeXattr dirty flag, the update of xattr doesn't based on dirty flag.
3. Disable hardlink when  enableSumInDIr is true.
4. batchGetInodeAttr and batchGetXattr from metaserver after find in inodeCache.
How it Works:
> curvefs/client: fix bug of support summary info in dir xattr

- curvefs/conf/metaserver.conf
Problem Summary: modify metaserver.conf storage max quota
**storage.max_memory_quota_bytes** from 500GB to 30GB
> curvefs/conf: modify metaserver.conf storage max quota

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/dentry_cache_manager.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/fuse_volume_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/main.c
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
- curvefs/test/client/test_dentry_cache_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
https://github.com/opencurve/curve/issues/1213
https://github.com/opencurve/curve/issues/1209
https://github.com/opencurve/curve/issues/1201
https://github.com/opencurve/curve/issues/1197
1. Split the persistence operations in FuseOpRelease into FuseOpFlush
2. Dentry does not use local caching when enableCto
How it Works:
> curvefs/client: fix bug issue

- curvefs/conf/tools.conf
- curvefs/proto/metaserver.proto
- curvefs/src/client/client_operator.cpp
- curvefs/src/client/client_operator.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/base_client.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/partition_clean_test.cpp
- curvefs/test/metaserver/partition_test.cpp
> curvefs: xattr summary info support hard link

- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
Issue Number: close #1226  
How it Works:
> curvefs/client: fix waitIntervalSec_ is not init

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/conf/tools.conf
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
We do not support virtual host.
Support both virtual host and path style
How it Works:
Add a config, init client with config
>  backport-2.2: add s3.useVirtualAddressing config 

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/conf/tools.conf
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
We do not support virtual host.
Support both virtual host and path style
How it Works:
Add a config, init client with config
> backport-2.1: add s3.useVirtualAddressing config

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/conf/tools.conf
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
We do not support virtual host.
Support both virtual host and path style
How it Works:
Add a config, init client with config
> add s3.useVirtualAddressing config

- .gitignore
- curvefs/monitor/README.md
- curvefs/monitor/curve-monitor.sh
- curvefs/monitor/docker-compose.yml
- curvefs/monitor/grafana-report.py
- curvefs/monitor/grafana/dashboards/client.json
- curvefs/monitor/grafana/dashboards/etcd.json
- curvefs/monitor/grafana/dashboards/mds.json
- curvefs/monitor/grafana/dashboards/metaserver.json
- curvefs/monitor/grafana/grafana.ini
- curvefs/monitor/grafana/provisioning/dashboards/all.yml
- curvefs/monitor/grafana/provisioning/datasources/all.yml
- curvefs/monitor/prometheus/prometheus.yml
- curvefs/monitor/target.ini
- curvefs/monitor/target_json.py
- curvefs/monitor/update_dashboard.sh
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/tools/status/curvefs_mds_status.cpp
- curvefs/src/tools/status/curvefs_status_base_tool.cpp
Issue Number: close #1236  
1. add curvefs monitor
2. curvefs_tool status-mds show dummy port for dummy mds
How it Works:
> curvefs/monitor: promethus

- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/test/client/test_inodeWrapper.cpp
> curve-fuse: fix missing update extent cache

- curvefs/src/client/curve_fuse_op.cpp
Issue Number: #1321 
Use vlog_level to dynamically modify the client's vlog level.
Set the validator to the flag vlog_level, and only modify the log level
by assigning it to FLAG_v when the vlog_level value is legal.
How it Works:
You can modify the vlog level to 0 using:
curl -s http://127.0.0.1:9000/flags/vlog_level?setvalue=0
> curvefs/client:change log level on fly

- curvefs/src/client/curve_fuse_op.cpp
Use vlog_level to dynamically modify the client's log level.
Set the validator to the flag vlog_level, and only modify the log level
by assigning it to FLAG_v when the vlog_level value is legal.
You can modify the daily log level to 0 using:
curl -s http://127.0.0.1:9000/flags/vlog_level?setvalue=0
How it Works:
> curvefs/client:change vlog level on fly

- curvefs/src/mds/metric/metric.cpp
- curvefs/src/mds/metric/metric.h
- curvefs/src/tools/curvefs_tool_define.cpp
Issue Number: #1301  
add port in mountpoint(like: {host}:{port}:{path}),
but mds metric only identify {host}:{path}.
add port in struct MoutPoint, fix key and ParseMountPoint func
How it Works:
> curvefs:fix_mountpoint

- curvefs/src/metaserver/storage/rocksdb_storage.cpp
- curvefs/src/metaserver/storage/rocksdb_storage.h
- curvefs/src/metaserver/storage/storage_fstream.h
- curvefs/test/metaserver/storage/storage_fstream_test.cpp
rocksdb's table prefix bloom filter and fixed extract empty key prefix.
How it Works:
> curvefs/metaserver: fixed sseek so slow which caused by unusing

- curvefs/src/metaserver/s3compact_wq_impl.cpp
- curvefs/src/metaserver/s3compact_wq_impl.h
- curvefs/test/metaserver/s3compactwq_test.cpp
s3compact now will process two kinds of chunk
1. the whole chunk is useless; chunkSize * chunkIndex > inodeLen-1
2. part of the chunk is useless; some info in list off+len-1 > inodeLen -1
i wll delete these useless data
> curvefs/metaserver: s3compat support "truncate smaller" correctly

- curvefs/proto/metaserver.proto
- curvefs/src/client/fuse_volume_client.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/volume/default_volume_storage_test.cpp
Issue Number: #1358 
How it Works:
> curvefs: fix a compatible issue which caused by modify FsFileType

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/curve_fuse_op.h
- curvefs/src/client/fuse_common.h
- curvefs/src/client/main.c
- curvefs/test/client/test_fuse_client.cpp
1. remove option: user, volume
2. add option: mdsaddr
3. format help message
4. fix coredump issue
``` bash 
$ ../bazel-bin/curvefs/src/client/curve-fuse --help
usage: ../bazel-bin/curvefs/src/client/curve-fuse -o conf=/etc/curvefs/client.conf -o fsname=testfs \
-o fstype=s3 [-o mdsAddr=1.1.1.1] [OPTIONS] <mountpoint>
Fuse Options:
-h   --help            print help
-V   --version         print version
-d   -o debug          enable debug output (implies -f)
-f                     foreground operation
-s                     disable multi-threaded operation
-o clone_fd            use separate fuse device fd for each thread
(may improve performance)
-o max_idle_threads    the maximum number of idle worker threads
allowed (default: 10)
-o allow_other         allow access by all users
-o …
```
> curvefs/client: add -o mdsaddr=xxxx support

- curvefs/conf/tools.conf
- curvefs/proto/topology.proto
- curvefs/src/tools/BUILD
- curvefs/src/tools/curvefs_tool.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/src/tools/curvefs_tool_define.h
- curvefs/src/tools/curvefs_tool_factory.cpp
- curvefs/src/tools/list/curvefs_partition_list.cpp
- curvefs/src/tools/list/curvefs_partition_list.h
- curvefs/src/tools/query/curvefs_inode.cpp
- curvefs/src/tools/query/curvefs_inode.h
- curvefs/src/tools/query/curvefs_inode_query.cpp
- curvefs/src/tools/query/curvefs_inode_query.h
- curvefs/src/tools/query/curvefs_inode_s3infomap.cpp
- curvefs/src/tools/query/curvefs_inode_s3infomap.h
- curvefs/test/tools/curvefs_umount_fs_tool_test.cpp
Issue Number: close #1218  
1. use GetOrModifyS3ChunkInfoResponse to query inode
2. add list-partition by fsId for locating inodes
3. use GeIndode to get inode baseInfo
How it Works:
```
curvefs_tool   query-inode -fsId=1 -inodeId=167772167
fsId: 1 inodeId: 16777217
-baseInfo:
inodeId: 16777217
fsId: 1
length: 3073219
ctime: 1651219921
ctime_ns: 647724164
mtime: 1651219921
mtime_ns: 647724164
atime: 1651219921
atime_ns: 647724164
uid: 13011
gid: 3000
mode: 33188
nlink: 1
type: TYPE_S3
rdev: 0
s3ChunkInfoMap {
key: 0
value {
s3Chunks {
chunkId: 2
compaction: 0
offset: 0
len: 3073219
size: 3073219
zero: false
}
}
}
openmpcount: 0
parent: 1
-----------------
-s3ChunkInfo:
chunkId: 2
compaction: 0
offset: 0
len: 3073219
size: 3073219
zero: false
Total …
```
> curvefs/tool: support query inode and list partition

- curvefs/conf/tools.conf
- curvefs/src/tools/list/curvefs_partition_list.cpp
- curvefs/src/tools/query/curvefs_inode_query.cpp
- mk-deb.sh
- mk-tar.sh
Issue Number: #1386 
How it Works:
1. fix the bug that always prompted the creation of fs failed due to
rpctimeout.
Since topology.yaml does not save s3 information, the default related
parameters of curvefs_tool running in it are not available, and the mds
check will cause a timeout.
2. fix make release error due to uninitialized variables
3. fix bazel version check erorr in mk-deb.sh and mk-tar.sh
> curvefs_tool/fix create fs fail and build error

- .gitignore
- curvefs/conf/mds.conf
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/schedule/coordinator.cpp
- curvefs/src/mds/schedule/copysetSchedule.cpp
- curvefs/src/mds/schedule/leaderScheduler.cpp
- curvefs/src/mds/schedule/recoverScheduler.cpp
- curvefs/src/mds/schedule/schedule_define.h
- curvefs/src/mds/schedule/scheduler.cpp
- curvefs/src/mds/schedule/scheduler.h
- curvefs/src/mds/schedule/topoAdapter.cpp
- curvefs/src/mds/schedule/topoAdapter.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_config.h
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/schedule/coordinator_test.cpp
- curvefs/test/mds/schedule/leaderScheduler_test.cpp
- curvefs/test/mds/schedule/topoAdapter_test.cpp
- curvefs/test/mds/topology/test_topology.cpp
Issue Number: #1336 
1. Add a leader schedule for curvefs. The purpose is to make the leader in copyset more balanced.
2. Further optimize the creation of copyset. The purpose is to make the copy more balanced.
3. Adjust the calculation method of metaserver resource usage.
> curvefs: add leader scheduler

- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
Issue Number: #1398 
Problem Summary: previous policy use `rand` without `srand()`, so each filesystem will generate same random number sequences
What's Changed: replace `rand` with `butil::fast_rand()`
How it Works:
> curvefs/fuse: fix generate identical inodeid sequences

- thirdparties/glog/glog.patch
Issue Number: #1347 
Problem Summary: fixed glog dead lock in child process
For test, i deploy a cluster and set the metaserver config item `copyset.snapshot_interval_s` to `10`, the cluster run long time and works well, all child process can exit success in time.
> glog: fixed dead lock in child process (#1347).

- nbd/src/main.cpp
variable sys_siglist disappeared on high version glibc, this is
verifyed on Ubuntu jammy.
fix compiling problem
Issue Number: #1375
change nbd main.c 
How it Works:
use official function instead
> nbd: use strsignal

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
Issue Number: #1382
Problem Summary: Copyset is not automatically migrated after stopping metaserver
What's Changed: fix clear copyset creating flag when create copyset success
When copyset created success, it should clear the copyset creating flag. But the code miss this in code.
> fix clear copyset creating flag when create copyset success

- curvefs/src/client/main.c
- curvefs/src/client/s3/client_s3_adaptor.cpp
Issue Number: #1414 
client deadlock after fork
How it Works:
move fork to the front of InitGlog and InitFuseClient
> curvefs/client: move fork to the front of InitGlog and InitFuseClient

- curvefs/conf/client.conf
- curvefs/src/client/common/common.cpp
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/client/xattr_manager.h
- curvefs/src/metaserver/copyset/raft_log_codec.cpp
- curvefs/test/client/test_fuse_client.cpp
1. list dentry concurrently when get summary xattr to improve performance.
2. rebuild xattr code in client and use XattrManager to deal with.
example: du dir1
```
dir1
├── dir2
│   └── file2
├── dir3
├── dir4
├── dir5
└── file1
```
before: need 5 times listDentry synchronously one by one.
now: use 10 threads default to listDentry concurrently.
The test result:
How it Works:
> curvefs/client: list dentry concurrently when get summary xattr

- curvefs/src/client/common/common.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/metaserver/copyset/raft_log_codec.cpp
1. Missing some optype in output function will caused Unknow optype.
2. Missing some opType in raft log coder will caused error when apply from log  at this opType.
How it Works:
> curvefs: missing some optype in output and raft log coder

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/mock_client_s3_cache_manager.h
Although there is no error in repeatedly flushing datacache, the total amount of data in s3 is much larger than the amount of used files in the file system.
Issue Number: #1348  
How it Works:
> curvefs/client: fix s3 takes up more space than  actually uses

- curvefs/src/client/fuse_s3_client.cpp
Issue Number: #1455 
Problem Summary: curvefs client read qps and latancy is missing 
How it Works: add curvefs client read qps and latancy
Side effects(Breaking backward compatibility? Performance regression?): no
- [*] Relevant documentation/comments is changed or added
- [*] I acknowledge that all my contributions will be made under the project's license
> curvefs/client: add client read qps and latancy metric

- src/chunkserver/datastore/file_pool.h
Issue Number: #1443 
Problem Summary: optimization some place
What's Changed: change the FilePoolOptions some functions.
How it Works: we know this struct is memory contiguous. we can use the c++ default function to do it.
> curve-chunkserver: use default generated copy constructor and copy assigment in FilePoolOptions

- curvefs/src/tools/query/curvefs_inode.cpp
- curvefs/src/tools/query/curvefs_inode_s3infomap.cpp
Issue Number: #1476  
inodeId should be uint64_t, use std::stoi to convert the address out of
bounds, should be std::stoull
How it Works:
> curvefs/tool: fix query inode coredump

- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
#1427
The before logic will crash when rcp retry, the iter will forward when retry but this is not expected.
How it Works:
> curvefs/client: fix the data iteration error when rpc retry.

- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/mds/topology/topology_manager.cpp
> curvefs/mds: fix miss set txid when create partition and fix inodeId type

- curvefs/src/client/inode_wrapper.cpp
Issue Number: #1493
Problem Summary: InodeWrapper can represent a directory, so we shouldn't abort when FsFileType is TYPE_DIRECTORY
How it Works:
> curve-fuse: fix sync directory aborted

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
> curvefs/mds: fix create partition error at parallel case

- src/common/interruptible_sleeper.h
- src/common/wait_interval.cpp
- test/common/wait_interval_test.cpp
Issue Number: #1380  
How it Works:
> curvefs/client: fix timer bug

- curvefs/proto/heartbeat.proto
- curvefs/proto/topology.proto
- curvefs/src/mds/heartbeat/heartbeat_manager.cpp
- curvefs/src/mds/heartbeat/topo_updater.cpp
- curvefs/src/mds/heartbeat/topo_updater.h
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/heartbeat.cpp
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/test/mds/topology/test_topology.cpp
- curvefs/test/metaserver/copyset/copyset_node_snapshot_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
- curvefs/test/metaserver/mock/mock_metastore.h
Issue Number: #1468
Problem Summary: curvefs fix load copyset stuck heartbeat #1468
When copyset is loading, it will stuck heartbeat when get partition info list. I make some changes.
1. When copyset is loading, heartbeat do not send partition info in copyset.
2. When copyset get partition, use try lock instead of lock.
3. Do not use heartbeat partition num to update topo.
> curvefs fix load copyset stuck heartbeat #1468

- curvefs/conf/client.conf
- curvefs/proto/metaserver.proto
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/dentry_cache_manager.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/lease/lease_excutor.cpp
- curvefs/src/client/main.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/client/xattr_manager.h
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
1. Get inodeAttr when need attr only intead of get inode.
2. Impliment readdirplus api.
3. Add iAttrCache for fast get some xattr when ls -l.
How it Works:
> curvefs: improve performance of command ls -*.

- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
partitionId is not set in transition constructor
Issue Number: #1541 
How it Works:
> curvefs: fix tool list-copysetInfo error

- curvefs/conf/mds.conf
Issue Number: #1529 
1、原来的patition 格式默认是3，这个数字太小了。这个会导致一个fs的元数据只能分布在3个copyset中。现在把这个数字改成和集群的初始copyset一致，可以让fs的元数据初始分布更均匀。
2、调低了partition中的inode的个数，让fs尽量使用更多的partition去让元数据分布的更均衡。
3、调低了copyset中的partition的个数，避免一个copyset管理太多的元数据。
4、集群默认的copyset个数调整为3的倍数。
1. The original patition format defaults to 3, which is too small. This will cause the metadata of an fs to only be distributed in 3 copies. Now change this number to be consistent with the initial copy of the cluster, which can make the initial distribution of fs metadata more uniform.
2. Reduced the number of inodes in the partition, and let fs use as many partitions as possible to make the metadata distribution more balanced.
3. Reduced the number of partitions in the copy to avoid managing too much …
> curvefs:modify mds.conf

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
Issue Number: #1597  
How it Works:
> curvefs/client: fix statfs problem

- curvefs/src/common/BUILD
- curvefs/src/common/threading.cpp
- curvefs/src/common/threading.h
- curvefs/src/metaserver/BUILD
- curvefs/src/metaserver/copyset/apply_queue.cpp
- curvefs/src/metaserver/copyset/apply_queue.h
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/main.cpp
Support set thread name which will display by `pstree` and `top`, and also set apply queue and bthread worker name in metaserver.
Here is some illustration,
`top` command will show the process's resource usage, and `top -H -p ${pid}` will display every threads' resource usage.
If thread's name is not specified, we will see this
, every thread has the same name, so we can't distinguish them.
After this patch, bthread worker and apply queue's thread name is specified, so we can get more information from `top -H -p ${pid}`
> metaserver: set apply queue and bthread worker thread name

- curvefs/src/metaserver/inode_storage.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
The inode have been getted in inodeManager before updateInode.
How it Works:
> curvefs/metaserver: remove the unnecessary get process in inodeStore

- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
Issue Number: #1672 
Problem Summary: If a metaserver disk is broken, the new disk can not add to cluster to replace the old one. Now I change the logic. If the old metaserver is in offline status, the new metaserver can add to cluster use the old ip and old port.
How it Works:
> filter offline metaserver when regist

- conf/tools.conf
- src/tools/curve_tool_define.cpp
- src/tools/snapshot_clone_client.cpp
- src/tools/snapshot_clone_client.h
- src/tools/status_tool.cpp
- src/tools/status_tool.h
- test/tools/snapshot_clone_client_test.cpp
1. rm the default snapshot server addr
2. If there is no SnapshotServer address, it can be considered that
there is no snapshot service
3. add Add noSnapshotServer_ to StatusTool to mark if a SnapshotServer
exists
Issue Number: [curveadm#112](https://github.com/opencurve/curveadm/issues/112)
How it Works:
> curve: fix curve_ops_tool without snapshotserver

- conf/s3.conf
Signed-off-by: Lijin Xiong <legion.xiong@gmail.com>
Change-Id: I667266706676776d6e6977697173627969766f61
Issue Number: the last line of conf/s3.conf will not be copied when make image
Problem Summary: this issue will chunkserver failed to start, errors as below
```
I 2022-07-21T10:55:07.117681+0800     7 chunkserver_main.cpp:28] ChunkServer starting.
I 2022-07-21T10:55:07.117946+0800     7 chunkserver.cpp:89] Loading Configuration.
F 2022-07-21T10:55:07.176982+0800     7 s3_adapter.cpp:106] 
*** Check failure stack trace: ***
*** Aborted at 1658372107 (unix time) try "date -d @1658372107" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7) received by PID 7 (TID 0x7fab8ed9c240) from PID 7; stack trace: ***
@     0x7fab8e1aa0e0 (unknown)
@     0x7fab8c6defff …
```
> [skipci] fix the last line of s3 conf not copied when make image

- curvefs/proto/mds.proto
- curvefs/src/client/common/config.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/mds/fs_info_wrapper.cpp
- curvefs/src/mds/fs_info_wrapper.h
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/trash.cpp
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
- curvefs/test/mds/fs_info_wrapper_test.cpp
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mds_service_test.cpp
- curvefs/test/metaserver/inode_manager_test.cpp
related to issue: 1213/1582/1463
1. All mount points on the same file system are either enableCto, or they do not guarantee consistency.
2. If enableCto, attr and dentry cache will auto set invalid.
3. Consistency of multi-mount nodes under delete operation is not guaranteed. If one mount point deletes a file,
the behavior of the other mount point for all operations on that file is unknown.
Issue Number: #1213 #1582 #1463 
How it Works:
> curvefs/client: fix cto bugs

- curvefs/test/client/test_fuse_client.cpp
The first param of GetInodeAttr in FuseOpGetXattr_EnableSumInDir_Failed utest is changing at concurrent scenarios, it depends witch thread run faster.
How it Works:
> curvefs: fix utest at concurrent scenarios

- curvefs/proto/metaserver.proto
- curvefs/src/client/async_request_closure.cpp
- curvefs/src/client/async_request_closure.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/rpcclient/BUILD
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/volume/bitmap_allocator.cpp
- curvefs/test/client/mock_metaserver_client.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
Signed-off-by: Hanqing Wu <wuhanqing@corp.netease.com>
Issue Number: #1779
How it Works:
> curve-fuse: update attr and extent in single rpc (#1779)

- curvefs/src/mds/topology/topology_metric.cpp
- curvefs/test/mds/topology/test_topology_metric.cpp
Issue Number: #1805 
if metaserver offlines, the metirc is inaccurate on copyset_num, partition_num of it.
How it Works:
> fix topology metric inaccurate when metaserver offline

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/test/client/mock_client_s3_adaptor.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/metaserver/mock_metaserver_s3_adaptor.h
Signed-off-by: hzwuhongsong [hzwuhongsong@corp.netease.com](mailto:hzwuhongsong@corp.netease.com)
Issue Number: #1802  
Added warmup function, then we can warmup the file to local cache directory  before we need it.
> curvefs/client: add feature of warmup

- curvefs/src/mds/schedule/copysetSchedule.cpp
> copyset schedule select copyset random

- README.md
- README_cn.md
Issue Number: (#1819)
1. Some users have problems in our README.md build guide. I think we only maintain the curveadm for users.
2. I change the README.md some styles.
1. Remove some links to the deploy.md.
2. You can easily watch the README.md changes here https://github.com/fansehep/curve/tree/fix_doc
How it Works:
> [skipci] docs: make README.md more pretty and remove old build guides Links

- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
after use new aws sdk, the PutObject will start upload until all the objs in queue have uploaded,
so it may be takes a long time.
so we need move the upload to S3ClientAdaptorImpl when write is failed
Issue Number: #1826
> curvefs/client: fix bugs after use new aws sdk

- nebd/src/common/uncopyable.h
- src/chunkserver/copyset_node_manager.h
- src/common/uncopyable.h
Problem Summary: The class of Uncopyable is not mordern style and bad.
The old design make this class disconstruct function be virtual 😮‍💨 . 
There are about **20+ class** extends this class in our project. 
So there is a big virtual table in this uncopybale class.
1. remove the uncopyable class disconstruct func virtual.
How it Works: 
1. I think some coding needs re-review. 😢 
> update: use modern style rewrite the uncopyable and fix its' destructor be normal

- curvefs/src/mds/topology/topology_item.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore_fstream.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/s3compact/s3compact_test.cpp
- curvefs/test/metaserver/s3compact/s3compact_worker_test.cpp
The filetype2inode information is stored in partitioninfo, and the
restart of the metaserver will cause a rebuild, so the number will be
abnormal
How it Works:
> curvefs: fix filetype inode error in metric

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/test/client/mock_disk_cache_manager.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
SetDiskInitUsedBytes may takes a long time, so use a separate thread to do this.
otherwise it will block FuseOpInit
Issue Number: #1842
> curvefs/client: use separate thread to call SetDiskInitUsedBytes(#1842)

- curvefs/src/client/fuse_s3_client.cpp
if all objs has cached, then the function will block
Issue Number: #1841  
Issue Number: #1833
> curvefs/client: fix warmup bug(#1841)

- curvefs/src/metaserver/storage/converter.cpp
- curvefs/src/metaserver/storage/storage_fstream.h
with type (#1807)
Problem Summary: std::ostreamstring in high version gcc / clang is unavailable in this case.
More details please see this issue. #1767
And libabseil is high performance than std::ostreamstring. It is a good suggest to disabled c++ standard IOStream in our project from now on. The design of c++ standard IOStream is so difficult to use and slow performance.
How it Works:
> fix: use absl::StrCat instead of std::ostreamstring and erace some enum

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- src/common/concurrent/task_thread_pool.h
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Issue Number: #1854 
add a work queue and a thread to handle async s3 request
How it Works:
move throttle check outside main loop, async s3 request will not block main loop
> avoid deadlock when calling s3async callback, issue #1854

- curvefs/proto/metaserver.proto
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/inode_manager_test.cpp
- curvefs/test/metaserver/metastore_test.cpp
Issue Number: #1850 
Problem Summary: see issue
What's Changed: add fuse client rpc to the three replicas tv_sec(sec) and tv_nsec(ns).
How it Works:
> curvefs/metaserver: fix inode create time inconsistent

- curvefs/src/client/common/common.h
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_wrapper.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/test/client/test_fuse_client.cpp
fix the update inode nlink logic, the previous logic will update nlink incorrect at:
The fixed logic is every update of nlink to metaserver should refresh from metaserver first.
Issue Number: #1904  
How it Works:
> curvefs/client: fix update nlink error

- curvefs/src/client/fuse_s3_client.cpp
stop s3 when where are download because of warmup, so umount will block
Issue Number: #1841
> curvefs/client: fix umount bug(#1841)

- thirdparties/aws/Makefile
aws sdk sdk s3 range get 
1. head -> parse content-length and content-range header
2. split object to to multi part downloads
some s3 backends do not support return content-range when do head request, so request will fail.
remove content-range check, content-length is enough.
How it Works:
> update aws-sdk-cpp: fix s3 range get compatibility issue

- src/common/leaky_bucket.h
- test/common/throttle_test.cpp
burst is 0 but burstlenth is non-zero,so the function of SetLimit not work default.
How it Works:
> curvefs/client: fix throttle bug

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/src/client/inode_wrapper.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_inode_cache_manager.cpp
- thirdparties/aws/Makefile
1. write some data to file and the inode attr in icache not sync to metaserver.
2. readdir will batch get inode attr from metasever and cached in vfs. But the length of inode is older.
3. read the data new written will failed.
How it Works:
> curvefs: fix batch get inodeattr when readdir

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_wrapper.h
- curvefs/src/client/xattr_manager.cpp
- curvefs/src/client/xattr_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inodeWrapper.cpp
> curvefs: implement setxattr interface.

- curvefs/conf/client.conf
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/inode_cache_manager.cpp
- curvefs/src/client/inode_cache_manager.h
- curvefs/test/client/mock_inode_cache_manager.h
- curvefs/test/client/test_fuse_client.cpp
- curvefs/test/client/test_inode_cache_manager.cpp
The OpGetInodeAttr will refresh inode from metaserver into cache when enable cto. The metadata will be overwritten if inode is dirty in icache.
How it Works:
> curvefs: fix refresh inode will overwrite data in cache when enabel cto

- src/tools/mds_client.cpp
- src/tools/mds_client.h
- src/tools/namespace_tool.cpp
- src/tools/namespace_tool_core.cpp
- src/tools/namespace_tool_core.h
- test/tools/mock/mock_mds_client.h
- test/tools/mock/mock_namespace_tool_core.h
- test/tools/namespace_tool_core_test.cpp
- test/tools/namespace_tool_test.cpp
create directory: curve_ops_tool create -fileName=/dir1 -isDir=true -userName=test -password=123
BTW, delete directory is already supported.
Issue Number: #2035
How it Works:
```
root@5dd029eb85a9:/curvebs# ./curve_ops_tool create --example
Example: 
curve_ops_tool create -fileName=/test -userName=test -password=123 -fileLength=20 [-stripeUnit=32768] [-stripeCount=32]  [-mdsAddr=127.0.0.1:6666] [-confPath=/etc/curve/tools.conf]
curve_ops_tool create -dirName=/dir -userName=test -password=123 [-mdsAddr=127.0.0.1:6666] [-confPath=/etc/curve/tools.conf]
The first example can create a volume and the second create a directory.
root@5dd029eb85a9:/curvebs# ./curve_ops_tool create -fileName=/dir11/test2 -userName=test -password=123 -fileLength=20 -stripeUnit=32768 …
```
> support create volume directory by curve_ops_tool

- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/list/client/client.go
- tools-v2/pkg/cli/command/curvebs/list/list.go
- tools-v2/pkg/config/bs.go
Issue Number:  #2037
add subcommand client in curve bs list
How it Works:
> feat: [curve/toos-v2]: add list client #2037

- .gitignore
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/test_disk_cache_manager_impl.cpp
Issue Number: #2025  
add `use ReadCache` and some Related function.
How it Works:
Add `useReadCache` to decide if use read cache. If do, write to the read cache and update to s3 async.
> curvefs/client:  local cache policy optimization

- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/delete/delete.go
- tools-v2/pkg/config/bs.go
Signed-off-by: 申屠鹏会 <shentupenghui@gmail.com>
Issue Number: #2030 
Add delete command in tools-v2
How it Works:
None
> [skipci]add delete impl

- WORKSPACE
- replace-curve-repo.sh
- src/chunkserver/raftlog/curve_segment_log_storage.cpp
- src/chunkserver/raftlog/curve_segment_log_storage.h
- test/chunkserver/raftlog/test_curve_segment_log_storage.cpp
Signed-off-by: tangwz <tangwz.com@gmail.com>
Issue Number: #2071 
Update braft to latest version v1.1.2
How it Works:
> [compile] update the braft to vesion v1.1.2

- util/image.sh
deploy curvefs need snapshotclone_addr:
The original pr didn't run ci : https://github.com/opencurve/curve/pull/2089
How it Works:
> fix image.sh

- Makefile
- util/build.sh
- util/install.sh
Issue Number: #2104
`make help` will give examples about building and installing.  
Don't print usage msg on encountering failure in util/build.sh and util/install.sh.  
How it Works:
> Add help_msg in Makefile

- conf/chunkserver.conf
- conf/chunkserver.conf.example
- src/chunkserver/chunkserver.cpp
- src/chunkserver/config_info.h
- src/chunkserver/copyset_node.cpp
- src/chunkserver/copyset_node.h
- src/chunkserver/copyset_node_manager.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.cpp
- src/chunkserver/datastore/chunkserver_chunkfile.h
- src/chunkserver/datastore/chunkserver_datastore.h
- test/chunkserver/chunkserver_test_util.cpp
- test/chunkserver/copyset_node_manager_test.cpp
- test/chunkserver/copyset_node_test.cpp
Issue Number: #1887 
Problem Summary: see issue.
I use SyncChunkThread instread of the synctimer, Let each write determine on its own whether to notify. and the sumWrite is shared. Default 30s or sum of write >= 4 MB(maybe 4MB is not better) will force sync.
We need **some tests or benchmarks** for this changes to verify this design is better than old synctimer design.
---
And i think 4 MB as the default threshold is not accurate, Maybe we can use ```binary search``` to find the best thredhold for most machines.
> curvebs/chunkserver: optimize sync chunk when write in bulk

- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_client.cpp
If rename file under the same dir, the udapteInodeParent is needn't
How it Works:
> curvefs/client: improve updata inode parent when rename

- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
> curvefs/client: fix client core dump error

- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_storage_codec.cpp
- curvefs/src/mds/topology/topology_storage_codec.h
- curvefs/src/mds/topology/topology_storge_etcd.cpp
- curvefs/test/client/rpcclient/base_client_test.cpp
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/client/rpcclient/mock_mds_base_client.h
- curvefs/test/client/rpcclient/mock_topology_service.h
- curvefs/test/mds/mock/mock_topology.h
- curvefs/test/mds/topology/test_topology.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/mds/topology/test_topology_service.cpp
- curvefs/test/mds/topology/test_topology_storage_etcd.cpp
- curvefs/test/mds/topology/topology_storage_codec_test.cpp
- src/common/encode.h
1. fix
2. add storage codec ut
3. add DecodeBigEndian
4. add storage etcd ut
5. add topology manager ut
6. add topology service ut
7. add topology ut
8. add clinet ut
How it Works:
> [fix]curvefs/client init core dump && add ut

- .bazelrc
Problem Summary: default gcc6.3 ouput is white, but we can add this flag to make it have colorful output.
How it Works:
> [skipci] make gcc colorful output

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/copyset.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/delete/delete.go
- tools-v2/pkg/cli/command/curvebs/delete/file/file.go
- tools-v2/pkg/cli/command/curvebs/delete/peer/copyset.go
- tools-v2/pkg/cli/command/curvebs/delete/peer/leader.go
- tools-v2/pkg/cli/command/curvebs/delete/peer/leader_test.go
- tools-v2/pkg/cli/command/curvebs/delete/peer/peer.go
- tools-v2/pkg/cli/curvecli.go
- tools-v2/pkg/config/bs.go
Issue Number: https://github.com/opencurve/curve/issues/2021
we'd like to support `remove peer` command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)
`remove peer` is one of the commands to make configuration changes to a raft replication group.
- The implementation of the old tool is here：
https://github.com/opencurve/curve/blob/5e49aed29c6cbf75f046373ecfd17ec0d3fbe0c5/src/tools/curve_cli.cpp#L99
- The old command input and out put:
```
remove-peer : remove the peer from the copyset
curve_ops_tool remove-peer --example
Example
curve_ops_tool remove-peer -logicalPoolId=1 -copysetId=10001 -peer=127.0.0.1:8080:0 -conf=127.0.0.1:8080:0,127.0.0.1:8081:0,127.0.0.1:8082:0 -max_retry=3 -timeout_ms=100
output:
remove peer ok
```
- The new command we want:
```
curve bs …
```
> [skipci]feat(peer): add remove peer command for bs

- curvefs/test/client/client_memcache_test.cpp
Because sh is used to start memcheched, the `sh` process is killed instead of the memcached.`tee` process to hang, grep fail.
Use execlp to start memcached directly.
How it Works:
> [fix]curefs/client: memcache test hang

- test/integration/common/peer_cluster.cpp
- test/integration/common/peer_cluster.h
Add ConfirmLeader to WaitLeader. If a follower is waked up after hang, it may deal with a expire heartbeat info and get a wrong leader. So follower must confirm the get leader
How it Works:
> curvebs|unit test|supply WaitLeader

- thirdparties/etcdclient/Makefile
use golang.google.cn to downlaod go1.12.8
How it Works:
> [fix] use golang.google.cn to dowanlod go1.12.8

- curvefs/proto/metaserver.proto
- curvefs/src/client/common/common.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/test/client/test_fuse_s3_client.cpp
#2200 
1. The xattr value maybe some encoded string which contains '\0', so use strlen() to get char array buf's length will return a wrong length.
2. The encoded value maybe not UTF-8 format, so change xattr proto form 'string' to 'bytes' 
How it Works:
> curvefs: fix getxattr return wrong length

- curvefs/proto/mds.proto
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/mds/metaserverclient/metaserver_client.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/src/mds/topology/topology_manager.h
- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mock/mock_topology.h
Signed-off-by: Yatoro ajb459684460@gmail.com
Issue Number: https://github.com/opencurve/curve/issues/2043
Problem Summary: The resources created in the previous steps need to be cleaned up when create fs failed.
Make sure all resources are cleaned up on every steps of creating fs.
How it Works:
> curvefs: clean up resources after failing to create fs

- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
fix deadlock when umount
if unint clean threadPool that is not locked,
try to join, but thread in threadPool try to lock,
that will cause deadlock
How it Works:
> [fix]curvefs/client: umount deadlock

- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/kvclient/memcache_client.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/test/client/client_memcache_test.cpp
1. When running the vdbech task, the memory usage of the mount point is very high
2. When running the vdbech task, the mount will coredump or the task will have data inconsistency
3. The memcache server fails over and then restarts and cannot be used by the client anymore
Issue Number: #2251 #2250 #2248 #2247 #2246  
How it Works:
> curvefs/client: bug fix about memcache

- curvefs/test/client/client_memcache_test.cpp
Issue Number: https://github.com/opencurve/curve/issues/2295
How it Works:
> curvefs: add memcached startup check

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/update/peer/peer.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
add cli `curve bs update peer`, corresponding to old cli `curve_ops_tool reset-peer`.
How it Works:
```bash
curve bs update peer
```
1. `curve_ops_tool check-copyset -logicalPoolId=1 -copysetId=1 --detail`
```
peer_id: 10.246.159.82:8201:0
state: LEADER
...
peer_id: 10.246.159.82:8200:0
state: FOLLOWER
...
peer_id: 10.246.159.82:8202:0
state: FOLLOWER
```
2. curveadm stop first peer and second peer
3. `curve_ops_tool check-copyset -logicalPoolId=1 -copysetId=1 --detail`
```
Copyset is not healthy!
[4294967297]
peer_id: 10.246.159.82:8202:0
state: FOLLOWER
```
4. `./curve bs update peer  10.246.159.82:8202:0 --logicalpoolid=1 --copysetid=1 --rpcretrytimes=1 --rpctimeout=10s`
output:
``` …
```
> [tools-v2] add CLI `curve bs update peer`

- README.md
- README_cn.md
In the README.md/README_cn.md, In Contribute Us Part, click the [Curve Open Source Community Guidelines]/[Curve 开源社区指南], it comes out a 404 page not found.
How it Works:
I think this link should jump to developers_guide.md/developers_guide_cn.md.
Update the original links to developers_guide.md/developers_guide_cn.md and change the name[Curve Open Source Community Guidelines]/[Curve 开源社区指南] to [Curve Developers Guidelines]/[Curve 开发者指南].
- [√ ] Relevant documentation/comments is changed or added
> [skipci] doc: update two jump links in README/README_cn.md

- developers_guide.md
- developers_guide_cn.md
Issue Number: 
Click the [中文版]/[English Version], it comes out a 404 page not found.
How it Works:
I think this link should jump to developers_guide.md/developers_guide_cn.md.
- [√] Relevant documentation/comments is changed or added
- [√ ] I acknowledge that all my contributions will be made under the project's license
> [skipci] doc: update two jump links in developers_guide/developers_guide_cn.md

- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/test/client/mock_disk_cache_write.h
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/client/test_disk_cache_write.cpp
Issue Number: https://github.com/opencurve/curve/issues/1669
don't need to call `UploadAllCacheWriteFile()` twice
How it Works:
> curvefs/client: optimize DiskCacheManager::UmountDiskCache()

- tools-v2/pkg/cli/command/curvebs/delete/file/file.go
Issue Number: #2402 
Problem Summary: curve bs delete file raises panic
What's Changed: /tools-v2/pkg/cli/command/delete/file.go
How it Works: registering the flags for RPC communication in the Init function
> [fix]tools-v2: bs delete file

- curvefs/src/client/common/common.cpp
- curvefs/src/client/common/common.h
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/test_fuse_s3_client.cpp
- tools-v2/pkg/cli/command/curvefs/warmup/add/add.go
- tools-v2/pkg/config/fs.go
> [feat]curvefs/client:support warmup to disk/mem

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/proto.go
- tools-v2/pkg/cli/command/curvebs/create/create.go
- tools-v2/pkg/cli/command/curvebs/create/dir/dir.go
- tools-v2/pkg/cli/command/curvebs/create/file/create.go
- tools-v2/pkg/cli/command/curvebs/create/file/file.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/seginfo/segment.go
- tools-v2/pkg/config/bs.go
1. create file
2. create dir
How it Works:
```bash
curve bs create file --path /test2/test4  --size 10GiB 
+---------+
| RESULT  |
+---------+
| success |
+---------+
curve bs create dir --path /test2/test5            
+---------+
| RESULT  |
+---------+
| success |
+---------+
```
> [feat]tools-v2:create

- docs/en/build_and_run_en.md
Document modify：
Modify `build_and_run_en.md`, change "Mainland China optional" to "Optional for Chinese mainland"，because both mainland and taiwan are one China. The adj should be China, not mainland.
reference:
[1] [为什么不要把「中国大陆」说成mainland China？](https://zhuanlan.zhihu.com/p/260814062)
[2] [embassy's translation](http://ae.china-embassy.gov.cn/eng/lsyw/1/1/)
> [skipci] doc: modify build_and_run_en.md

- tools-v2/pkg/cli/command/curvebs/create/file/file.go
- tools-v2/pkg/config/bs.go
some bugs in `size` flag in `bs create file`
What's Changed: /tools-v2/pkg/cli/command/curvebs/create/file/file.go and /tools-v2/pkg/config/bs.go
How it Works: use uint64 instead of string and change this flag to optional
> [fix]: toos-v2: bs create file

- docs/cn/mds.md
> [skipci] doc: fix mds.md(module name error)

- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/test/client/metric/BUILD
- curvefs/test/client/metric/client_metric_test.cpp
Issue Number: #2319
Problem Summary: Use `static const std::string xxx` to replace `const std::string xxx`  in a struct type.
What's Changed: some metric class in `curvefs/src/client/metric`, add a cpp file to initialize it;
How it Works: static variables only have one copy for all objects, so it occupy less memory in this way.
> [fix] optimize some metric style in curvefs

- tools-v2/docs/zh/develop.md
> [skipci] doc: tools-v2/develop.md(href 404)

- tools-v2/docs/zh/develop.md
针对playground环境不能使用snapshot相关指令的问题，新增单机部署流程。
并修改之前命令可能不正确的地方。
新的目录形式如下：
- [curve tool 开发者指南](#curve-tool-开发者指南)
- [目录](#目录)
- [整体设计](#整体设计)
- [项目组织结构](#项目组织结构)
- [Curve 命令的实现（添加）](#curve-命令的实现添加)
- [Curve 命令开发调试](#curve-命令开发调试)
- [利用提供的playground docker镜像部署](#利用提供的playground-docker镜像部署)
- [部署 Curve 集群](#部署-curve-集群)
- [环境准备](#环境准备)
- [编译](#编译)
- [调试](#调试)
- [调试流程](#调试流程)
- [在物理机上部署](#在物理机上部署)
- [部署curve集群](#部署curve集群)
- [环境准备](#环境准备-1)
- [编译](#编译-1)
- [调试](#调试-1)
- [调试流程](#调试流程-1)
> [skipci] doc: tools-v2/develop.md(add deployment stand-alone )

- tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
1. the error "no leader peer" status is still ok
2. copysetKey2Status is unused
What's Changed: modify /tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
How it Works:
> [fix]tools-v2: supplementary status collection

- tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/query.go
- tools-v2/pkg/config/bs.go
1. make rpc GetChuckServerListInCopyset supports multiple request
2. GetChuckServerListInCopyset command should not be exported
modify tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
modify tools-v2/pkg/cli/command/curvebs/query/chunk/chunkserver.go
modify tools-v2/pkg/cli/command/curvebs/query/query.go
modify tools-v2/pkg/config/bs.go
How it Works:
> [feat]tools-v2: GetChuckServerListInCopyset supports multiple request

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/copyset.go
- tools-v2/internal/utils/string.go
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/check/check.go
- tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/status/copyset/get_copyset_status.go
- tools-v2/pkg/config/bs.go
Issue Number: #2354 
Problem Summary: support check copyset command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)
add tools-v2/pkg/cli/command/curvebs/check/check.go
add tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
add tools-v2/pkg/cli/command/curvebs/status/copyset/get_copyset_status.go
modify tools-v2/pkg/cli/command/curvebs
modify tools-v2/pkg/config/bs.go
modify tools-v2/internal/utils/copyset.go
modify tools-v2/internal/error/error.go
modify tools-v2/README.md
How it Works:
```shell
root@09e6445fe6e0:/# curve bs check copyset -h                                
Usage:  curve bs check copyset [flags]
check copysets health in curvebs
Flags:
-c, --conf string             config file (default is
$HOME/.curve/curve.yaml or …
```
> [feat]tools-v2: add check copyset

- tools-v2/README.md
- tools-v2/pkg/cli/command/curvebs/list/client/client.go
- tools-v2/pkg/cli/command/curvebs/status/client/client.go
- tools-v2/pkg/cli/command/curvebs/status/status.go
Issue Number: #2345
Problem Summary:  add client-status in tools-v2
1. command `curve bs list client`, modify return result to make it correct.
2. add command `curve bs status client` in (`tools-v2/pkg/cli/command/curvebs/status/client`)
How it Works:
just a client command. reuse command  `curve bs list client`, and get status from client list.
the result in tools-v1:
```
Client status: 
nebd-server: version-9.9.9+2c4861ca: 2
```
the result in tools-v2:
```
+-------------+----------------+---------------------+-----+
|    TYPE     |    VERSION     |        ADDR         | NUM |
+-------------+----------------+---------------------+-----+
| nebd-server | 9.9.9+2c4861ca | 192.168.20.149:9001 | 2   |
+             +                +---------------------+     +
|             | …
```
> [feat] tools-v2: add client-status

- tools-v2/README.md
- tools-v2/internal/utils/cobra.go
- tools-v2/internal/utils/flag.go
- tools-v2/internal/utils/proto.go
- tools-v2/internal/utils/string.go
- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvebs/check/operator/operator.go
- tools-v2/pkg/cli/command/curvebs/update/throttle/throttle.go
- tools-v2/pkg/cli/command/curvefs/status/metaserver/metaserver.go
- tools-v2/pkg/cli/curvecli.go
- tools-v2/pkg/config/bs.go
- tools-v2/pkg/config/config.go
- tools-v2/pkg/config/fs.go
1. Separate global flags from local flags
2. Add a function to automatically generate finalcmd example 3 take `bs check operator` and `bs update throttle` ad example
How it Works:
```bash
curve bs update throttle --help                          
Usage:  curve bs update throttle [flags]
update file throttle params
Flags:
--burst uint            burst (default 30000)
--burstlength uint      burst length (default 10)
--limit uint            limit[required]
--mdsaddr string        mds address, should be like 127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702
--password string       user password (default "root_password")
--path string           file path[required]
--rpcretrytimes int32   rpc retry times (default 1)
--rpctimeout duration   rpc …
```
> [feat] Adjust help output

- tools-v2/README.md
- tools-v2/docs/zh/develop.md
- tools-v2/pkg/cli/command/curvebs/status/etcd/etcd.go
- tools-v2/pkg/cli/command/curvebs/status/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/status/status.go
- tools-v2/pkg/config/bs.go
- tools-v2/pkg/config/curve.yaml
Issue Number: #2346
Problem Summary:  support `bs status snapshot` command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)
What's Changed:  
1. add snapshot command(`snapshot.go`) in `curve/tools-v2/pkg/cli/command/curvebs/status` (also modify some code style in `etcd.go` and `mds.go`).
2. add new command reference in `tools-v2/pkg/cli/command/curvebs/status/status.go`.
3. add snapshot clone config in config file(`tools-v2/pkg/config`) and modify the user config file.
How it Works: using command `curve bs status snapshot`
Side effects(Breaking backward compatibility? Performance regression?): just client
the result in tools-v1:
```
SnapshotCloneServer status:
version: 9.9.9+2c4861ca
current snapshot-clone-server: 192.168.20.149:5550
online snapshot-clone-server …
```
> [feat] tools-v2: add snapshot-clone-status

- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/update/leader/leader.go
- tools-v2/pkg/cli/command/curvebs/update/peer/peer.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
Issue Number: #2022
Problem Summary: add command `curve bs update leader`
1. modified:   internal/utils/row.go
2. new file:   pkg/cli/command/curvebs/update/leader/leader.go
3. modified:   pkg/cli/command/curvebs/update/peer/peer.go
4. modified:   pkg/cli/command/curvebs/update/update.go
How it Works:
implement by using `TransferLeaderRequest2` rpc.
step 1: transfer leader from 192.168.20.149:8202:0 to 192.168.20.149:8201:0
```shell
$ curve bs update leader 192.168.20.149:8201:0 --logicalpoolid=1 --copysetid=1 --peers=192.168.20.149:8200:0,192.168.20.149:8201:1,192.168.20.149:8202:2
+-----------------------+-----------------------+---------+---------+--------+
|        LEADER         |       OLDLEADER       | COPYSET | RESULT  | REASON | …
```
> [feat] tools-v2: add transfer-leader

- tools-v2/README.md
- tools-v2/pkg/cli/command/curvebs/update/scan_state/scan_state.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/config/bs.go
Issue Number: #2360 
support bs set scan command in [curve tool]
1.  add tools-v2/pkg/cli/command/curvebs/update/scan_state.go
2. modify tools-v2/pkg/cli/command/curvebs/update.go
3. modify tools-v2/pkg/config/bs.go
4. modify tools-v2/README.md
How it Works:
```
Usage:  curve bs update scan-state [flags]
enable/disable scan for logical pool
Flags:
-c, --conf string            config file (default is $HOME/.curve/curve.yaml or /etc/curve/curve.yaml)
-f, --format string          output format (json|plain) (default "plain")
-h, --help                   print help
--logicalpoolid uint32   logical pool id[required]
--mdsaddr string         mds address, should be like 127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702
--rpcretrytimes int32    rpc retry times (default …
```
> [feat] tools-v2: add scan-state

- tools-v2/pkg/config/bs.go
Issue Number: #2431
solve panic
```
root@f8df310173eb:/# ./curve bs status mds
+----------------+----------------+------------------------------+----------+
|      ADDR      |   DUMMYADDR    |           VERSION            |  STATUS  |
+----------------+----------------+------------------------------+----------+
| 127.0.0.1:6701 | 127.0.0.1:7701 | v2.1.0-beta+09566f57+release | follower |
+----------------+----------------+                              +          +
| 127.0.0.1:6702 | 127.0.0.1:7702 |                              |          |
+----------------+----------------+                              +----------+
| 127.0.0.1:6700 | 127.0.0.1:7700 |                              | leader   |
+----------------+----------------+------------------------------+----------+ …
```
> [fix] tools-v2: fix robust string process

- mk-deb.sh
- mk-tar.sh
- thirdparties/memcache/Makefile
Part of #2024 .
Since #2024 will be reserved for OSPP2023, so only necessary build fixes and cleanups are included in this PR. It will NOT solve that issue.
**What's Changed:**
- fix missing dependency (`memcache` and `rocksdb`) issues when using on a clean build machine
- clean up code by removing unnecessary error checking (replaced with `errexit`)
- format shell script to make it human-readable
Note that the first part of the `mk-deb.sh` and `mk-tar.sh` is intentionally made the same, so we can merge them easily later.
**Side effects(Breaking backward compatibility? Performance regression?):**
No. The build logic is not touched. Only additional dependency (`memcache` and `rocksdb`) is installed.
> build: refactor and fix build issues in mk-deb.sh and mk-tar.sh

- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/list/client/client.go
- tools-v2/pkg/cli/command/curvebs/status/client/client.go
- tools-v2/pkg/cli/command/curvebs/status/etcd/etcd.go
- tools-v2/pkg/cli/command/curvebs/status/mds/mds.go
- tools-v2/pkg/cli/command/curvebs/status/snapshot/snapshot.go
Problem Summary: fix return error format (special case: when we run a command, and it init fail, err is nil...)
1. modified:   internal/error/error.go
2. modified:   pkg/cli/command/curvebs/list/client/client.go
3. modified:   pkg/cli/command/curvebs/status/client/client.go
4. modified:   pkg/cli/command/curvebs/status/etcd/etcd.go
5. modified:   pkg/cli/command/curvebs/status/mds/mds.go
6. modified:   pkg/cli/command/curvebs/status/snapshot/snapshot.go
How it Works:
return a non-nil err to client, client can judge by `err.Code`.
> [fix] tools-v2: fix return error format

- curvefs/conf/client.conf
- curvefs/src/client/BUILD
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/client_s3_cache_manager.h
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/data_cache_test.cpp
- curvefs/test/client/file_cache_manager_test.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
Issue Number: https://github.com/opencurve/curve/issues/2070
`FileCacheManager::ProcessKVRequest` processes kvRequests one by one, maybe we can increase the concurrency
- Handle kvRequests through TaskThreadPool
- Cancel all threads and return when any kvRequests fail
How it Works:
> Curvefs: enable async read for `FileCacheManager::ReadKVRequest`

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/copyset.go
- tools-v2/pkg/cli/command/curvebs/list/list.go
- tools-v2/pkg/cli/command/curvebs/list/server/server.go
- tools-v2/pkg/cli/command/curvebs/query/chunkserver/chunkserver_recover.go
- tools-v2/pkg/config/bs.go
Issue Number: #2036 
Problem Summary:  support list chunkserver command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)
What's Changed: add /tools-v2/pkg/cli/command/curvebs/list/chunkserver.go 
How it Works: curve bs list chunkserver
```
root@d6c388ef51ff:/# ./curve bs list chunkserver 
+----+------+-----------+------+-----------+------------+------------+-----------------------------------------------+--------------+-------------+------------------+-----------+
| ID | TYPE |    IP     | PORT | RWSTATUS  | DISKSTATE  | COPYSETNUM |                  MOUNTPOINT                   | DISKCAPACITY |  DISKUSED   | UNHEALTHYCOPYSET |  EXTADDR  |
+----+------+-----------+------+-----------+------------+------------+-----------------------------------------------+---------- …
```
> feat: [curve/toos-v2] add list chunkserver

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/common/config.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/client_s3_adaptor_test.cpp
- curvefs/test/client/data_cache_test.cpp
- curvefs/test/client/file_cache_manager_test.cpp
- curvefs/test/client/fs_cache_manager_test.cpp
Depends on: https://github.com/opencurve/curve/pull/2492
Problem Summary: after that, fuseMaxSize is not needed anymore
How it Works:
> curvefs/client: remove unused setting fuseMaxSize 

- curvefs/conf/client.conf
- curvefs/src/client/error_code.h
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
Issue Number: https://github.com/opencurve/curve/issues/2427
- `FuseS3client` exit when `writeCacheMaxByte <= 8MB`
How it Works:
> curvefs/client: fuse client exit when cache size less than 8MB

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/test/client/test_fuse_s3_client.cpp
Issue Number: #2225 
Problem Summary: add qos for curve-fuse, then we can limits the bandwidth or IOPS
1.  Read the configuration from the  client.conf
2.  enable the throttle
It does not start by default
> curvefs/client: add qos for curve-fuse,  we can limits the bandwidth

- curvefs_python/curvefs_wrap.cxx
in python3, str need encode/decode, but what we need is binary data. old code works in python2, but not python3.
cbdclient read/write accept bytes instead of str
How it Works:
> change cbdclient python binding read/write to bytes instead of str

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/copyset.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/copyset_by_host.go
- tools-v2/pkg/cli/command/curvebs/list/unavailcopysets/unavailcopysets.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
- tools-v2/pkg/cli/command/curvebs/query/chunkserver/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
- tools-v2/pkg/cli/command/curvebs/update/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/config/bs.go
Issue Number: #2357  
Problem Summary: support update availflag command in [curve tool](https://github.com/opencurve/curve/tree/master/tools-v2)
add tools-v2/pkg/cli/command/curvebs/list/unavailcopysets/unavailcopysets.go
add tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
add tools-v2/pkg/cli/command/curvebs/list/chunkserver/copyset_by_host.go
add tools-v2/pkg/cli/command/curvebs/set/set.go
add tools-v2/pkg/cli/command/curvebs/update/copyset/copyset.go
add tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
modify tools-v2/internal/error/error.go
modify tools-v2/internal/utils/row.go
modify tools-v2/pkg/cli/command/curvebs/bs.go
modify tools-v2/pkg/config/bs.go
modify tools-v2/pkg/cli/command/curvebs/update/update.go
modify …
> [feat]tools-v2: add update copyset availflag

- buildfs.sh
> fix buildfs.sh failed on debian11

- curvefs/conf/client.conf
- curvefs/src/client/filesystem/rpc_client.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
> curvefs/client: fixed some minor bugs.

- tools-v2/pkg/cli/command/base.go
- tools-v2/pkg/cli/command/curvefs/list/copyset/copyset.go
when run `curve fs status copyset`, while get error:
```bahs
rpc error: code = ResourceExhausted desc = stream terminated by
RST_STREAM with error code: FLOW_CONTROL_ERROR
```
Refer to [issue](https://github.com/apache/brpc/issues/1087).
Issue Number: #2524 2524 
How it Works:
> [fix]fs list copysetinfo err

- src/mds/topology/topology_service_manager.cpp
The judgment condition is wrong. If it is the old way, as long as filterScanning is set, the filter will be started regardless of the value, which is inconsistent with expectations.
How it Works:
> [fix]get copyset in clusetr

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/offline_chunkserver.go
- tools-v2/pkg/cli/command/curvebs/list/list.go
- tools-v2/pkg/cli/command/curvebs/list/may-broken-vol/may-broken-vol.go
Issue Number: #2356 
add tools-v2/pkg/cli/command/curvebs/list/chunkserver/offline_chunkserver.go
add tools-v2/pkg/cli/command/curvebs/list/may-broken-vol/may-broken-vol.go
modify tools-v2/pkg/cli/command/curvebs/list/list.go
How it Works:
Usage: 
```bash
$curve bs list may-broken-vol --help
Usage:  curve bs list may-broken-vol [flags]
list all volumes on majority offline copysets
Flags:
-f, --format string         output format (json|plain) (default "plain")
--mdsaddr string        mds address, should be like 127.0.0.1:6700,127.0.0.1:6701,127.0.0.1:6702
--rpcretrytimes int32   rpc retry times (default 1)
--rpctimeout duration   rpc timeout (default 10s)
Global Flags:
-c, --conf string   config file (default is $HOME/.curve/curve.yaml or …
```
> [feat]tools-v2: add bs list may-broken-vol

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/proto/curvebs/schedule/statuscode.proto
- tools-v2/internal/utils/row.go
- tools-v2/mk-proto.sh
- tools-v2/pkg/cli/command/curvebs/update/leader_schedule/leader_schedule.go
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/config/bs.go
Issue Number: #2359 
How it Works:
curve bs update leader-schedule --logicalpoolid 1
curve bs update leader-schedule-all
+---------+--------+
| RESULT  | REASON |
+---------+--------+
| success | null       |
+---------+--------+
+--------+--------------------+
| RESULT |          REASON       |
+--------+--------------------+
| failed    | InvalidLogicalPool |
+--------+--------------------+
> [feat] tools-v2: add update leader-schedule[-all]

- tools-v2/internal/error/error.go
- tools-v2/internal/error/error_test.go
- tools-v2/internal/utils/health.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/list/space/space.go
- tools-v2/pkg/cli/command/curvebs/status/chunkserver/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/status/cluster/cluster.go
- tools-v2/pkg/cli/command/curvebs/status/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/status/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/status/status.go
- tools-v2/pkg/config/bs.go
- tools-v2/pkg/config/config.go
How it Works:
`curve bs status cluster`
The output is as follows：
Services:
| ROLE | LEADER | ONLINE | OFFLINE |
| -------- | :--------: | -------- | -------- |
|    etcd     | 10.0.0.1:23790 | 10.0.0.2:23790 <br> 10.0.0.3:23790 |         |
|    mds     | 10.0.0.1:6700 | 10.0.0.2:6700 <br> 10.0.0.3:6700 |         |
|    chunkserver     | - | 10.0.0.1:8200 <br> 10.0.0.2:8200 <br> 10.0.0.3:8200 |         |
|    snapshot     | 10.0.0.1:5555 |  10.0.0.2:5555 <br> 10.0.0.3:5555 |         |
Copyset:
| POOLID | TOTAL | OK | WARN | ERROR |
| -------- | -------- | -------- | -------- |-------- |
|   1    |  100  | 94 |  3   |   3   |
Space:
|   TYPE   | USED |  LEFT  | RECYCLABLE | CREATED |
| -------- | -------- | -------- | :--------: | …
> [feat] tools-v2: add bs status cluster

- tools-v2/pkg/cli/command/curvebs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/list/chunkserver/offline_chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunk.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkinfo.go
- tools-v2/pkg/cli/command/curvebs/query/chunkserver/chunkserver.go
- tools-v2/pkg/cli/command/curvebs/query/copyset/get_copyset_status.go
- tools-v2/pkg/cli/command/curvebs/query/file/file.go
- tools-v2/pkg/cli/command/curvebs/update/copyset/availflag/availflag.go
- tools-v2/pkg/cli/command/curvefs/check/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/list/partition/partition.go
- tools-v2/pkg/cli/command/curvefs/list/topology/topology.go
- tools-v2/pkg/cli/command/curvefs/query/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/query/copyset/status.go
- tools-v2/pkg/cli/command/curvefs/query/inode/inode.go
Issue Number: #2535 
Problem Summary: remove the pointer of map
What's Changed: remove all *map from struct and function
How it Works:
The map in Golang itself is a reference type and does not need to be declared as a pointer type
> [refactor]tools-v2: refactor all *map to map

- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
It turns out that mem and disk are not separated, the storage of mem is asynchronous, and the storage of disk is synchronous, so when it is deleted later, it is generally written. Later, after the separation of the two, an exception occurred in the asynchronous save of mem.
How it Works:
> [fix] warmup to mem error

- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/mds.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/metaserver.h
Add idle_timeout_sec option to reduce server resource
How it Works:
> mds/metaserver: Add idle_timeout_sec option

- curvefs/src/metaserver/trash.cpp
- curvefs/test/metaserver/BUILD
- curvefs/test/metaserver/trash_test.cpp
When the file is deleted, the object will not be deleted forever.
the objects that will be removed  is based on chunklist, now , chunklist is empty always
How it Works:
> curvefs/client: fix s3 object will not be removed

- include/client/libcurve.h
- nebd/src/part2/request_executor_curve.cpp
- nebd/src/part2/request_executor_curve.h
- nebd/test/part2/mock_curve_client.h
- nebd/test/part2/test_request_executor_curve.cpp
- src/client/libcurve_client.cpp
- src/client/libcurve_file.cpp
- src/client/libcurve_file.h
- test/client/libcurve_client_unittest.cpp
- test/client/mock/mock_file_client.h
> client supports mounting volumes in different clusters

- docker/debian9/Dockerfile
debian9 eol. rm apt cmd
It will cause the execution of modprobe nbd to fail when the bs client container restarts.
How it Works:
> [fix] rm apt cmd in bs

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/snapshot/copyset/all.go
- tools-v2/pkg/cli/command/curvebs/snapshot/copyset/copyset.go
- tools-v2/pkg/cli/command/curvebs/snapshot/copyset/one.go
- tools-v2/pkg/cli/command/curvebs/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/update/leader_schedule/leader_schedule.go
- tools-v2/pkg/config/bs.go
Issue Number: #2352 
How it Works:
curve bs snapshot copyset --all
```
+----------------+---------+
|  CHUNKSERVER   | RESULT  |
+----------------+---------+
| **.*.*.**:8200 | failed  |
+----------------+---------+
| **.*.*.**:8201 | success |
+----------------+         +
| **.*.*.**:8202 |         |
+----------------+---------+
```
> [feat] tools-v2: add snapshot copyset --all

- curvefs/conf/metaserver.conf
- curvefs/src/client/rpcclient/metacache.cpp
- curvefs/src/client/rpcclient/metacache.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/task_excutor.cpp
- curvefs/src/client/rpcclient/task_excutor.h
- curvefs/src/metaserver/copyset/config.h
- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/src/metaserver/copyset/meta_operator.cpp
- curvefs/src/metaserver/copyset/raft_node.h
- curvefs/src/metaserver/metaserver.cpp
- curvefs/test/client/rpcclient/metacache_test.cpp
- curvefs/test/client/rpcclient/metaserver_client_test.cpp
- curvefs/test/client/rpcclient/mock_metacache.h
- curvefs/test/client/rpcclient/mock_metaserver_service.h
- curvefs/test/client/rpcclient/test_task_executor.cpp
- curvefs/test/metaserver/copyset/copyset_node_test.cpp
- curvefs/test/metaserver/copyset/meta_operator_test.cpp
- curvefs/test/metaserver/copyset/mock/mock_copyset_node.h
- curvefs/test/metaserver/copyset/mock/mock_raft_node.h
Problem Summary: feat: support braft lease read for curvefs
What's Changed: enable braft lease, change request handler in metaserver.
How it Works:
> [feat] CurveFS: support braft lease read

- src/client/metacache_struct.h
Problem Summary: delete apply index in client
How it Works:
> [feat] CurveBS: delete apply index in client

- curvefs/proto/topology.proto
- curvefs/src/mds/topology/topology.cpp
- curvefs/src/metaserver/register.cpp
- curvefs/src/tools/create/curvefs_create_topology_tool.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
- curvefs/test/mds/topology/test_topology_service.cpp
Issue Number: #2493  
How it Works:
> [feat]curvefs: change hostname to optional

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/metaserver/s3compact/s3compact_test.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Issue Number: https://github.com/opencurve/curve/issues/2499
Let user agent item configurable for users having security reasons
How it Works:
> curvefs/client: make user agent configurable

- mk-tar.sh
Fix the problem that compilation fails when there is only pyhton3
How it Works:
> [skipci][fix]fix mk-tar

- WORKSPACE
- curvefs/src/metaserver/copyset/copyset_node.h
- curvefs/test/client/chunk_cache_manager_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/data_cache_test.cpp
- curvefs/test/metaserver/storage/dumpfile_test.cpp
- nebd/src/common/timeutility.h
- nebd/src/part2/metafile_manager.cpp
- nebd/test/part1/fake_file_service.cpp
- src/chunkserver/raftlog/curve_segment.cpp
- src/common/timeutility.h
- src/tools/mds_client.cpp
- src/tools/snapshot_clone_client.cpp
- test/chunkserver/raftlog/common.cpp
- test/mds/topology/test_topology_service_manager.cpp
- thirdparties/brpc/fix-gcc11.patch
- tools/curvefsTool.cpp
* Support build on GCC 11+.
* Add a patch to brpc.
* Fix mismatched `new[]` and `delete`. 
How it Works:
* Add `-D__const__=__unused__` to brpc `CXX_FLAGS`.
* Change `CopysetNode::GetAppliedIndex` memory order to `std::memory_order_acquire`.
https://github.com/opencurve/curve/blob/c30eff073d91fabb7a51c84663da1aad144c5f46/curvefs/src/metaserver/copyset/copyset_node.h#L304
See also:
* [GCC -Winvalid-memory-model warning option](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Winvalid-memory-model)
* [Built-in Functions for Memory Model Aware Atomic Operations](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html)
> [Build]: Support build on GCC 11+

- src/chunkserver/concurrent_apply/concurrent_apply.cpp
- src/chunkserver/concurrent_apply/concurrent_apply.h
- src/chunkserver/copyset_node.cpp
- src/chunkserver/op_request.cpp
- src/chunkserver/op_request.h
- test/chunkserver/concurrent_apply/concurrent_apply_test.cpp
unify bs and fs apply queue.
How it Works:
simply moving `Schedule` in apply queue to `ChunkOpRequest` as a utils.
> [refactor] CurveBS: unify bs and fs apply queue

- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/pkg/cli/command/curvebs/check/check.go
- tools-v2/pkg/cli/command/curvebs/check/chunkserver/chunkserver.go
Issue Number: #2353
What's Changed: ./pkg/cli/command/check/chunkserver, ./pkg/cli/command/check/check.go and README.md
How it Works: use wrapper function `GetCopySetsInChunkServer` to get the copyset list in chunkserver, then use wrapper function `CheckCopysets` to check copysets.
> [feat]tools-v2:curve bs check chunkserver

- CHANGELOG-2.6.md
> [skipci] docs: added changelog v2.6.

- curvefs/conf/metaserver.conf
- curvefs/src/metaserver/metaserver.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.h
- curvefs/test/metaserver/metaserver_s3_adaptor_test.cpp
Issue Number: #2597 
How it Works:
> [opt] curvefs: Change the confusing configuration name

- curvefs/proto/metaserver.proto
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/mds/metaserverclient/metaserver_client.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/metaserver/partition_clean_test.cpp
- curvefs/test/metaserver/partition_test.cpp
- curvefs/test/metaserver/recycle_cleaner_test.cpp
- curvefs/test/metaserver/recycle_manager_test.cpp
Issue Number: #2548  
How it Works:
> [feat]: curvefs: merge two rpc into one rpc when makenode

- curvefs/src/mds/topology/topology.cpp
The mds maybe get the if of retired metaserver when deal with heartbeat from metaserver:
This bug was triggered after the metaserver was added with a new role after changing the disk：
How it Works:
> fix curvefs mds get metaserver

- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/test_fuse_s3_client.cpp
> [feat]curvefs/client:support warmup sym link

- curvefs/test/mds/fs_manager_test.cpp
- curvefs/test/mds/mds_service_test.cpp
- curvefs/test/mds/mock/mock_fs_stroage.h
Issue Number: #2505
All the test cases in these two files are written into one test suite, and the names of the test cases have no meaningful information. Once the code is modified, it is difficult to change the corresponding unit tests accordingly.
1. fs_manager_test.cpp
```
test_success_cleanup_after_fail_create_volume_fs_on_inode_error
test_success_cleanup_after_fail_create_volume_fs_on_dentry_error
test_success_create_volume_fs
test_success_create_s3_fs
test_success_monotonically_increasing_fsid_for_multiple_fs
test_fail_create_volume_fs_on_fail_partition_creation
test_fail_create_volume_fs_on_failed_root_node_creation
test_fail_create_s3_fs_on_failed_root_node_creation
test_fail_create_duplicate_s3_fs_with_different_fsname …
```
> [test] curvefs/mds: split large test cases into focused smaller ones

- .clang-format
- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/metric/BUILD
- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_adaptor.h
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.h
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.h
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/s3/disk_cache_write.h
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/client/warmup/warmup_manager.h
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/metric/client_metric_test.cpp
- curvefs/test/client/test_disk_cache_manager.cpp
- curvefs/test/client/test_disk_cache_manager_impl.cpp
- curvefs/test/metaserver/copyset/raft_cli_service2_test.cpp
- src/chunkserver/clone_copyer.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
Add bps, qps, latency metrics to the following:
1.  writeToS3
2. readFromS3
3. writeToDiskCache
4. readFromDiskCache
5. writeToKVCache
6. readFromKVCache
How it Works:
> [feat]add s3/diskcache/kvcache io metric

- curvefs/src/client/s3/disk_cache_base.cpp
- curvefs/src/client/s3/disk_cache_base.h
How it Works:
test.cpp:
```c++
#include <iostream>
#include <dirent.h>
#include <sys/stat.h> // Include the header file for struct stat
#include <ostream>
#include <string>
int main() {
struct stat statbuf;
std::string path;
std::cin >> path;
if (stat(path.c_str(), &statbuf) == 0){
if (S_ISREG(statbuf.st_mode)) {
std::cout << "normal file" << std::endl;
}
}
return 0;
}
```
output:
> [fix]curvefs/client: fix check filetype

- WORKSPACE
- conf/client.conf
- conf/cs_client.conf
- conf/py_client.conf
- conf/snap_client.conf
- curve-sdk/DEBIAN/control
- mk-deb.sh
- nebd/nebd-package/usr/bin/nebd-daemon
- src/chunkserver/raftlog/curve_segment.cpp
- src/client/client_config.cpp
- src/client/config_info.h
- src/client/libcurve_file.cpp
- src/client/mds_client.cpp
- src/client/metacache.cpp
- src/client/metacache.h
- src/client/metacache_struct.h
- src/client/splitor.cpp
- src/client/utils.cpp
- src/client/utils.h
- src/mds/main/main.cpp
- src/mds/nameserver2/curvefs.cpp
- src/mds/nameserver2/namespace_service.cpp
- test/client/client_unittest_main.cpp
- test/client/client_utils_test.cpp
- test/client/metacache_test.cpp
- thirdparties/braft/0001-fix-change-set_error-to-set_errorv.patch
- thirdparties/brpc/0001-bvar-warning-on-conflict-bvar-name.patch
> build: add braft format patch

- tools-v2/README.md
- tools-v2/pkg/cli/command/curvebs/update/update.go
- tools-v2/pkg/cli/command/curvebs/update/volume/flatten/flatten.go
- tools-v2/pkg/cli/command/curvebs/update/volume/volume.go
- tools-v2/pkg/config/bs.go
Issue Number: #2587  
add bs update volume flatten
modify tools-v2/pkg/cli/command/base.go
create tools-v2/pkg/cli/command/curvebs/update/volume/volume.go
create tools-v2/pkg/cli/command/curvebs/update/volume/flatten/flatten.go
How it Works:
Usage:
```bash
curve bs update volume flatten
```
Output:
```
+------+--------------------------------------+---------+            
| USER |               TASK ID                | RESULT  |            
+------+--------------------------------------+---------+            
| root | d26e27a8-fcbd-4f7a-adf8-53795217cbb0 | success |            
+------+--------------------------------------+---------+  
```
> [feat]tools-v2: add bs update volume flatten

- curvefs/src/mds/topology/topology.cpp
- curvefs/src/mds/topology/topology.h
- curvefs/src/mds/topology/topology_item.h
- curvefs/src/mds/topology/topology_manager.cpp
- curvefs/test/mds/topology/test_topology_manager.cpp
The previous logic of allocate inode range to partition is: index of partiton in this fs * range form conf.
For example, there are five partitions in fs and each manage 100 inodes:
p1 0-99
p2 100-199
p3 200-299
p4 300-399
p5 400-499
If you make  this conf value smaller(maybe 80) and upgrade mds:
p1 0-99
p2 100-199
p3 200-299
p4 300-399
p5 400-499
p6: 400-479    new allocated partition will have repetitive parts with previous partition.
Now we will change allocation algorithm and record max inodeId of fs.
previous:
after fix:
How it Works:
> improve partition range management

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/kvclient/kvclient.h
- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/kvclient_manager.h
- curvefs/src/client/kvclient/memcache_client.h
- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/test/client/client_memcache_test.cpp
- curvefs/test/client/client_s3_adaptor_Integration.cpp
- curvefs/test/client/metric/client_metric_test.cpp
- curvefs/test/client/mock_kvclient.h
1. fix base metric(bps/qps/latnecy) error
2. add hit and miss metric
3. change metric prefix to curvefs_kvclient_manager
4. add memcache client metric
How it Works:
> [feat]curvefs/client kvcache monitor

- curvefs/monitor/grafana/provisioning/dashboards/metaserver.json
- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/kvclient/memcache_client.h
- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/client/s3/client_s3_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager.cpp
- curvefs/src/client/s3/disk_cache_manager_impl.cpp
- curvefs/src/client/s3/disk_cache_write.cpp
- curvefs/src/client/warmup/warmup_manager.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.cpp
- curvefs/src/metaserver/s3/metaserver_s3_adaptor.h
- src/client/client_metric.cpp
- src/client/client_metric.h
> [feat]curvefs/metaserver: add delete inode monitor

- curvefs/conf/client.conf
- curvefs/src/client/common/config.cpp
- curvefs/src/client/fuse_client.cpp
- curvefs/src/mds/heartbeat/metaserver_healthy_checker.cpp
- curvefs/src/mds/heartbeat/metaserver_healthy_checker.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash_manager.cpp
- curvefs/test/client/filesystem/helper/builder.h
1. use gflag to change mds heartbeatMissTimeOutMs on fly
2. use gflag to change metaserver transh.expiredAfterSec on fly
3. use gflag to change metaserver transh.scanPeriodSec on fly
4. use gflag to change client fs.disableXattr on fly
5. set client s3.maxAsyncRequestInflightBytes default vale to 1GiB
How it Works:
------
1. heartbeatMissTimeOutMs
Use the following command to observe the status of the corresponding metaserver
```bash
watch -n 1 "curl -X POST http://xxx.xxx.xxx.xxx:xxxx/TopologyService/ListMetaServer -H 'Content-Type: application/protobuf'  -d $'{\n  \"serverID\": 1\n}' | jq"
```
Use the following command to modify the corresponding configuration items:
```bash
curl …
```
> [feat]curvefs/mds: change some config on fly

- curvefs/monitor/grafana/provisioning/dashboards/client.json
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/fuse_s3_client.h
- curvefs/src/client/metric/client_metric.cpp
- curvefs/src/client/metric/client_metric.h
> [feat]curvefs/client: split io attr/data latency

- curvefs/proto/mds.proto
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds_service.cpp
- curvefs/src/mds/mds_service.h
- curvefs/test/mds/mds_service_test.cpp
- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvefs/fs.go
- tools-v2/pkg/cli/command/curvefs/update/fs/fs.go
- tools-v2/pkg/cli/command/curvefs/update/update.go
- tools-v2/pkg/config/config.go
1. add mds rpc
2. add tools-v2 command
> add ability to change capacity in fsinfo

- curvefs/proto/mds.proto
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_s3_client.cpp
- curvefs/src/client/rpcclient/fsdelta_updater.cpp
- curvefs/src/client/rpcclient/fsdelta_updater.h
- curvefs/src/client/rpcclient/fsquota_checker.cpp
- curvefs/src/client/rpcclient/fsquota_checker.h
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/s3/client_s3_adaptor.cpp
- curvefs/src/mds/codec/codec.cpp
- curvefs/src/mds/codec/codec.h
- curvefs/src/mds/common/storage_key.h
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/fs_storage.cpp
- curvefs/src/mds/fs_storage.h
- curvefs/src/tools/curvefs_tool_define.cpp
- curvefs/test/client/test_fsquota_checker.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
- curvefs/test/mds/mock/mock_fs_stroage.h
1. client send delta update to mds
2. mds update usage both cache and etcd and response latest to client
3. client do quota check when operate
> curvefs: add quota support for s3 client using mds

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/check/check.go
- tools-v2/pkg/cli/command/curvebs/check/consistency/consistency.go
- tools-v2/pkg/cli/command/curvebs/query/chunk/chunkhash.go
- tools-v2/pkg/cli/command/curvebs/query/seginfo/seginfo.go
- tools-v2/pkg/cli/command/curvebs/status/copyset/agent.go
- tools-v2/pkg/config/bs.go
Issue Number: #2351  
Problem Summary: Add bs check consistency command.
modify tools-v2/README.md
modify tools-v2/internal/error/error.go
modify tools-v2/pkg/cli/command/curvebs/check/check.go
modify tools-v2/pkg/cli/command/curvebs/query/seginfo/seginfo.go
modify tools-v2/pkg/cli/command/curvebs/status/copyset/agent.go
add tools-v2/pkg/cli/command/curvebs/check/consistency/consistency.go
How it Works:
Usage:
```shell
curve bs check consistency --path /test
```
Output:
```shell
+--------+--------+------------+
|  NAME  | STATUS |   EXPLAIN  |
+--------+--------+------------+
| /test  |  ok    |      -     |
+--------+--------+------------+
```
> [feat]tools-v2: add bs check consistency

- src/common/arc_cache.h
- src/common/lru_cache.h
Issue Number: #2819
Add ARC Cache, an Adaptive Replacement Cache. 
Normal LRU cache is not scan-resistant while ARC is.
ARC also has ghost cache (key cache) can improve cache behavior.
A head file arc_cache.h is added and included by lru_cache.h
How it Works:
GetLast() function may not work as same as LRUCache, because ARC cache is not ordered by time when a cache
item is entered or hit.
> Add ARC, an Adaptive Replacement Cache.

- curvefs/monitor/target_json.py
> [fix]curvefs/monitor: target_json.py

- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/internal/utils/snapshot.go
- tools-v2/pkg/cli/command/curvebs/list/list.go
- tools-v2/pkg/cli/command/curvebs/list/snapshot/snapshot.go
- tools-v2/pkg/config/bs.go
Issue Number: #2832
add bs list snapshot command
How it Works:
> curve bs list snapshot

- tools-v2/internal/error/error.go
Issue Number: #2801
Problem Summary: Error messages contains character `%` cannot be output correctly because `%` is treated as the prefix of a format verb.
What's Changed: Replaced `fmt.Errorf(ce.Message)` with `errors.New(ce.Message)` in `ToError()`
How it Works: `errors.New` treats the error messages as plain text instead of format strings.
> [fix] tools-v2: fix incorrect error output

- curvefs/src/metaserver/metaserver.cpp
Issue Number: #2671  
How it Works:
> [opt]: Compatible with previous metaserver

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/internal/utils/row.go
- tools-v2/internal/utils/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/delete/volume/clone/clone.go
- tools-v2/pkg/cli/command/curvebs/delete/volume/recover/recover.go
- tools-v2/pkg/cli/command/curvebs/query/query.go
- tools-v2/pkg/cli/command/curvebs/query/volume/clone-recover/clone-recover.go
- tools-v2/pkg/cli/command/curvebs/query/volume/volume.go
- tools-v2/pkg/config/bs.go
Issue Number: #2584  
add bs query volume clone-recover
How it Works:
Usage:
```bash
curve bs query volume clone-recover
```
Output:
```bash
+------+--------------------------------------+--------------------------------------+----------+-------+----------+--------+----------+--------+----------+---------------------+
| USER |                 SRC                  |               TASK ID                | TASKTYPE | FILE  | FILETYPE | ISLAZY | NEXTSTEP | STATUS | PROGRESS |        TIME         |
+------+--------------------------------------+--------------------------------------+----------+-------+----------+--------+----------+--------+----------+---------------------+
| root | a19b5e5e-b306-488f-8e6d-d87282c869cb | d26e27a8-fcbd-4f7a-adf8-53795217cbb0 | …
```
> [feat]tools-v2: add bs query volume clone-recover

- conf/mds.conf
- conf/snapshot_clone_server.conf
- curvefs/conf/mds.conf
- curvefs/docker/debian11/Dockerfile
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/mds.h
- docker/debian11/Dockerfile
- src/chunkserver/chunkserver.cpp
- src/mds/server/mds.cpp
- src/mds/server/mds.h
- src/snapshotcloneserver/snapshotclone_server.cpp
- src/snapshotcloneserver/snapshotclone_server.h
- src/tools/metric_name.h
- thirdparties/etcdclient/etcdclient.go
- util/install.sh
> etcd support enable auth

- tools-v2/internal/utils/snapshot/snapshot.go
function snapshotutil.NewQuerySubUri does not add the version param.
How it Works:
> [fix]tools-v2: add version in function NewQuerySubUri

- curvefs/src/client/curve_fuse_op.cpp
- curvefs/src/mds/main.cpp
- curvefs/src/metaserver/main.cpp
- nebd/src/part2/main.cpp
- src/chunkserver/chunkserver.cpp
- src/common/log_util.h
- src/mds/main/main.cpp
- src/snapshotcloneserver/main.cpp
Issue Number: #2811
How it Works:
* Set `FLAGS_stderrthreshold` to `3`, so only FATAL log will write to stderr.
See also:[Glog Doc](https://github.com/google/glog#setting-flags)
Effect:
```log
┌──(nature㉿LAPTOP-9TS0FG11)-[~/curve]
└─$ docker ps -a
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS          PORTS                                                                                            NAMES
af01056361a9   curvebs:unknown       "/entrypoint.sh --ro…"   13 seconds ago   Up 12 seconds                                                                                                    focused_hofstadter
55a1484d3ef6   portainer/portainer   "/portainer"             5 months ago     Up 4 hours …
```
> [Fix]: Stop write log to stderr, when `FLAGS_logtostderr` is `false`

- tools-v2/README.md
- tools-v2/pkg/cli/command/curvebs/bs.go
- tools-v2/pkg/cli/command/curvebs/stop/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/stop/stop.go
Issue Number: https://github.com/opencurve/curve/issues/2579
add curve bs stop volume snapshot
How it Works:
curve bs stop volume volumeSnapshot
> Curvebs stop volume snapshot

- curvefs/src/mds/fs_manager.cpp
- curvefs/test/mds/fs_manager_test2.cpp
Issue Number: #2779  
How it Works:
> [fix] curvefs: mds: createfs error

- curvefs/proto/metaserver.proto
- curvefs/src/client/fuse_client.cpp
- curvefs/src/client/fuse_client.h
- curvefs/src/client/rpcclient/metaserver_client.cpp
- curvefs/src/client/rpcclient/metaserver_client.h
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/client/test_fuse_volume_client.cpp
- curvefs/test/metaserver/partition_test.cpp
Issue Number: #2548 
How it Works:
> [feat]: curvefs: merge two rpc into one when delete

- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvefs/status/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/etcd/etcd.go
- tools-v2/pkg/cli/command/curvefs/status/mds/mds.go
- tools-v2/pkg/cli/command/curvefs/status/metaserver/metaserver.go
Issue Number: #2878 
When the commands `status cluster` relies on returns an error while `init`, the `cmd.Error` is nil, causing the command to panic. Since I don't have the environment, I am not sure if this is the cause of the problem, but it is risky.
How it Works:
> [fix]tools-v2: panic when show cluster status

- src/common/configuration.cpp
- src/common/string_util.h
- test/common/string_util_test.cpp
Issue Number: https://github.com/opencurve/curve/issues/2898
How it Works:
> [fix] s3 user agent configuration is incorrect

- conf/s3.conf
- curvefs/conf/client.conf
- curvefs/conf/mds.conf
- curvefs/conf/metaserver.conf
- curvefs/test/client/client_s3_test.cpp
- curvefs/test/client/test_fuse_s3_client.cpp
- curvefs/test/metaserver/s3compact/s3compact_test.cpp
- src/common/s3_adapter.cpp
- src/common/s3_adapter.h
This reverts commit 0346d8291eb31997ca8e251df42373d73a6d2be6.
How it Works:
> Revert "curvefs/client: make user agent configurable"

- curvefs/docker/debian11/entrypoint.sh
- curvefs/docker/openeuler/entrypoint.sh
- curvefs/src/client/s3/disk_cache_manager.cpp
- docker/debian11/entrypoint.sh
- docker/openeuler/entrypoint.sh
- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvefs/status/copyset/copyset.go
- tools-v2/pkg/cli/command/curvefs/status/etcd/etcd.go
- tools-v2/pkg/cli/command/curvefs/status/mds/mds.go
- tools-v2/pkg/cli/command/curvefs/status/metaserver/metaserver.go
> Pick some pull request to release2.7

- src/client/file_instance.cpp
- src/client/file_instance.h
- src/client/libcurve_file.cpp
- test/client/BUILD
- test/client/file_instance_test.cpp
- test/client/mock/mock_namespace_service.h
> curvebs(client): Fix always get file info from cache

- curvefs/proto/metaserver.proto
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash.h
- curvefs/src/metaserver/trash_manager.cpp
- curvefs/src/metaserver/trash_manager.h
- curvefs/test/metaserver/partition_test.cpp
- curvefs/test/metaserver/trash_test.cpp
> curvefs: fix trash will delete file data more than once

- curvefs/proto/mds.proto
- curvefs/src/client/lease/lease_excutor.cpp
- curvefs/src/client/rpcclient/BUILD
- curvefs/src/client/rpcclient/mds_client.cpp
- curvefs/src/client/rpcclient/mds_client.h
- curvefs/src/mds/fs_manager.cpp
- curvefs/src/mds/fs_manager.h
- curvefs/src/mds/mds.cpp
- curvefs/src/mds/mds_service.cpp
- curvefs/src/mds/mds_service.h
- curvefs/test/client/lease/lease_executor_test.cpp
- curvefs/test/client/rpcclient/mds_client_test.cpp
- curvefs/test/client/rpcclient/mock_mds_client.h
- curvefs/test/mds/fs_manager_test.cpp
- src/client/mds_client.cpp
- src/client/mds_client.h
- tools-v2/pkg/cli/command/curvefs/update/mds/clientMdsAddrsOverride.go
- tools-v2/pkg/cli/command/curvefs/update/mds/mds.go
we need to make client alive when migrate mds to new ones. so we add online client mds addrs override to broadcast by session. 
tool -> send SetClientMdsAddrsOverride to mds, will keep active mds
mds -> refresh session send to client
client -> change mds addr to override ones
use case:
client -> mds A,B,C
change to client -> mds A,B,C,D,E,F
change to client -> mds D,E,F
> curvefs: support client mdsaddrs override

- curvefs/src/client/kvclient/kvclient_manager.cpp
- curvefs/src/client/metric/client_metric.h
Issue Number: #2841  
Problem Summary: Get和Set方法会加到线程池，大量Get和Set的情况下线程池里的任务会大量堆积，这里使用bvar变量对线程池里的Get和Set进行计数。
client_metric.h：结构体KVClientManagerMetric中增加了两个bvar变量（getQueueSize和setQueueSize）分别用来对Get和Set计数。
kvclient_manager.cpp：在类KVClientManager的Get和Set方法里改变bvar变量的值。
How it Works: 任务加入到线程池，对bvar变量进行+1操作，任务结束，bvar变量及时-1。
Side effects(Breaking backward compatibility? Performance regression?): 无
> curvefs/client: get and set counts

- WORKSPACE
- curvefs/src/metaserver/copyset/concurrent_apply_queue.cpp
- thirdparties/brpc/0002-Support-fork-without-exec.patch
- thirdparties/brpc/0003-Add-docs-on-fork-w-o-exec.patch
- thirdparties/brpc/0004-not-register-pthread_atfork-in-child-process.patch
- thirdparties/brpc/0005-Fix-LatencyRecorder-qps-not-accurate.patch
- thirdparties/brpc/0006-fix-1973-1863.patch
> Backport bvar fork fixes

- curvefs/src/metaserver/copyset/copyset_node.cpp
- curvefs/src/metaserver/inode_manager.cpp
- curvefs/src/metaserver/inode_manager.h
- curvefs/src/metaserver/inode_storage.cpp
- curvefs/src/metaserver/inode_storage.h
- curvefs/src/metaserver/metastore.cpp
- curvefs/src/metaserver/metastore.h
- curvefs/src/metaserver/partition.cpp
- curvefs/src/metaserver/partition.h
- curvefs/src/metaserver/storage/converter.cpp
- curvefs/src/metaserver/storage/converter.h
- curvefs/src/metaserver/storage/rocksdb_storage.cpp
- curvefs/src/metaserver/storage/rocksdb_storage.h
- curvefs/src/metaserver/storage/storage.h
- curvefs/src/metaserver/trash.cpp
- curvefs/src/metaserver/trash.h
- curvefs/src/metaserver/trash_manager.h
- curvefs/test/metaserver/copyset/raft_cli_service2_test.cpp
- curvefs/test/metaserver/inode_storage_test.cpp
- curvefs/test/metaserver/trash_test.cpp
> curvefs/metaserver: fix trash bugs

- curvefs/src/mds/topology/topology.cpp
Different order of acquiring locks in  `AddMetaServer` and `RemoveMetaServer` may cause deadlock.
How it Works:
> fix curvefs topology lock

- curvefs/test/common/arc_cache_test.cpp
- src/common/arc_cache.h
In the original ARC paper, there was no explanation of how Remove should be handled when the cache is full. The Remove operation would have a side effect on subsequent Put operations when the cache is not full, which is still evicting items even though it's clear that there is no need to evict when the cache is not full.
Now, code has been added to check if the cache is full to avoid performance degradation.
Also fix c_, it should be max_count.
Also add unittest.
Issue Number: #2962
How it Works:
> Fix side effect of Remove operation.

- tools-v2/README.md
- tools-v2/internal/utils/row.go
- tools-v2/internal/utils/snapshot/const.go
- tools-v2/pkg/cli/command/curvebs/create/create.go
- tools-v2/pkg/cli/command/curvebs/create/volume/snapshot/snapshot.go
- tools-v2/pkg/cli/command/curvebs/create/volume/volume.go
- tools-v2/pkg/cli/command/curvebs/update/volume/flatten/flatten.go
- tools-v2/pkg/config/bs.go
Issue Number: #2585  
modify tools-v2/internal/utils/snapshot.go
modify tools-v2/internal/utils/row.go
modify tools-v2/pkg/cli/command/curvebs/create/create.go
modify tools-v2/pkg/config/bs.go
add tools-v2/pkg/cli/command/curvebs/create/volume/snapshot/snapshot.go
add tools-v2/pkg/cli/command/curvebs/create/volume/volume.go
How it Works:
Usage:
```bash
curve bs create volume snapshot --user root --filename test --snapshotname snap-test
```
Output:
```
+------+----------+--------------+
| USER | FILENAME | SNAPSHOTNAME |
+------+----------+---------------
| root |   test   |  snap-test   |
+------+----------+--------------+
```
> [feat]tools-v2: add bs create volume snapshot

- src/common/lru_cache.h
- test/client/client_metric_test.cpp
- test/client/libcbd_ext4_test.cpp
- test/client/libcurve_client_unittest.cpp
- test/client/mock/mock_file_client.h
Issue Number: #2946 
Problem Summary: current cache promotion and demotion need to copy a duplica, erase old elem and reinsert duplica.
What's Changed: optimize cache promotion and demotion using `list.splice` and add some tests.
How it Works: `list.splice` will update cache object priority without object duplica, list reinsertion and hashtable update.
> Perf(common): optimize cache promotion and demotion

- tools-v2/README.md
- tools-v2/internal/error/error.go
- tools-v2/pkg/cli/command/curvebs/recover/recover.go
- tools-v2/pkg/cli/command/curvebs/recover/volume/volume.go
- tools-v2/pkg/config/bs.go
Issue Number: #2588  
Problem Summary: add recover as a middle command, and it has sub-command volume.
What's Changed: add recover middle command directory, and subcommand directory volume. 
How it Works: recover.go is the middle command. Inside the sub-direcotry volume , the volume.go is the final command, while the recover.go wraps the RecoverFilePRC to execute the real recover procedure.
- [yes] Relevant documentation/comments is changed or added
- [yes] I acknowledge that all my contributions will be made under the project's license
> [feat]tools-v2: add bs recover volume 
